### ISSUE TITLE
OAI-PMH: harvesting all digitized records

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1000]
Somewhat related to #999. 

@mccalluc: Is there a way to create a separate feed that allows for harvesting of records for all digitized assets and not just those that are in the Online Reading Room. We need a way for Digital to harvest metadata to be used in building the game. 

If the metadata for all digitized records is currently available using a different method, please let me know.

**Comment by mccalluc** [comment]
I could do this, but I believe you are satisfied with the existing APIs? Reopen if I am mistaken.
