### ISSUE TITLE
Cross-site security for transcripts

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#1005]
Chrome has this helpful message on http://americanarchive.org/catalog/cpb-aacip_111-02c8693q :
>
Text track from origin 'https://s3.amazonaws.com' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://americanarchive.org' is therefore not allowed access.

(FF is not working, either, but there is no error message. When Chrome is fixed, see if that also helps FF.)

**Comment by caseyedavis12** [comment]
@mccalluc: Will we need to transfer the SRT files to web VTT for the captions to appear on the site again?

**Comment by mccalluc** [comment]
Either that, or figure out why they stopped working.

**Comment by mccalluc** [comment]
I'm going to approach this by making a controller than will make the conversion on the fly. For the long run, we might want to apply the same code to the whole batch on s3.

**Comment by afred** [comment]
@caseyedavis12 @foo4thought I'm not familiar with this bug, but the fix for it in #1010 is causing a new bug: #1033. Do either of you have any more detail than what's in the comments here? thanks.

**Comment by mccalluc** [comment]
@afred: I don't have any real memory of this, but another approach would be to set up cname pointing to s3: if it's a subdomain, I think that will satisfy browser security. (But there might be a way to get the original fix working, too.)

**Comment by afred** [comment]
thanks @mccalluc, that's a good suggestion if I can't find any secret sauce in the CORS specs
