### ISSUE TITLE
spelling mistakes in WGBH metadata

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#1015]
http://americanarchive.org/catalog?f[series_titles][]=The+First+Amendment&f[access_types][]=all

> Each episode features a _converstaion_ that examines civil _liberities_ in the media in the 1970s

**Comment by sroosa** [comment]
Having Kevin run a script in the AMS tables that will change all records with this description to the same description but with the typos fixed. He will then reindex those records on AAPB. I'll close when the process is complete

**Comment by caseyedavis12** [comment]
@sroosa is this done?
