### ISSUE TITLE
Player does not appear on record in Chrome

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1031]
In Chrome, when a user goes to a record page for a digitized asset, the video player does not appear on the screen. One has to click the "play" button, and the player will then appear. The player should appear automatically without the user having to click on the play button. This is not an issue in Firefox or Safari.

![screen shot 2016-08-09 at 8 35 51 am](https://cloud.githubusercontent.com/assets/5992135/17516550/f15d4776-5e0c-11e6-84ad-59211e4b7b80.png)

**Comment by caseyedavis12** [comment]
@afred @muraszko: This is an issue for On Location access using Google Chrome.

When one is not present at WGBH or the Library of Congress, there is a different problem, perhaps related: When one uses Google Chrome from a remote location, no media plays whatsoever. One can click on the play button, and nothing happens.

**Comment by afred** [comment]
@caseyedavis12 oh, gotcha. Please see #1033.

**Comment by afred** [comment]
@caseyedavis12 is this still happening for you? It's working for me.

To be clear, this is the issue where the poster image is not showing up, but the video still plays. If poster images are showing up for you, then we can close it.

**Comment by caseyedavis12** [comment]
@afred: I just checked it this did not happen to me today. We can close.
