### ISSUE TITLE
Do not keep large downloads from AMS on the webserver

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#1035]
**Done when** only 1 AMS download (the most recent) is kept on the webserver at any given time.

**Comment by jasoncorum** [comment]
@afred, if you'd like me to take a look at this ticket, let me know when you're free to walk through it.

**Comment by jasoncorum** [comment]
Other potential refactors from review process:

1) Get rid of the disparate naming of the downloaded files. Stick with a known path.
2) Have 2 distinct steps for "download the thing from AMS" and "ingest the thing you downloaded"
3) Have 1 step that defaults to: "download if needed, then ingest"

**Comment by afred** [comment]
closed by #1115
