### ISSUE TITLE
Display anamorphic video in the AAPB in 16x9 aspect ratio

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1044]
@Afred, @muraszko: Some of the tapes that are being digitized for the American Masters project are anamorphic. For anamorphic video, the camera is 16:9, it's squished, then recorded 4:3 on a standard def machine. It's meant to be unsquished on play back. 

WNET (who manages the vendor contract) decided to keep all preservation, production and proxy files anamorphic 4:3 (to be unquished on playback) instead of keeping preservation and production files anamorphic 4:3 and but make the proxies 16:9. We would have preferred that they make the proxies 16:9, and this is the typical compromise for digitization projects, but we were not consulted on this question and now changing it is out of scope. 

We need to figure out how to handle the anamorphic proxy files we are getting from the American Masters project. Can our player be modified to recognize anamorphic video and then play it back as 16x9? The other alternative is to edit all of the anamorphic videos in the editing room and unsquish them and re-encode them. 

cc @cmhosale

**Comment by Muraszko** [comment]
Notes from discussion on how to solve this.  Long story short, configure the player to display 16:9 for anamorphic 4:3 video which will be marked in the metadata.

```
<p>
<strong>Example 1 - </strong> a 16:9 video in a 4:3 playback area, which results in the horizontal "letterbox" bars.
</p>
<video class="playback_area_4x3" controls="controls">
  <source src="https://s3.amazonaws.com/bostonlocaltv.org/video/cpb-aacip-504-0k26970d52.h264.mp4" type="video/mp4">
</video>

<br /><br />

<p>
<strong>Example 2 - </strong> 4:3 video in a 16:9 playback area, which results in the vertical "pillarbox" bars.
</p>
<video class="playback_area_16x9" controls="controls">
  <source src="https://ia600307.us.archive.org/26/items/SF121/SF121_512kb.mp4" type="video/mp4">
</video>

<br /><br />

<p>
<strong>Example 3 - </strong> stretch a 16:9 video element vertically into a 4:3 aspect ratio (approx) using CSS transform properties. There are 3 problems with this approach:
  <ol>
    <li>The video controls are also stretched along with the video.</li>
    <li>The stretching causes the vertical alignment to be off. Extra work is needed to reposition it correctly, which can be very tricky.</li>
    <li>The CSS transform properties are less likely to behave consistently across browsers than more commonly used properties.</li>
  </ol>
</p>
<video class="playback_area_16x9 make_taller" controls="controls">
  <source src="http://www.rwardell.com/rtw/video/fuelieclip.webm" type="video/webm">
</video>

<br /><br />

<p>
<strong>Example 4 - </strong> stretch a 4:3 video element horizontally into a 16:9 aspect ratio (approx) using CSS transform properties. Same problems here as with stretching vertically.
</p>
<video class="playback_area_4x3 make_wider" controls="controls">
  <source src="https://s3.amazonaws.com/bostonlocaltv.org/video/cpb-aacip-504-0k26970d52.h264.mp4" type="video/mp4">
</video>
```
![screen shot 2016-08-24 at 8 41 59 am](https://cloud.githubusercontent.com/assets/6650285/17931058/7932074c-69d7-11e6-8b86-95101ec3b076.jpg)

**Comment by afred** [comment]
Here's the fiddle, with the CSS that makes it work: https://jsfiddle.net/51t55x5L/4/

**Comment by afred** [comment]
@Muraszko @caseyedavis12 keep in mind the downsides of this approach:
  1. stretching a `<video>` element in this way also stretches the player controls along the bottom. In some cases, the left-most controls may end up outside of the viewable area.
  1. stretching vertically or horizontally affects the positioning of the element, which then may have to be compensated in tricky ways.
  1. I suspect that these advanced CSS properties may be less likely to be consistent across browsers.

Are you ok with these drawbacks?

**Comment by Muraszko** [comment]
@afred @caseyedavis12 
Would it be worth it to change the layout of the entire pages for these anamorphic vids?  Have it so the video element is sized to display the 16:9 box?

I imagine this may also be useful if we start to get more 16:9 content.

**Comment by caseyedavis12** [comment]
@muraszko, @afred: The video element is already wide enough for a 16x9 player, isn’t it?
http://americanarchive.org/catalog/cpb-aacip_398-61djhhq3

**Comment by afred** [comment]
@caseyedavis12 actually, the video is hardcoded right now to be 400px wide by 300px tall, so it's 4:3. Here is the source:

```html
<video controls="controls" crossorigin="anonymous" height="300" id="player-media" oncontextmenu="return false;" poster="http://americanarchive.org.s3.amazonaws.com/thumbnail/cpb-aacip_398-61djhhq3.jpg" preload="none" width="400">
      <source src="/media/cpb-aacip_398-61djhhq3?part=1" type="video/mp4">
</video>
```

The `height` and `width` properties of the `<video>` element define what is sometimes called the "playback area", and serves as a maximum boundary for the actual video that get's played inside.

Therefore, if you put a 16:9 video into a playback area that is 4:3, then it will have the horizontal "letterbox" bars. However, you can hide the bars from the user by making the background of the `<video>` element (i.e. the "playback area") the same color what's behind it, and remove any borders. I think is what we are doing.

**Comment by caseyedavis12** [comment]
Hey @afred: Oh, I see. I thought the “video element” you were referring to was the grey box behind the 4:3 player.


1.       The controls on the player being outside of the viewable area sounds like an unacceptable drawback.

2.       Do you mean that we may need to change the design of the “Record” page to accommodate the wider player?

3.       Could we test the jsfiddle examples in different browsers? Would that help us determine if it is compatible with other browsers?
Cc @muraszko

**Comment by afred** [comment]
> 1. The controls on the player being outside of the viewable area sounds like an unacceptable drawback.

Yeah, I tend to agree. There _might_ be a different HTML5 media player out there that allows you to apply CSS transform properties to the `<video>`  element without affecting the controls, but that would take some research (maybe ~4 hours) -- and if we found one, I presume it would compel us to change our media player (maybe ~8 hours).

> 2. Do you mean that we may need to change the design of the “Record” page to accommodate the wider player?

No, that shouldn't be necessary.

> 3.  Could we test the jsfiddle examples in different browsers? ...

Yes. However, manual cross-browser testing can be very time consuming, especially when you run into problems for which there are no clear solutions.

**Comment by afred** [comment]
@caseyedavis12 have we made a decision here yet?

**Comment by caseyedavis12** [comment]
@afred: Have we tested this solution with VideoJS? I know we were testing it with the HTML5 player.

**Comment by afred** [comment]
@caseyedavis12 ah.. good point. I don't think we've tried it with video-js.

**Comment by afred** [comment]
[This answer](http://stackoverflow.com/questions/22349444/showing-anamorphic-mp4-video-with-video-js) suggests that VideoJS should handle anamorphic just fine. However, it could be that the answerer doesn't understand the question correctly.

@caseyedavis12 do you have an example of an anamorphic video that we could throw into a VideoJS player and see what happens?

**Comment by cmhosale** [comment]
@afred this video can serve as our example: http://americanarchive.org/catalog/cpb-aacip_504-xd0qr4ph35

recorded as 4:3 but shot with an anamorphic lens, meaning the display ratio should be 16:9.

**Comment by cmhosale** [comment]
@afred do you have access to the AAPB Sony Ci account? This file, stored in the workspace, is an example: cpb-aacip-504-jd4pk07p0p.h264.mp4. If you don't have access I can index it into the AAPB public website.

The item is SD material recorded in 480x360, but shot with a widescreen lens so the content's display ratio is actually 16:9.

**Comment by afred** [comment]
@cmhosale I do have access to Ci. But first...

Can you double check [the link you gave](http://americanarchive.org/catalog/cpb-aacip_504-xd0qr4ph35) and confirm the problem. The poster image is "squished", but the video playback does not appear to be.

**Comment by caseyedavis12** [comment]
@afred, @jasoncorum, @cmhosale: all work done on this anamorphic video issue should be charged to:

Overhead
156840

**Comment by caseyedavis12** [comment]
@jasoncorum , @afred: here is an example of an anamorphic video: http://americanarchive.org/catalog/cpb-aacip_41-67jq2t1w

**Comment by jasoncorum** [comment]
@caseyedavis12 & @cmhosale – After digging in to the AAPB anamorphic video ticket on Github (#1044), Drew, Mike and I discussed the issue and we wanted to give you an overview of the testing we’ve done and outline potential next steps.

Testing an anamorphic video in in the video-js player shows that there doesn’t seem to be support. Essentially, even if we programmatically apply changes to the player around the 4:3 anamorphic video file, we still just get a 4:3 video horizontally letter-boxed in a 16:9 player. From what we found, the HTML 5 player (and corresponding wrappers like video-js) just don’t allow you to “unsquish” anamorphic video files on fly. Some CSS properties that Drew and I tried out allowed us to stretch or skew elements on a page (including the video itself), but support for them vary browser to browser and the transformations can bleed over to the video controls. This solution could be really brittle.

So, instead of trying to force video-js and HTML 5 player to do something they weren’t intended to do (and potentially have unintended issues crop up down the road), we think it makes more sense to use an FFMPEG script to transcode the files prior uploading to S3.

**Comment by cmhosale** [comment]
@jasoncorum @Muraszko @afred - @caseyedavis12 and I talked and I will work to transcode them. @Muraszko do you have a script that can batch delete proxies from Sony Ci?

**Comment by Muraszko** [comment]
@cmhosale Sorry, don't have a script to batch delete from Ci.  The easiest way would probably be to login to the Ci web app.  Change display to list view and sort by date ingested, then select multiple and delete.  Or, if all the ones you want to delete are from the same organization you can search by the first couple parts of the GUID.

**Comment by afred** [comment]
@cmhosale let us know if that works.

**Comment by caseyedavis12** [comment]
@afred: we will handle anamorphic videos by transcoding them.
