### ISSUE TITLE
MediaBox access

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1045]
We have been approved to implement the MediaBox Access for the AAPB. This is done when:

-AAPB metadata records for all digitized items that are not available in the ORR include a "Request MediaBox access" box next to the player.
-Clicking on the box will cause a new window to open with the Intro Paragraph and MediaBox rules of Use (will send separately).
-After reading the Rules, a user will click a box that says "Accept." 
-Clicking "Accept" will prompt the user to enter their email address, the Unique Identifier for that record(s) the are requesting, and then click a "Send Request" link.
-Casey will receive an email with the user's email and the requested GUIDs.

@afred, @muraszko: please let me know if you have better methods of achieving this.

**Comment by Muraszko** [comment]
Sounds good.  One suggestion, the request prompt could probably auto enter the identifier based on the record page the user is viewing.

Should this be added to a new, October milestone?  We're probably going to need Drew be focused September on other work.

**Comment by caseyedavis12** [comment]
@Muraszko: It would be great if the request prompt could auto identify the record page, but I would rather users put all identifiers in one email than for the same user to request 10 items and then I get 10 emails. Could we instead let users "save" records after accepting the Media Box Rules of Use and then when they finish their research, they can click "Send Request"?

Adding this to an October deliverable sounds good.

**Comment by afred** [comment]
Can you refresh my memory on what MediaBox offers?

**Comment by caseyedavis12** [comment]
@afred:

MediaBox is a feature of Sony Ci. It allows for admins of Sony Ci to login to Sony Ci and create unique URLs that provide password-protected, time-restricted access to select media files. This occurs outside of the AAPB website environment.

The idea is that when I get the automated email from a user requesting access, I will login to Sony Ci and create the links and then the link to them via email.

**Comment by afred** [comment]
Ok, so MediaBox gives us:
  1. URLs that expire
  1. Password protected access to media
  1. Serving the media from a website other than americanarchive.org.

Are all of these legal requirements for the "On Location" only media.

I ask because creating URLs that expire would probably be easier (and a better user experience) than using MediaBox.

But if the other two are necessary, then MediaBox would probably be the way to go.

**Comment by caseyedavis12** [comment]
@afed: Yes, 1 and 2 are required. Also, some materials are ineligible for MediaBox acess, and it requires a staff person to make that determination after a request is received.

**Comment by afred** [comment]
Cool.. then I have a few questions re: your proposed workflow in the original comment...

> -AAPB metadata records for all digitized items that are not available in the ORR include a "Request MediaBox access" box next to the player.

Users won't know what "MediaBox" is, and thus won't know whether they want to click on "Request MediaBox access" or not.
  1. Is there a benefit, or requirement, to keeping the "MediaBox™" branding?
  1. If not, can we just say "Request limited access"?

> -Clicking on the box will cause a new window to open with the Intro Paragraph and MediaBox rules of Use (will send separately).

I'm very much in favor of not using popup windows or shadow boxes. Can we just take them to a different page, like we do with our other TOS page?

> -After reading the Rules, a user will click a box that says "Accept."

Is this page something we design? Or does MediaBox have it's own TOS page?

> -Clicking "Accept" will prompt the user to enter their email address, the Unique Identifier for that record(s) the are requesting, and then click a "Send Request" link.

  1. Currently there is no database for AAPB, so the app doesn't have a way to store the requests that users have made over time. Right now, you would only be able to get a list of requests from the the INBOX of the destination email address.
    
    Adding a database would make sense here, but there is some overhead that comes with it.

  2. I'm in agreement with @Muraszko that it would be better to start out with 1 record per request, especially if we decide not to add a database.

  3. Very much in favor of not having the user type in the unique identifier. Even if we allow them to "save" items, we can still fetch the ID automatically for them.

You're missing the step where the user sets a password. Is this something that MediaBox handles, or will we have to?

**Comment by afred** [comment]
@caseyedavis12 @Muraszko there are a lot of question here that might be better hashed out in a live call. Let me know if you want to do that.

**Comment by caseyedavis12** [comment]
@afred: Mike is out this week, and last Friday I reached out to legal counsel about whether we could not use the MediaBox branding. I am waiting to hear back from them.

**Comment by caseyedavis12** [comment]
We have decided to handle all Limited Research Access (formerly MediaBox) requests via email instead of through the website. I will be adding a new section to the FAQ page. No dev work needed.
