### ISSUE TITLE
Close captions indexed but not communicated to user

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1055]
The closed caption SRT files are being indexed. When a user conducts a keyword search, items that have a CC file are retrieved, and sometimes that keyword does not appear elsewhere in the record. This is confusing to users who wonder why a record was retrieved when they do not see the keyword on the record page. 

Discuss: how to communicate to users that cc files are being indexed and may retrieve records that have keywords in the cc file which is hidden to the user in the public interface.

**Comment by afred** [comment]
Something like this?.. assuming the user searches for **Little Rock**...
![image](https://cloud.githubusercontent.com/assets/1507490/18935303/577823e4-859c-11e6-85c6-a0d6c5a11a34.png)

**Comment by caseyedavis12** [comment]
@afred: This looks great! Although the SRT files are not transcripts; they are closed caption files. If we say that they are transcripts, users may wonder why we are not making them available in full on the website.

________________________________

**Comment by afred** [comment]
Word. There is a bit of confusion in the code about terminology, but yes, I prefer “captions”.

**Comment by afred** [comment]
**done when**
  * search terms found in a record's captions are displayed, and highlighted, in the `catalog#index` view.
  * captions are not displayed for search results that did not match terms in the captions

**Comment by jasoncorum** [comment]
@afred, I've been starting to look at this ticket this morning. Ping me if there is anything you think I should know as I'm working on it.

**Comment by caseyedavis12** [comment]
I think that we lost this feature? These assets all have "arsenic old lace" in the caption file but the caption is not appearing in the search results: http://americanarchive.org/catalog?q=arsenic+old+lace&utf8=%E2%9C%93&f[access_types][]=online

**Comment by jasoncorum** [comment]
The feature wasn't lost but you did uncover a bug for which I just submitted a PR.

You can see the highlight currently working here: http://americanarchive.org/catalog?utf8=%E2%9C%93&f%5Baccess_types%5D%5B%5D=digitized&q=oregon+coast

What caused the issue you were seeing was some faulty logic that returned nil if the first term wasn't found. The new PR should fix that.
