### ISSUE TITLE
Pin down mechanics of on-site-only access

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#107]
@sroosa : This is a little ways away, but can we pin down how on-site-only access will work? My understanding is that users at WGBH and at LOC get special treatment: Can we base this on IP address? Can we get a list of the valid IP ranges?

(If we're claiming site-based access controls, I think this is really the way to go: username-password isn't hard, but it doesn't match the problem, as I understand it.)

**Comment by sroosa** [comment]
@mccalluc I am happy to have this based on IP address. @caseyedavis12 who do you think would be the best person to ask at the Library of their valid IP range?

**Comment by caseyedavis12** [comment]
I'd start with Lauren.

**Comment by sroosa** [comment]
Lauren forwarded me the following from Matt Derby at the Library of Congress. 
"I think that you could say to Sadie that we use the block of IPs from 140.147.0.1 to 140.147.255.255 (in other words, 140.147.0.0/16). However, I am cc’ing the ITS folks here as they likely either know a more specific range themselves or they know the right person to ask."

I'll follow up if their ITS people send more.

**Comment by mccalluc** [comment]
The player is up, access is restricted, and folks seem happy. Closing.
