### ISSUE TITLE
16:9 video playing in 4:3

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1075]
Video that I have encoded to be 16:9 aspect ratio is displaying for me as 4:3 in the new player. It plays in a 16:9 box in Sony Ci.

I'm in Chrome, and I also checked in Safari on the same machine.

See here for an example: http://americanarchive.org/catalog/cpb-aacip_508-4q7qn5zw1r

**Comment by afred** [comment]
Closing.. duplicate of #1072
