### ISSUE TITLE
Sometimes old HTML5 player still appears

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1077]
I cleared my cache this morning but sometimes the old HTML5 player still appears on record pages.

**Comment by afred** [comment]
@caseyedavis12 to fix this, we'll need to replicate the problem in a consistent way. Can you please supply a URL, and let us know which browser/versin you're seeing the old player on?

**Comment by caseyedavis12** [comment]
@afred: I believe that all video and audio appear in the html5 player for me when I click to an asset directly from the homepage rotating gallery. If I conduct a search and click to view an asset from the search results page, it looks the way it is supposed to look. This is an issue that is present in both Google Chrome and Firefox. (see #1076 for a related issue that occurs when I click to an asset from the homepage rotating gallery)

To replicate, go to the homepage and click on an asset in the rotating gallery: http://americanarchive.org/ 

This will show the video/audio in HTML5 player. If you first click on an audio file and then go back to the home page and click on a video file, it will decrease the size of the player.

Then, go to the homepage and click the search box. Go to search results and click on an item fro the search results. You will see that the player appears differently -- correctly -- from the search results page.

Audio from homepage rotating gallery:
![screen shot 2016-11-21 at 2 59 26 pm](https://cloud.githubusercontent.com/assets/5992135/20498664/08b497b2-affc-11e6-9c8b-8669c966a1c2.png)

Video from homepage rotating gallery:
![screen shot 2016-11-21 at 3 00 36 pm](https://cloud.githubusercontent.com/assets/5992135/20498676/13847978-affc-11e6-980d-2650d812176a.png)

Audio from search results:
<img width="709" alt="screen shot 2016-11-21 at 3 01 01 pm" src="https://cloud.githubusercontent.com/assets/5992135/20498687/1f08a224-affc-11e6-9f9a-f207768818c0.png">

Video from search results:
<img width="707" alt="screen shot 2016-11-21 at 3 01 20 pm" src="https://cloud.githubusercontent.com/assets/5992135/20498698/2610dce4-affc-11e6-8ae0-ab3353cdd42a.png">

Related issue #1076, where clicking on video from homepage gallery after clicking to audio from homepage gallery decreases size of player:
<img width="723" alt="screen shot 2016-11-21 at 3 00 43 pm" src="https://cloud.githubusercontent.com/assets/5992135/20498720/382b7740-affc-11e6-9823-7b5af28d33e0.png">

best,
Casey

**Comment by afred** [comment]
Yeah, so this is pretty weird. I can confirm that the browser's default `<video>` element shows up with clicking links from the homepage, but when I `⌘+R` to refresh, the Video-JS player shows up.

If this is a caching issue, then it's consistently caching it in the wrong way.

**done when** navigating to a `catalog#show` page from the homepage correctly displays the Video-JS player.

**Comment by jasoncorum** [comment]
@afred : Looks like this is an issue with the turbolinks gem. What I found was that the site wasn't reloading the header when clicking the link from the homepage. Since the video-js styles are added to the header from the catalog#_player partial the styles weren't getting applied.

Looks like potential fixes would be to remove the turbolinks gem or apply "data-no-turbolink='true'" to the link to catalog#show from catalog#_featured_carousel. I have a branch with the latter option that seems to fix the issue.

**Comment by afred** [comment]
@jasoncorum sweet, go ahead and make PR from your branch, notify my with a mention in the comments, and I'll check it out. Thanks!
