### ISSUE TITLE
Thumbnail edge cases

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#108]
Michael:
- Can you point me at the image that should be used as a thumbnail for audio?
- We may have records which we know are video, but which haven't been ingested: Should there be another special-case thumbnail for them?
- It's possible that records will be neither Moving Image nor Sound: Should there be another kind of thumbnail for them? Or maybe they don't get a thumbnail?

**Comment by caseyedavis12** [comment]
--Design has not provided the thumbnail for audio but I will ping them about that
--We will have a thumbnail for non-digitized assets, so everything will have a thumbnail (digitized video, digitized audio, non-digitized video and audio)
--I do not foresee having any content that is not Moving Image or Sound.

**Comment by Muraszko** [comment]
@mccalluc 
Yeah, Casey is right that all video should have a thumbnail.  Audio files don't have thumbnails, but you could do something like:
![openvault_audio](https://cloud.githubusercontent.com/assets/6650285/6228851/d8d56544-b67e-11e4-8355-83af3ed22161.jpg)

Or a little microphone icon.  I'd lean more towards no image or a small icon to be really clear visually if the record is audio, video, or a text only record.

**Comment by caseyedavis12** [comment]
You can use any image as a placeholder for audio and for non-digitized assets. The Design team will be delivering a standard thumbnail for audio and for non-digitized assets.

Best,
Casey

**Comment by mccalluc** [comment]
done long ago.
