### ISSUE TITLE
Add other NAEB organizations to "Participating Organizations" and map

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1091]
More content from the NAEB collection has been added to the ORR. We should add these organizations to the Map and Participating Organizations page.

**Comment by caseyedavis12** [comment]
Also add all new participating organizations to the map. 

NewsHour Productions
Jim and Donald Voegeli
Vision Maker Media

Adding the station to the map should be added to the workflow for creating Organization pages for all new Organizations

cc @sroosa @cmhosale @rfraimow

**Comment by sroosa** [comment]
@caseyedavis12 Since I usually add the new station pages, can someone show me how to add them to the map, and I can just do it all as one process?

**Comment by caseyedavis12** [comment]
@sroosa: I haven’t tested it but this appears to be the file that needs to be edited: https://github.com/WGBH/AAPB2/blob/fed2411e538de9b7059c3da60d2ecd78a0e80dbc/app/views/organizations/usa.svg

@afred can you confirm?

**Comment by afred** [comment]
@caseyedavis12 yes, that's how that works.

To add a new dot to the map, find the part of the raw SVG file that contains links like these...
```html
<a xlink:href='/participating-orgs#Alabama'><title>Tuscaloosa, AL: WUOA, University of Alabama</title><use x='643' y='400' xlink:href='#dot'/></a>
```
You should be able to basically copy and paste one of those links and just change values for `<title>` and the x,y coordinates in the `<use x=### y=### xlink:href="#dot"/>`.

**Comment by sroosa** [comment]
@caseyedavis12 : Which NAEB organizations do I need to add or how to I determine those?

**Comment by caseyedavis12** [comment]
@sroosa  can we close this ticket?

**Comment by sroosa** [comment]
@caseyedavis12 I still have to add the ones that have multiple orgs in one state.

**Comment by afred** [comment]
@sroosa ping? Also.. if it makes sense to add an effort estimation here, it's on our list. So feel free. thanks!

**Comment by sroosa** [comment]
@afred this actually should have been closed when you fixed that .yml file for me!
