### ISSUE TITLE
Pop Up Archive Transcript display

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1096]
The transcript viewer window that is being designed by Digital for the Pop Up Archive project, and further implemented by MLA developer will need to be able to display transcripts formatted according to the Pop UP Archive time-stamped json. Related to #1095 and #1097

**waiting on:**
  - [x] design of "transcript viewer window". Specifically what features are we expecting in the transcript viewer window? (see below)

**Done when:**
  - [x] transcript viewer window displays on the page with HTML transcript (converted from JSON)
  - [x] There is an option to hide the transcript viewer window.

**Comment by caseyedavis12** [comment]
I closed #973 but am copying Chuck's comment in that issue into this issue:

"My thinking right now is that the SRT should be parsed on the fly and HTML generated from it. A different approach would be a bulk process to transform the SRT to some XML format, put that on S3, and then use XSL to translate that to both SRT/WebVTT and HTML

SRT parsing is needed regardless, though the way it ultimately gets used could be different."

**Comment by afred** [comment]
@caseyedavis12 the amount of effort is going to hinge on what kind of features the transcript viewer window is going to have. Specifically, any of these?...
  * sync buttons (similar to OV?)
  * auto scrolling (similar to OV?)
  * paragraph highligting?
  * localized search box (for searching just the transcript -- as opposed to the OV solution of giving them the Ctrl+F hint).

**Comment by caseyedavis12** [comment]
I have attached the comps for the transcript display window and updated record page layout. I believe the design comps answer @afred's questions except for auto-scrolling, which we do want along with the sync buttons, paragraph highlighting and localized search box.

The new design also features a larger player. Below are the sizes:

For the default player in the left column (when transcript is shown):
4:3 aspect ratio: 562 x 422 px
16:9 aspect ratio: 562 x 316 px
 
For the player centered on screen (when transcript is hidden):
4:3 aspect ratio: 680 x 510 px
16:9 aspect ratio: 680 x 383 px

[AAPB transcript display comps.zip](https://github.com/WGBH/AAPB2/files/838958/AAPB.transcript.display.comps.zip)

**Comment by afred** [comment]
@caseyedavis12 @jasoncorum There's an edge case here to consider, and one that we ran into with OV as well.

The transcript automatically advances as the media does. But the user can scroll forward and backward within the transcript (e.g. when searching for a word or phrase) without moving the media playback position. At this point the transcript becomes un-sync'd from the media.

Now, if we don't handle this case with some special logic, then the transcript will continue to auto-scroll along with the video's playback, which would be confusing to the user, because they'd be fighting for control of the transcript. So I would recommend doing something different.

Proposal:
  1. Highlight the "active" part of the transcript, as planned.
  1. Provide a "sync" button at the top of the transcript that has two states, "on" and "off" that match whether or not the transcript is currently auto-scrolling or not. (Note we briefly had a version of the OV transcript viewer that did this).
  1. Start with auto-scrolling turned "on".
  1. When the user moves transcript independently of the media playback (e.g. by scrolling or by searching), then the auto-scroll switches "off".
  1. Auto-scrolling remains "off" until the user re-enables it with the "sync" button.

Thoughts?

**Comment by afred** [comment]
@caseyedavis12 Also.. i'm wondering about the usefulness of a "Hide" button. My feeling is that if a user wants to make the video bigger, and watch it without the distraction of the transcript scrolling by, then they would just hit the "full screen" button. Especially on mobile. Thoughts?

**Comment by jasoncorum** [comment]
@sroosa @afred - Now that I'm digging in to this I'm seeing an issue with the comps and the data we currently have from PUA. Presuming that what we get back from Fix It is the same as what we have from PUA, we won't have the actual speaker names. Speakers are assigned an ID but no name is attached to the ID.  What I would propose doing for the comp below is to combine successive segments with the same user ID into chunks of text (like in the comp) and just drop the speaker names. How does that sound? I can walk through this more in-depth if you need more info. 

![aapb_transcript_open](https://cloud.githubusercontent.com/assets/3814190/25591830/379c82d6-2e84-11e7-9d7d-ba8ce509673c.png)

**Comment by sroosa** [comment]
@jasoncorum Can we talk about this with an example from PUA? I'm not super confident in the speaker IDs they are generating, so I might want to figure out a way around that...

**Comment by sroosa** [comment]
@jasoncorum we just talked about this, and chunking it based on speaker IDs, but not displaying any of the speaker ID information is a good way to proceed for now. When we have corrected transcripts to test with, then we can decide if we want to change the way we do that.

**Comment by jasoncorum** [comment]
@sroosa @caseyedavis12 - As I'm finishing up the ticket and doing some manual testing, I noticed that we're going to have some titles that go to two lines which makes the title look not so great in the new location. I think I'd handle it by reducing the font-size a little bit (reduce the number of times we go to 2 lines) and try to make the space between lines tighter for when we do. Does that approach sound good?

![screen shot 2017-05-09 at 9 06 37 am](https://cloud.githubusercontent.com/assets/3814190/25852311/ebdcfb78-3496-11e7-8981-a3c3cddb9299.png)

**Comment by sroosa** [comment]
@jasoncorum, That sounds good to me. @caseyedavis12, what do you think?

**Comment by caseyedavis12** [comment]
@jasoncorum sounds good to me too!

**Comment by sroosa** [comment]
@jasoncorum I played around with it, and I think it looks great! @caseyedavis12 agrees. 
The syncing seems to work both before and after search. The show/hide function works. I can't see anything that we need to do before this is ready for code review.

**Comment by sroosa** [comment]
Just for the sake of documentation - we decided to hold on merging this code until the NewsHour transcripts are ready as well (#1097), so that it's not on production until there are transcripts for at least some of the assets.
