### ISSUE TITLE
Non-synched NewsHour transcript indexing and display

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1097]
**waiting on:**
  - [x] design for "Transcript Display Window" (may come from design comps delivered by other tickets).

**Done when**
- [x] Plain text transcripts appear within the Transcript Display Window 
- [x] Plain text transcripts retain the newlines when displayed
- [ ] ~Plain text transcripts are indexed for searching~ covered by #1166 
- [x] Plain text transcripts do not appear within the player.

**Comment by afred** [comment]
@caseyedavis12 should this be labeled "Data/Media"? Sounds like a programmer task.

**Comment by jasoncorum** [comment]
Notes for self:

1. We'll use the straight text for the transcript window, no additional processing for speakers.
2. Transcript files will be named and stored on S3 the same way as the PUA transcripts.
3. Due to one, we will need some additional logic on which view and which transcript to use. Thinking is first try .json, then .txt, then "no transcript)

**Comment by jasoncorum** [comment]
@sroosa - How's this look? If good, I'll get tests done tomorrow!

![screen shot 2017-06-05 at 3 58 50 pm](https://cloud.githubusercontent.com/assets/3814190/26800672/2d7d1730-4a08-11e7-9abb-9ade25ed0263.png)

**Comment by sroosa** [comment]
@jasoncorum: !?! That was so fast! I think this looks good. Exactly what we want!

**Comment by jasoncorum** [comment]
Additional notes: 

* This work is being done in the #1096 branch and will be in the same PR.
* Will require updates to #1200 branch which is based on #1096.

**Comment by jasoncorum** [comment]
@sroosa - In doing this work I noticed that, at least, on this Newshour record (http://americanarchive.org/catalog/cpb-aacip_507-0000000j8w.pbcore) the transcript status is stored as annotationType='Transcripts Status' and not annotationType='Transcript Status' per this ticket: https://github.com/WGBH/AAPB2/issues/1188.

**Comment by sroosa** [comment]
@jasoncorum thanks for catching that! i must have mistyped at one point while we were building the workflow. I've asked Kevin to correct all of them in the AMS, and we're correcting the workflows so we don't introduce any new discrepancies down the line.
