### ISSUE TITLE
Index Pop Up Archive transcripts

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1098]
We need to pull down the unfixed Pop Up Archive transcripts, put them on S3 and index them on the public website. 

We need a plan for replacing and reindexing fixed Pop Up Archive transcripts after we launch the game in March 2017.

**waiting on:**
- [x] Confirm that we've downloaded all the transcripts from PUA
- [x] Store the records on S3 in new transcripts folder, mirroring existing captions folder structure
- [x] Work with Sadie on tracking transcripts in AMS

**Done When**
- [ ] Use transcripts in site searches. Do not display yet. Will be after they're corrected.

**Comment by caseyedavis12** [comment]
Here are scripts developed by @mccalluc to pull down transcripts from Pop Up Archive: https://github.com/WGBH/AAPB-etc/tree/master/scripts

**Comment by jasoncorum** [comment]
** Done When **
1. Confirm that we've downloaded all the transcripts from PUA
2. Store the records on S3
3. Work with Sadie on tracking transcripts in AMS
4. Use transcripts in site searches. Do not display yet. Will be after they're corrected.

**Comment by jasoncorum** [comment]
Update on this. Almost all the transcripts and entities are up on S3, but there was an outlier in the PUA naming convention that caused my scripts to miss some items. Currently working on fixing this.

**Comment by jasoncorum** [comment]
All transcripts should be up on S3, now.

**Comment by jasoncorum** [comment]
@sroosa - I think you mentioned last week that you were close to having these tracked in the AMS. Do you have an example of how this will look in the PBCore?

**Comment by jasoncorum** [comment]
Note to self. Sadie sent an example via email.
