### ISSUE TITLE
Confirm map <iframe> appears on first amendment exhibit

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1111]
@jasoncorum: we just added the iframe code to the ```/exhibits/first-amendment``` .md file. Can you open this page in the first-amendment-fixes branch and let us know if it displays on the website? 

Here is the iframe code:

```<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1ePTiUOPnzGHpc-H4TFbW6In2X-k" width="640" height="480"></iframe>```

cc @janowiecmichelle

**Comment by jasoncorum** [comment]
The map displays! Screenshot attached. 

However, I'm still seeing the weird issues we saw earlier and CMLess also doesn't like some tweaks made to the TOC on the 60s and 70s page. We'll have to take a look at that later.  

<img width="1212" alt="screen shot 2016-12-01 at 1 27 39 pm" src="https://cloud.githubusercontent.com/assets/3814190/20806816/62a0e142-b7ca-11e6-8f22-73ab464da180.png">
