### ISSUE TITLE
UX Rec: Remove Search Bar in Header on Homepage

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1117]
On the homepage, we suggest that search bar in the header be removed since there is already a prominent search bar in the top portion of the homepage. The users eye is drawn to the large search box and the one in the header becomes redundant. 

**Done when**
- [ ] Search box in header does not appear on Homepage or Advanced Search page.

**Comment by caseyedavis12** [comment]
Related to #1187

**Comment by sroosa** [comment]
already closed in another ticket.
