### ISSUE TITLE
UX Rec: Remove search bar from left side of pages

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1126]
We suggest removing the search bar from the left side of any pages.

"This was to avoid the redundancy of having the search bar at the top of the page, in the header. Keeping only one search box on the page keeps the user from getting confused. A user might find themselves asking, “Does this search bar link to a different set of resources?” It is better to keep things simple."

**Done When**
- [x] Search box does not appear on the left side of Asset Records.
- [x] Search box does not appear on the left side of static pages.
- [x] Search box does not appear on the left side on search results pages.

**Comment by caseyedavis12** [comment]
Only keep the search box that is in the header.

**Comment by caseyedavis12** [comment]
@sroosa can this be moved up?

**Comment by jasoncorum** [comment]
@sroosa & @caseyedavis12 - in removing the search bar from the sidebar, the issue @caseyedavis12 mentioned in #1222 about the page label was more pronounced. see this screenshot:

![screen shot 2017-07-31 at 10 22 25 am](https://user-images.githubusercontent.com/3814190/28782123-3f6cbfe2-75da-11e7-9b5c-026e662d952e.png)

We have the title replicated right beneath itself. Based on the feedback on #1222, I set this up as a potential solution on this ticket. Take a look below and let me know your thoughts.

![screen shot 2017-07-31 at 10 18 46 am](https://user-images.githubusercontent.com/3814190/28782269-ae736620-75da-11e7-8456-3a1b8d85bfab.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: looks good to me
________________________________

**Comment by sroosa** [comment]
+1
