### ISSUE TITLE
UX Rec: Access facet should be more prominent

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1132]
The students suggested that the Access facets should be more prominent on the search results page.

**Done when**
- [x] Design has been delivered and approved
- [x] Design is implemented

**Comment by caseyedavis12** [comment]
Mock-up look of access facets placed in "Search" purple banner.

**Comment by afred** [comment]
@caseyedavis12 confirm that we need to receive some mocks from design?

**Comment by caseyedavis12** [comment]
@afred: getting mocks of design will cost $$. Do you feel comfortable proposing something with the current design framework? If not, this becomes low priority as we don't have funding for Digital's work on this right now.

**Comment by jasoncorum** [comment]
@caseyedavis12 @afred - How does this look? This isn't functionally coded at all, so disregard the "Access" section still displaying beneath the other facets.

![screen shot 2017-03-16 at 11 17 46 am](https://cloud.githubusercontent.com/assets/3814190/24003618/4f815958-0a3a-11e7-9f99-6207ab60021e.png)

**Comment by jasoncorum** [comment]
Note for implementation: the render_facet_partials methods accepts an array of field_names. Using that we can specify which facets to display where.

**Comment by jasoncorum** [comment]
Updated screenshot with full functionality.

![screen shot 2017-04-14 at 10 21 54 am](https://cloud.githubusercontent.com/assets/3814190/25045858/4a1711dc-20fc-11e7-9e05-c0bd74dc1865.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: this has all the functionality we need but I am wondering if we could hold on this and get Design input with the new potential grant we're getting. I'm sorry to keep this blocked!

**Comment by jasoncorum** [comment]
@caseyedavis12 That's cool with me!

**Comment by sroosa** [comment]
Updated design on this from Creative.
![screen shot 2018-01-26 at 8 09 42 am](https://user-images.githubusercontent.com/4029248/35441127-47eb70fa-0270-11e8-9a8d-ddbe9caf8bf1.png)
