### ISSUE TITLE
UX Rec: No shortcuts on site

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1133]
Users cannot save searches or records for future use. Could we install a Zotero plugin so that researchers can save their searches? https://www.zotero.org/download/

**Comment by Muraszko-wgbh** [comment]
During the meeting yesterday I downloaded and used Zotero to save searches and local copies of a record page so I don't think you need to implement anything on the site itself and can probably close this ticket.  All functionality is handled by the Zotero app and browser plugin and it seemed to work fine with the site as is.
