### ISSUE TITLE
Make ORR Rules of Use a window instead of full page

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1134]
From Google Analytics, one can tell that some users stop at the ORR Rules of Use and do not accept to view the media. This may be because the page is confusing to users who do not know what to do on this page. 

We think that more people would click through the ORR Rules of Use if it appears as an pop up window hovering over the record page (slightly dimmed in the background) for the item that the user clicked to view. The Rules of Use would appear with a scroll bar and Accept Rules of Use would appear on the outside of the Scroll Bar. 

**Done when**
- [ ] ORR Rules of Use is presented to users as a hover window with the ORR rules of use scrollable within the window instead of full page.

Here is an example:

![popupwindow](https://cloud.githubusercontent.com/assets/5992135/21547090/d8a16d6a-cdb1-11e6-8a75-a6333d1f8408.png)

**Comment by caseyedavis12** [comment]
Actually, this is a design feature we have already implemented on Open Vault:

<img width="1433" alt="screen shot 2016-12-30 at 10 43 12 am" src="https://cloud.githubusercontent.com/assets/5992135/21567776/d083d0f2-ce7c-11e6-86cf-a9c287229b18.png">

**Comment by caseyedavis12** [comment]
Casey will supply the language.

**Comment by caseyedavis12** [comment]
Priority

**Comment by caseyedavis12** [comment]
Language for the updated ORR Rules of Use hover window:

Welcome to the American Archive of Public Broadcasting Online Reading Room (ORR). To access media in the ORR, please review and agree to the ORR Rules of Use. [this should not appear within the scroll window]

[ORR Rules of Use within a scrollable area of the window]

Button: "I agree to the ORR Rules of Use."

**Comment by jasoncorum** [comment]
@caseyedavis12 - Does this look good? Feel free to stop by if you want to see it in person.

![screen shot 2017-03-07 at 3 09 15 pm](https://cloud.githubusercontent.com/assets/3814190/23675658/06c603ce-0348-11e7-8159-54ee7a4abdae.png)

**Comment by caseyedavis12** [comment]
Approved by all parties! We're good to go @jasoncorum.
