### ISSUE TITLE
Allow Multiple NAEB stations to appear per state

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1136]
Currently, we use the states.yml file to add blurbs about NAEB stations in specific states on the Contributing Organizations page. The way it is currently set up, we can only add one NAEB station per state. Now that we are adding more and more NAEB content, there are some states with multiple NAEB stations. Can we modify the process to allow for multiple NAEB stations to be added per state?

Current stations that will need to be added once this functionality is in place are:
San Bernardino Valley College
KEBS San Diego University
Moody Bible Institution/WMBI
KWSC and WDET (Wayne State University)
WMUK Western Michigan University/College
Union Theological Seminary
WBFO, SUNY Buffalo
WGUC University of Cincinnati

**Comment by afred** [comment]
This actually doesn't require any changes to ruby code, just the `states.yml` file, although the way it's set up now is not very intuitive.

@sroosa What do you want the end result to look like for states with > 1 NAEB station?

**Comment by sroosa** [comment]
@afred: I'd like it to show up with just the one blurb, but instead of just one station's name being inserted with a link to the search results, multiple stations names would should up listed in the first sentence, each linking to the specific search results for that station.

**Comment by afred** [comment]
Right on. You can do that just by editing the `blurb_md` in `states.yml` for a given state. You can actually put whatever you want in there. Most states right now are re-using the `naeb_blurb` defined for Kansas, but they don't have to.

So, for states that have multiple NAEB stations, I would say just hardcode the `naeb_blurb` for those states. It's not the prettiest, but probably the simplest.
