### ISSUE TITLE
batch upload - scripts/ci/ci.rb JSON parse error

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1150]
I can't get the batch upload script (scripts/ci/ci.rb) to work. I get this error: 

**/Users/charles_hosale/.rvm/gems/ruby-2.3.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse': 743: unexpected token at '' (JSON::ParserError)
	from /Users/charles_hosale/.rvm/gems/ruby-2.3.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from scripts/ci/ci.rb:198:in `singlepart_upload'
	from scripts/ci/ci.rb:174:in `upload'
	from scripts/ci/ci.rb:50:in `upload'
	from scripts/ci/ci.rb:253:in `block in <main>'
	from scripts/ci/ci.rb:253:in `each'
	from scripts/ci/ci.rb:253:in `<main>'
/Users/charles_hosale/.rvm/gems/ruby-2.3.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse': 743: unexpected token at '' (JSON::ParserError)
	from /Users/charles_hosale/.rvm/gems/ruby-2.3.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
	from scripts/ci/ci.rb:198:in `singlepart_upload'
	from scripts/ci/ci.rb:174:in `upload'
	from scripts/ci/ci.rb:50:in `upload'
	from scripts/ci/ci.rb:253:in `block in <main>'
	from scripts/ci/ci.rb:253:in `each'
	from scripts/ci/ci.rb:253:in `<main>'**

I tried updating ruby and my gems, also tried getting the most recent AAPB2.

The command I am running is: echo /Users/charles_hosale/Desktop/AM_anamorphic_fixed/fixed/* | xargs -n 10 ruby scripts/ci/ci.rb --log /Users/charles_hosale/ci_log.tab --up &

This is attempting to run on a set of 304 mp4s that are nested in subdirectories.

**Comment by jasoncorum** [comment]
We cleaned up RVM and tweaked command/
