### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1152]
I'm still getting 500 errors when I conduct some searches. I just searched for 13th amendment and received a 500 error. This is high priority.

**Comment by jasoncorum** [comment]
looks like an issue with the CaptionConverter srt_to_html method which the new caption code uses. and the as_timestamp method

saw this url responding 500 in the logs: http://americanarchive.org/catalog?f%5Baccess_types%5D%5B%5D=online&page=15&q=AIDS&sort=year+asc
