### ISSUE TITLE
Add newlines to NewsHour transcripts

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1161]
One option to consider: delete all returns and replacing all period with period space space hard return.

Some exceptions include words such as Mr., question marks, commas, etc.

Has someone already written a script that can parse a text transcript?

**Comment by cmhosale** [comment]
I'm waiting to hear back from the vendor, they might be sending us transcripts with fixed whitespace. I'll update when I get a definitive answer from them.

**Comment by caseyedavis12** [comment]
@cmhosale: I heard that we got updated transcripts with a character to signify where a return should go. Can this be closed?

**Comment by afred** [comment]
@cmhosale or @foo4thought can you please give @caseyedavis12 an effort estimation? thanks

**Comment by caseyedavis12** [comment]
@cmhosale is this done?

**Comment by cmhosale** [comment]
@caseyedavis12 @afred @foo4thought this is closed, we got better transcripts from the partner
