### ISSUE TITLE
Map NewsHour transcript header and footer metadata to PBCore data model

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1162]
@sroosa is creating a spreadsheet mapping of the NewsHour transcript header and footer metadata to the fields in which we want the data populated in the AMS.

Done when:

- [ ] @sroosa gives @foo4thought a spreadsheet mapping subject headings from transcript to AAPB genres. 

- [ ] @sroosa gives @foo4thought a mapping of other metadata in transcripts to AMS fields.

- [ ] @foo4thought  agrees these documents can be used to write a script needed in #1163

**Comment by afred** [comment]
@sroosa can you provide an effort estimation here? thanks

**Comment by sroosa** [comment]
Resolved outside of the website code.
