### ISSUE TITLE
Write script to insert NewsHour transcript header and footer metadata to AMS records

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1163]
Will follow #1162

**waiting on:**
- [x] @sroosa provides a mapping to Kevin
- [x] Transcript names are matched to GUIDs. 
- [x] @foo4thought develops process to generate SQL insert statements for each GUID ready to be processed 

**Done when**
- [x] A sampling of records are reindexed for display on the public website
- [x] A plan is in place to process records on a regular schedule until all of them are processed

**Comment by sroosa** [comment]
After @sroosa provides a mapping, @foo4thought will be able to create a csv/spreadsheet with name of each transcript and pieces of data pulled from each transcript. Then we can match transcript names to GUIDs. From this @foo4thought will be able to write insert statements to add each piece of data pulled from the transcript into the GUID's AMS record.

**Comment by sroosa** [comment]
closed with work outside of github
