### ISSUE TITLE
Rename NewsHour transcript file names to AAPB transcript file-naming convention

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1164]
Use the Intern Review Worksheet, rename the original file name to the agreed upon AAPB transcript file-naming convention.

**Done when**

- [x] a process is established for renaming the transcripts using the AAPB convention
- [x] the process is tested

**Comment by sroosa** [comment]
@cmhosale: files to be names [GUID with hyphen]-transcript.txt

**Comment by sroosa** [comment]
closed with work outside of gihub
