### ISSUE TITLE
Index and evaluate sampling of NewsHour transcripts on AAPB website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1166]
#1165 is a pre-req for this issue.

**Done when**
- [x] A sampling of NewsHour transcripts are indexed on public website.
- [ ] Indexing transcripts does not affect acceptable relevancy of search results (i.e. does not make them too noisy).

**Comment by afred** [comment]
@caseyedavis12 Question:
  - [ ] should this ticket involve any QA to assure that search results aren't getting thrown off by additional searchable data

**Comment by caseyedavis12** [comment]
@afred: Adding QA to the done when statement would be good.

**Comment by sroosa** [comment]
We'll test this when we release the transcript features to demo. We should have staff and interns work on demo for the day and see if it affects their results.

**Comment by sroosa** [comment]
Closing this ticket after extensive test searches show that NewsHour assets with transcripts are not cluttering searching. Opening ticket #1297 to test this again when there are even more NewsHour assets in the ORR.
