### ISSUE TITLE
If Proxy is 16x9, it should display in 16x9 player

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1169]
If a proxy is 16x9, it should display in a 16x9 player and not a 4x3 player with letterboxing. Is this possible?

**Comment by caseyedavis12** [comment]
Can we make the website draw a 16x9 player if this metadata field appears anywhere in the PBCore:

<essenceTrackFrameSize>720 x 486</essenceTrackFrameSize>

**Comment by caseyedavis12** [comment]
@jasoncorum: any work on this issue can be charged to Overhead 156840

**Comment by cmhosale** [comment]
http://americanarchive.org/catalog/cpb-aacip_504-222r49gp2h here is a 16x9 video. The player draws a hard coded 4:3 box and then letter boxes the video. It would be nice if the player responded to the video being 16x9 by drawing a bigger 16x9 player without letterboxes.

**Comment by caseyedavis12** [comment]
duplicate of #1072
