### ISSUE TITLE
Add FixIt logo and tagline to AAPB header

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1176]
Add FixIt logo and tagline to AAPB header

**waiting on:**
   - [x] design comps specifically for the header (if not included in comps for  #1187)
   - [x] #1187 

**Done when**
- [x] FixIt logo and tagline added to header, and looks like the comps.
- [ ] ~We have redeployed the site with the new header~

**Comment by afred** [comment]
@sroosa @jasoncorum was there code committed that closes this?

**Comment by sroosa** [comment]
@afred yes as part of #1187
