### ISSUE TITLE
Reorganize AAPB header info

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1187]
**Done when**

- [x] Remove Contact from Header
- [x] Remove "organizations" link from header
- [x] Remove "About" link from header"
- [x] Remove "Advanced Search" from header

- [x] Change "Research" tab to "About"

Include the following pages in the About menu:
- [x] About the AAPB
- [x] Vision and Mission
- [x] History
- [x] Participating Organizations
- [x] On Location Research
- [x] Searching the Website
- [x] Exhibits
- [x] Projects
- [x] Funding
- [x] Executive Advisory Council
- [x] Acknowledgments
- [x] FAQ
- [x] Contact Us

- [x] Add "a collaboration between WGBH and the Library of Congress" below the logo on the AAPB website header.

**Comment by jasoncorum** [comment]
@caseyedavis12 - How does this look?

![screen shot 2017-03-08 at 3 02 25 pm](https://cloud.githubusercontent.com/assets/3814190/23721576/506b5722-0410-11e7-8f8a-fde95695e8cb.png)
![screen shot 2017-03-08 at 3 02 53 pm](https://cloud.githubusercontent.com/assets/3814190/23721577/52080d8c-0410-11e7-98d5-7554f4b7a8be.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: Looks great, but could you put the Library of Congress first in the collaboration statement? "a collaboration between the Library of Congress and WGBH"


Can you then send me updated screenshots?


thank you!

**Comment by jasoncorum** [comment]
@caseyedavis12 - Here you go!

<img width="1277" alt="screen shot 2017-03-09 at 4 11 07 pm" src="https://cloud.githubusercontent.com/assets/3814190/23770920/0f76ff22-04e3-11e7-9df5-79e3ea4235cf.png">

<img width="1280" alt="screen shot 2017-03-09 at 4 11 28 pm" src="https://cloud.githubusercontent.com/assets/3814190/23770925/12ee1302-04e3-11e7-98a5-b814a0b4f87a.png">

**Comment by jasoncorum** [comment]
@caseyedavis12 - Are we good to move ahead with this? Thanks!

**Comment by caseyedavis12** [comment]
@jasoncorum: I'm waiting on approval from the LOC. Will let you know when we get approval!


:-)

**Comment by caseyedavis12** [comment]
@jasoncorum: I am waiting on LOC approval of this change. 

One thing that needs to be changed is that the Search box in the header should not appear on the homepage but should appear on every other page.

In addition, Digital has provided a design of the updated header (that includes all these changes you have made) to add the FIX IT logo in the top right corner of the header. I am also waiting on LOC approval of this but have attached an image below. The image below should only be referenced for the FIX IT logo which I can send to you.

![aapb_home](https://cloud.githubusercontent.com/assets/5992135/24970429/3f736c38-1f82-11e7-812e-62ecd3322418.jpg)

**Comment by jasoncorum** [comment]
@caseyedavis12 - Random thought for Google Analytics. It would probably be a good idea to use some Google Analytics tracking code for the Fix It promo in the header. Thoughts? https://ga-dev-tools.appspot.com/campaign-url-builder/

**Comment by caseyedavis12** [comment]
@sroosa: We are no longer blocked on this ticket. As a reminder:

-tag line below AAPB logo should say "a collaboration between the Library of Congress and WGBH" (LOC first)
-Search box in header should not appear on homepage but on all other pages
-I just sent the logo via email

cc @jasoncorum

**Comment by caseyedavis12** [comment]
@sroosa @jasoncorum : one more link that needs to be added under the About tab is Funding (http://americanarchive.org/about-the-american-archive/funding)

**Comment by jasoncorum** [comment]
@caseyedavis12 @sroosa - Dropped it in. If these looks good, I'll submit the PR.

![screen shot 2017-04-13 at 3 22 57 pm](https://cloud.githubusercontent.com/assets/3814190/25020699/65d38bc0-205d-11e7-876a-d9cee27ad9a8.png)

![screen shot 2017-04-13 at 3 23 21 pm](https://cloud.githubusercontent.com/assets/3814190/25020700/67e99d8c-205d-11e7-8702-b6e1954acf2e.png)

**Comment by jasoncorum** [comment]
@caseyedavis12 @sroosa - Also where should "Funding" go in the dropdown list?

![screen shot 2017-04-13 at 3 42 11 pm](https://cloud.githubusercontent.com/assets/3814190/25021380/fa2a94ec-205f-11e7-970b-f8d7109c228e.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: Funding should go below projects. Everything else looks good!

**Comment by caseyedavis12** [comment]
@jasoncorum here you go! http://fixit.americanarchive.org/?utm_source=aapb_fixit_header&utm_medium=website&utm_campaign=fixit_from_website

**Comment by jasoncorum** [comment]
Opened #1238 and assigned to @afred for review.
