### ISSUE TITLE
More padding around images in static pages

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1190]
**Done when**
- [ ] There is more padding around static images on the website.

http://americanarchive.org/exhibits/first-amendment/protests-80s-andbeyond

**Comment by afred** [comment]
@caseyedavis12 How does this look?

![image](https://cloud.githubusercontent.com/assets/1507490/25055504/773d4f72-2120-11e7-8f90-64133f12a3d1.png)

**Comment by caseyedavis12** [comment]
I think it needs a little more padding

Casey E. Davis Kaufman
Senior Project Manager, WGBH Media Library & Archives
Project Manager, American Archive of Public Broadcasting
WGBH | One Guest Street, Boston, MA 02135
casey_davis-kaufman@wgbh.org | 617-300-5921

________________________________

**Comment by afred** [comment]
@caseyedavis12 The only way to change padding for these images _without_ changing the padding for all other images in the markdown, is to add a custom CSS class to the images. And to do that, you'd have to change the syntax from Markdown to HTML.

E.g. instead of...
```markdown
![CPB Logo Image](https://s3.amazonaws.com/americanarchive.org/org-logos/cpb_logo.png)
```
.. you would do this instead...
```html
<img class="funder-logo" src="https://s3.amazonaws.com/americanarchive.org/org-logos/cpb_logo.png" alt="CPB Logo Image">
```

Your call.

**Comment by caseyedavis12** [comment]
@afred let's just stick with what we have for now and if we want to add more padding later on I know how to do that in the markdown. This is good enough for deployment.
