### ISSUE TITLE
High Priority: Old audio player appearing on some records with link to download the file!

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1191]
Old audio player appearing on some records, including a link to download the file!!!

<img width="795" alt="screen shot 2017-02-17 at 2 19 57 pm" src="https://cloud.githubusercontent.com/assets/5992135/23079768/58ef1e22-f51c-11e6-8400-1e5fac1a41c7.png">

**Comment by caseyedavis12** [comment]
Some videos are affected, too:

Example: http://americanarchive.org/catalog/cpb-aacip_328-77sn09w0
<img width="828" alt="screen shot 2017-02-17 at 2 22 44 pm" src="https://cloud.githubusercontent.com/assets/5992135/23079858/a70e76e8-f51c-11e6-9ce4-9d8bfed96b74.png">

**Comment by Muraszko-wgbh** [comment]
What browser are you using, I'm trying it on Chrome and Safari and both show the old player.

**Comment by caseyedavis12** [comment]
**Done when** VideoJS is the only player that appears on the website, and there is no download link.

@muraszko In test, I was using Google Chrome.

**Comment by Muraszko-wgbh** [comment]
Can you clear your browser and try again?

**Comment by caseyedavis12** [comment]
Whew! I cleared my browser cache and all seems to be working fine. VideoJS is the only player showing up now. Closing.
