### ISSUE TITLE
Set up basic monitoring

### ISSUE THREAD

**Issue by Muraszko-wgbh** [WGBH/AAPB2#1211]
Similar to PBCore instance

**Comment by jasoncorum** [comment]
For reference: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring_ec2.html

**Comment by jasoncorum** [comment]
@afred - you cool with me setting up the same monitoring that we have set up for PBCore on the other instances? 

The rule we have for PBCore is to notify us if any of their basic status check fails twice within 15 minutes. I think this would be a good start across the board.

(FYI - I added my email my email address to the PBCore status check).

**Comment by jasoncorum** [comment]
@afred - FYI, I think you should get some emails confirming that you'd like to receive notifications for these alarms.

**Comment by afred** [comment]
@jasoncorum yep, got em
