### ISSUE TITLE
Homepage missing latest blog post and links to social

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1219]
On the homepage, next to "A collaboration with a long-term vision," the latest blog post title and first characters of the post should appear with links to social media. 

Now, that half of the page is blank.

**Comment by jasoncorum** [comment]
@caseyedavis12 - I think what happened here is that the site didn't receive a response from the Wordpress blog. It looks like it checks every hour or so. Since the blog is up now, the content is back after the cache page fragment was cleared.
