### ISSUE TITLE
AAPB site is down!!!

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1224]
AAPB website is down. I receive a 503 error.

http://americanarchive.org/

**Comment by afred** [comment]
It looks like @foo4thought fixed it. Confirm?

**Comment by caseyedavis12** [comment]
We're back up and running.

**Comment by afred** [comment]
whew! When I get notified of these updates, the first thing I see is the title of the ticket... "AAPB Website is Down!" -- makes my heart jump
