### ISSUE TITLE
Install an AAPB wiki using MediaWiki

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1228]
**Done when**

- [x] A wiki using the MediaWiki open-source tool exists at wiki.americanarchive.org

Install guide available at:
https://m.mediawiki.org/wiki/MediaWiki

**Comment by sroosa** [comment]
Hopefully up by April 21

**Comment by jasoncorum** [comment]
@afred - I did a quick local install of this earlier in the week to get a feel for the process. Should we schedule a time to discuss how best to set this up? I'm thinking this should be a separate ec-2 instace with an elastic ip - similar to pbcore site.

**Comment by sroosa** [comment]
closed outside of this repo
