### ISSUE TITLE
Still getting 500 errors

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1229]
I just conducted a search for "arsenic old lace" on the AAPB website and got a 500 error

http://americanarchive.org/catalog?utf8=%E2%9C%93&f%5Baccess_types%5D%5B%5D=online&q=arsenic+old+lace

**Comment by jasoncorum** [comment]
@caseyedavis12 @afred - This should be fixed now. It looks like Kevin and Drew swapped servers last week for the apache log issues and the demo server didn't have the update we pushed to resolve the issue above. 

I ported the apache log fix that to the other server and re-swapped servers.

**Comment by caseyedavis12** [comment]
Confirming that I no longer get the 500 error.
