### ISSUE TITLE
Reorder homepage sections

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1240]
The colors of each section should remain in the same order. The content should be re-orders as:

-Header
-Rotating items with About the AAPB and From the Blog boxes
-Curated Exhibits
-FIX IT
-Browse the Collection
-Participating Organizations
-Every Picture Video
-Footer

Done when
- [x] colors of homepage sections appear in same order
- [x] content of homepage sections appear in new order

**Comment by jasoncorum** [comment]
Notes for Self:

Original Lineup
Welcome : rgba(255,255,255,.25)
Stations : rgba(239,63,55,.85)
Exhibits : rgba(44,42,115,.85)
Browse : rgba(144,41,142,.85)
Video : rgba(158,32,100,.85)

New Lineup
Welcome : rgba(255,255,255,.25)
Exhibits : rgba(239,63,55,.85)
Fix It
Browse : rgba(44,42,115,.85)
Stations : rgba(144,41,142,.85)
Video : rgba(158,32,100,.85)
