### ISSUE TITLE
Error on ingest

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#1246]
**Background:** Getting the following error when trying to run an ingest: `Method validation errors: '#img_height' failed: uninitialized constant PBCore::FastImage`

Most likely just a missing `require "fastimage"` at the top of `app/models/pb_core.rb`.

**Done when:** running an ingest doesn't raise that error anymore.

**Comment by jasoncorum** [comment]
ugh, sorry about this @afred. thanks for taking care of it!
