### ISSUE TITLE
Media not playing for off-site users

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#1249]
**Description:** Cannot play media when viewing from off site.

**Replicate:** Go to the following URLs using a computer that is _not_ onsite at WGBH, LOC, or any other whitelisted host.
  * http://americanarchive.org/catalog/cpb-aacip_384-29p2nm62 (video)
  * http://americanarchive.org/catalog/cpb-aacip_16-804xg9fj63 (audio)

**Expected result:** after agreeing to TOS, the media plays.

**Actual result:** after agreeing to TOS, media does _not_ play.

**Comment by afred** [comment]
Tried clearing cookies, to see if stale cookie (with possibly different data) was causing the issue. Nope.

**Comment by afred** [comment]
Checking logs on demo

**Comment by caseyedavis12** [comment]
I am In vegas and also cannot access media in the Online Reading room

We are presenting on the AAPB at two conferences this week, one today. This is high priority.

________________________________

**Comment by afred** [comment]
@caseyedavis12 pushed a fix to production. Let me know if it doesn't work.

**Comment by caseyedavis12** [comment]
Working!!! Thanks so much for noticing this and for your prompt attention to it!
________________________________
