### ISSUE TITLE
Add Advanced Search link to header and footer

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1254]
Done when

- [x] Advanced Search link is added to header (except on homepage) next to search box. 
- [x] Advanced Search link is added to Footer.

**Comment by caseyedavis12** [comment]
@sroosa, can this be done pretty quickly by you?

**Comment by jasoncorum** [comment]
@caseyedavis12 and @sroosa - How does this look?

![screen shot 2017-08-02 at 10 22 57 am](https://user-images.githubusercontent.com/3814190/28878252-b83f93d4-776c-11e7-9ff6-1f33b418b61b.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: this looks great to me!

**Comment by jasoncorum** [comment]
@caseyedavis12 - apologies! almost missed adding it to the footer. any specific requests on location?

**Comment by caseyedavis12** [comment]
@jasoncorum: could you put it below Contact Us?


best,

Casey
