### ISSUE TITLE
Give the user an indication that something is happening when they switch the per-page count in search results.

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#1257]
**Probelm:** when you you do a search, and switch from "10 per page" to "100 per page", there's a lag of a couple of seconds, where nothing seems to happen. But actually, a new query is being run.

We need to give the user some kind of feedback when this is happening.

**Done when:**
  - [ ] approved screen shot of what this will look like visually
  - [ ] user receives visual feedback when switching the "per-page" count, using the approved visuals

**Comment by jasoncorum** [comment]
@sroosa - here are 3 different options for the loading icon. the icon will spins during page load and would disappear once it loads in it's entirety. let me know which one you think works best! thanks.

![screen shot 2017-08-04 at 8 34 22 am](https://user-images.githubusercontent.com/3814190/28968843-fb8620e8-78ef-11e7-8b31-cf99f69fbaae.png)
![screen shot 2017-08-03 at 4 00 27 pm](https://user-images.githubusercontent.com/3814190/28968844-fd107404-78ef-11e7-9e7c-7b9aae050679.png)
![screen shot 2017-08-03 at 3 57 15 pm](https://user-images.githubusercontent.com/3814190/28968848-ff8dd212-78ef-11e7-8389-e9e95ade0aa3.png)

**Comment by sroosa** [comment]
@jasoncorum: Casey and I agree on #2!
