### ISSUE TITLE
Media not playing on website or AMS

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1259]
Media is not playing on the AAPB website or in the AMS.

The error I receive on the public website says "The media could not be loaded, either because the server or network failed or because the format is not supported."

The error in the AMS says "VIdeo File Not Found: HTML5"

Media is playing in Sony Ci.

@afred @jasoncorum

**Comment by sroosa** [comment]
resolved on Sony Ci's end.
