### ISSUE TITLE
availability facet

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#126]
For now, mock it up. Getting the real data is #75, and is blocked right now.

**Comment by caseyedavis12** [comment]
Just commented on issue #75

**Comment by mccalluc** [comment]
Calling the facet "Access"
- "All"
- "Only Digitized"
- "Only Digitized and Playable"

(With the last option not deliverable till the fall.)

**Comment by mccalluc** [comment]
Going to say this is fixed with #142. Expect we'll need to look at how it actually works live.
