### ISSUE TITLE
Replace code in scripts/ci/ci.rb with code that uses the sony-ci-api gem. 

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#1260]
**Done when:** logic currently in `scripts/ci/ci.rb` does not duplicate what is currently in the `sony-ci-api` gem.

**Comment by cmhosale** [comment]
@afred scripts/ci/ci.rb fails often. The most recent upload I did 12 of 21 files failed. Can we look at the script and figure out what is going on and if we can increase the success rate, and improve failure reporting so that we're notified when an item fails?

**Comment by cmhosale** [comment]
@afred I reran the upload over night and only one failed, so clearly something was wrong with the way I did it earlier yesterday. I was testing a script so maybe I accidentally ran it twice, which caused a big set from the first attempt to fail or something.

**Comment by cmhosale** [comment]
@afred @sroosa ci.rb has stopped working for me. I run it, get no error messages, but every upload fails on Ci. My thought is that the API changed.
