### ISSUE TITLE
Create link capability to point to specific timecode in media file

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1266]
In AAPB curated exhibits or elsewhere, we would like to be able to use a hyperlink to point to a specific time code in a video or audio file. If someone clicks on the link, it will take the user to the record page to a specific time code in the media file.

We should check to see if we can link to a specific chapter heading using webvtt.

**Comment by sroosa** [comment]
Low effort because this is mainly investigating. If development will be required, make a new ticket with a new effort estimation.

**Comment by jasoncorum** [comment]
Note to self: see https://stackoverflow.com/questions/6221344/jump-to-timestamp-in-html5-embedded-video-with-video-js

**Comment by jasoncorum** [comment]
@sroosa - here's the format for using direct links to timecodes. It's in seconds.

http://localhost:3000/catalog/cpb-aacip_111-21ghx7d6#at_400.00_s

**Comment by caseyedavis12** [comment]
@jasoncorum, @sroosa: I tested this a couple of times and I wonder if I'm doing something wrong. For example, I tried to link to a NewsHour episode at 27:50. I converted this to seconds, which is 1620. However, when I create the link to start at 1620, it's about 48 seconds off. The spot where I want it to start actually begins at 1668.

**Comment by afred** [comment]
27 * 60+50 = 1670, right?

**Comment by caseyedavis12** [comment]
@afred: Whoops! Yes, you are correct. I should use a calculator next time.
