### ISSUE TITLE
Clicking on a record page from an exhibit opens HTML5 player in record

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1267]
If you click on a record page from an exhibit, the record page opens using the old HTML5 player and it includes the download option!

Here is an example: http://americanarchive.org/exhibits/presidential-elections/candidates (click on any hyperlinked item in the exhibit)

**Comment by jasoncorum** [comment]
Related to #1077. Similar fix. Eventually revisit #861.

**Comment by sroosa** [comment]
Closed by 1276
