### ISSUE TITLE
Add footnoting capabilities to wiki.americanarchive.org

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1273]
@rfraimow Can you add the done when statement with a reference to the ad-in to do this?

**Comment by rfraimow** [comment]
Done when: 'Extension: cite' is installed in the AAPB Wiki: https://www.mediawiki.org/wiki/Extension:Cite#Manual_installation

**Comment by jasoncorum** [comment]
Good to go! Give it atry @rfraimow and let me know.
