### ISSUE TITLE
ingest on AWS

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#128]
@afred: I think this is just my ruby ignorance, but what do I do to resolve this on AWS?
```
$ ruby scripts/pb_core_ingester.rb spec/fixtures/pbcore/clean-*.xml
/usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rsolr (LoadError)
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from scripts/pb_core_ingester.rb:1:in `<main>'
```

I guess I'm confused because the site is running now, but 
```
$ gem which rsolr
ERROR:  Can't find ruby library file or shared library rsolr
$ sudo ls /home/deploy/.bundler/aapb/ruby/2.1.0/gems | grep rsolr
rsolr-1.0.10
```

Ruby on the command line has a different class path than the code running in rails?

**Comment by afred** [comment]
yes. Rails has it's own conventions for specifying include paths. For instance, it adds `myproject/lib/` to the path, so you can `require` anything you put in there.

I don't know all of the nitty gritty, but if you do not load your rails environment in a script you are invoking from the command line, then your include paths may differ.

Curious that `gem which rsolr` didn't return anything. Try `bundle show rsolr` maybe?

Also... are you not using rvm? My rsolr gem is here:
```
$ gem which rsolr
=> /Users/andrew_myers/.rvm/gems/ruby-2.0.0-p353/gems/rsolr-1.0.10
```

**Comment by mccalluc** [comment]
got over this bump, so closing.
