### ISSUE TITLE
multiple rights statements

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1280]
Example:
http://americanarchive.org/catalog/cpb-aacip_509-6h4cn6zm21.pbcore

Done when:
- [ ] All rights statements appear on detail page for records with multiple rights statements

**Comment by jasoncorum** [comment]
@sroosa - do you want these to appear as completely different entries of rights statements? or do you want them to get concatenated in to one rights statement somehow?

so, with screenshots, do you want each rights statement to have their own individual line like:

![screen shot 2018-04-11 at 11 33 55 am](https://user-images.githubusercontent.com/3814190/38636175-595ebdaa-3d7c-11e8-847e-1c72c4a84963.png)

Or do you want something more like this? where each rights statement would correspond to a citation?

![screen shot 2018-04-11 at 11 35 16 am](https://user-images.githubusercontent.com/3814190/38636271-8e6fca66-3d7c-11e8-8ed5-3fde4d4ab8b0.png)

**Comment by sroosa** [comment]
@jasoncorum: I like the first option better as long as there's a hard return and a bit of white space between each rights summary

**Comment by jasoncorum** [comment]
@sroosa - just to doubly confirm, here's what that will look like. yay or nay?

![screen shot 2018-04-12 at 9 47 17 am](https://user-images.githubusercontent.com/3814190/38691762-9cb4fc6c-3e36-11e8-94fb-4782fcf00184.png)

**Comment by sroosa** [comment]
@jasoncorum Oh! I didn't understand your first question. I don't need it to say Rights twice or have a rule between the 2 entries. It can be formatted more like the citation section. Somehow the idea of "concatenating" them got my brain all confused.

**Comment by sroosa** [comment]
@jasoncorum yes!
