### ISSUE TITLE
Redesign Transcript Not Available icon

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1289]
Currently the icon looks like this:
<img width="988" alt="screen shot 2017-06-27 at 2 43 52 pm" src="https://user-images.githubusercontent.com/4029248/27604407-2fefe09c-5b47-11e7-8ca1-7eb2fb10c795.png">

But if you have the page pretty narrow, it looks like this: 
<img width="833" alt="screen shot 2017-06-27 at 2 43 58 pm" src="https://user-images.githubusercontent.com/4029248/27604429-3ce159a2-5b47-11e7-8995-787e3983bba6.png">

The icon should either enforce a space between Transcript and Not Available, or add a hard return if the page width narrows, so that Transcript is above Not Available. @jasoncorum what do you think is easiest/looks best?

Done when:
- [x] A decision is made about how to redesign the Transcript Not Available
- [x] The design appears on record pages where the transcript is not available

**Comment by sroosa** [comment]
Also, do we want to take this opportunity, while we're working in the area, to add something to the transcript not available message about how users can play FIX IT to help make more transcript available? Not sure if we want to do this right now, or if we want input from design before we move forward. We can also make another ticket for that work, separate from this one. @caseyedavis12, @jasoncorum, what do you think?

**Comment by jasoncorum** [comment]
@sroosa - I went with a font-size reduction for the narrow region in this screenshot. What do you think?

![screen shot 2017-07-13 at 9 12 13 am](https://user-images.githubusercontent.com/3814190/28167988-974966a8-67ab-11e7-948c-d91ec0d30b4a.png)

**Comment by sroosa** [comment]
@jasoncorum This looks good!
