### ISSUE TITLE
Document blog admin

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#129]
Who has admin privs? Where is it running?

**Comment by caseyedavis12** [comment]
I have admin privileges. I believe Sadie does as well. It is a hosted instance, not installed instance, of Wordpress.

**Comment by mccalluc** [comment]
@sroosa : Can you confirm you also have admin privs? (Close this if so.)

Just want to be sure it's not a single point of failure.

For documentation, I'm just saying that you two are admins, since I think that's all that needs to be said?

**Comment by sroosa** [comment]
I also have admin privs. @caseyedavis12 Bill also still have admin privs. Should we delete him as a user?

**Comment by caseyedavis12** [comment]
@Sroosa I removed Bill.
