### ISSUE TITLE
Create asset playlists for users to navigate segmented content

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1290]
Similar to how Open Vault handles the same issue:
<img width="1255" alt="screen shot 2017-06-27 at 2 54 13 pm" src="https://user-images.githubusercontent.com/4029248/27604826-9491210e-5b48-11e7-9d60-c0ea22e87ed1.png">

Assets that are Part X of Y will be grouped together and ordered using annotations. On any of their record pages, they should display links to the previous and next records in the playlist. 

Done when:
- [x] annotations are added to records in the AMS and provided as examples (and documentation is added to workflow documents about conventions for this)
- [x] the record page for every asset in a playlist provides links to the previous and next assets in the playlist.

**Comment by sroosa** [comment]
@jasoncorum so it turns out I couldn't combine all of the information into one annotation because the AMS doesn't support all of the pbcore attributes. So I did have I create 2 annotations for each record in the playlist. I use the exact same values for annotationType that are used in Open Vault, so hopefully it should be pretty easy to use the same structure for AAPB. I've add annotations to a set of 31 records making 7 playlists. I'll send you the GUIDs and the exported pbcore, and I can reindex them for testing if you need me to at any point.

**Comment by jasoncorum** [comment]
@afred - what are your thoughts about attempting to incorporate node packages in to AAPB? there are some slicker looking options than our OpenVault implementation that i'm interested in digging in to. i've spent some time this morning to see how complicated it would be, but don't want to go too far down a rabbit hole. specifically here are the packages i'm interested in:

https://github.com/brightcove/videojs-playlist
https://github.com/brightcove/videojs-playlist-ui

**Comment by afred** [comment]
👍 Brightcove provides the main developers to vidojs, so I assume their plugins would work pretty well.

The only way I've used npm is to install packages locally, so I'm not sure what implications this would have for testing and deployment. I assume that we'd have to install node on remote hosts, configure it on Travis, maintain a package.json file, etc. All doable things, but worth keeping in mind when estimating effort. What's your experience with it?

**Comment by jasoncorum** [comment]
@afred - My experience is about the same as yours on that front - just some local dabbling. This would definitely blow up our "medium" estimate on this but I think it would be a good longterm play especially as we start to expect more and more out of the video player. 

Just chatted with @sroosa and we're thinking that we implement the OpenVault style solution now and then I'll make 2 additional tickets:

1. Enable the ability to use node packages on AAPB
2. Another to use the Brightcove playlist plugins

If this sounds good, I'll make the 2 new tickets and start the OV style short-term solution.

**Comment by afred** [comment]
I Agree that it's good in the long run. Those 2 tickets sound good to me.

For "Enable the ability to use npm...", I imagine the **done looks like** would be to demonstrate actually downloading a node package, and successfully using it? If so, would we want that to be video.js?

**Comment by jasoncorum** [comment]
@sroosa - How does this look for the OV-style  implementation? 

![screen shot 2017-07-10 at 12 35 13 pm](https://user-images.githubusercontent.com/3814190/28028963-5c9a8870-656c-11e7-99da-ec86a77ef52a.png)

**Comment by sroosa** [comment]
@jasoncorum: Looks good to me! It's less intrusive than I thought it might be!
@caseyedavis12 just looked at it too, and she agrees we should go ahead with this design.
