### ISSUE TITLE
Transcript search usability

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1302]
- Hitting return button on keyboard does not initiate search in the transcript keyword search. I feel it should.
- When a search is initiated, if there are no results there is no indication that your search was completed with no results.
- if possible, search bar should show you number of search results (similar to how browsers show you with ctrl+f)

**Comment by jasoncorum** [comment]
How's this look y'all? @sroosa @cmhosale 

![screen shot 2017-07-18 at 11 50 52 am](https://user-images.githubusercontent.com/3814190/28327334-17df8ef6-6bb1-11e7-9683-096204612f18.png)

**Comment by sroosa** [comment]
Looks good! @jasoncorum how do you get from one result to the next? just enter? do we want to add arrows to cycle forward and backward through them, or would that be too cluttered?

**Comment by jasoncorum** [comment]
@sroosa - my bad, i was just highlighting the term and letting the user how many occurrences there are (no traversing results). i think we can do something that, so i'll dig in to it.

**Comment by afred** [comment]
I have a usage bias, but I really like the way Chrome's "Find on page" looks... 
![image](https://user-images.githubusercontent.com/1507490/28345370-3a121db4-6be7-11e7-81f7-9d8401b298db.png)

**Comment by caseyedavis12** [comment]
+1 to what @afred said.

**Comment by sroosa** [comment]
@jasoncorum +1 to ^
