### ISSUE TITLE
At launch, redirect americanarchiveinventory.org?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#131]
@caseyedavis12 : I'd guess americanarchiveinventory.org will go away at launch? Or maybe not? Some possibilities:
- Do nothing.
- Actually, keep it around, but add a note in the banner than more current data is available.
- It just 404s
- It will redirect to the top page at americanarchive.org
- For a subset of the pages, it redirects to something appropriate on the new site. (Looking at traffic numbers in analytics could help determine whether this is worth the effort.)

Thanks!

**Comment by caseyedavis12** [comment]
@Mccalluc: Have it redirect automatically to the home page at americanarchive.org

**Comment by mccalluc** [comment]
Here's how I'm thinking this will be done:
- Add a DNS CNAME for americanarchiveinventory.org -> americanarchive.org
- Like how we do the `host` based redirect for www.*, redirect these incoming requests, but send them all to the homepage. (Not interested in preserving distinctions in original URLs, though that could be done for some.)

**Comment by caseyedavis12** [comment]
Americanarchiveinventory.org dns records are managed by the WGBH name servers. Yesterday I submitted an IT request to handle the redirect. It has not been resolved yet, but maybe it will today.

**Comment by caseyedavis12** [comment]
WGBH IT has redirected americanarchiveinventory.org to americanarchive.org. Please do not delete everything off of the americanarchiveinventory.org server on AWS. I will create another ticket for backing up this content locally before shutting down the instance.
