### ISSUE TITLE
Multiple title display

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1327]
Watergate Library of Congress assets brought out the problem that the website displays the title of a record that have multiple titles in the order that those titles appear in the pbcore. The AMS exports titles in the order that they were created. This can cause problems with display. The Watergate titles should display in the order "Series Title"; "Episode Title"; "Segment Title", but currently displays with segment before episode, because segment was created first. We should change the website so that it knows to always display "Series" before "Episode" before "Segment".

If we wanted to make a more robust hierarchy I think the order for our most used title vocab is:

Series
Program
Episode
Raw Footage
Episode Number
Promo
Shot
Element
Segment
Clip

Any other uncontrolled term could probably be assumed to be on the same hierarchy level as anything after episode number? 

I see the ways that making a more robust hierarchy gets complicated, so maybe it is best to just say that Series comes before Episode comes before Segment.

**Comment by sroosa** [comment]
@cmhosale and @jasoncorum 
2 things - 
1. the uncontrolled terms all get normalized/filtered out pre-ingest into solr, so we don't have to worry about ordering those.
2. I think that Episode Number should come before Episode. Whenever you see an full title, it usually has something like Frontline 1234: Bombs and Money and Other Bad Things. I think a number hanging at the end would look really weird. Also, then they sort in order by episode number. 

I want to look at the part of the code that Chuck and I originally wrote to order these, and then makes adjustments based on that list. @jasoncorum: when you start working on this, can you send me that, so I can reorder them? Thanks!

**Comment by jasoncorum** [comment]
@sroosa - I think this is what you're referring to. Amiright?

collection: Collection
series: Series
program: Program
segment: Segment
number: Episode Number
epospde: Episode
episode: Episode
clip: Clip
advertis: Promo
trailer: Promo
promo: Promo
raw: Raw Footage
field tape: Raw Footage
element: Raw Footage
b-roll: Raw Footage
b roll: Raw Footage
album: Album
label: Label

**Comment by sroosa** [comment]
@jasoncorum: Yep! I think the mapping has one last row though, which is everything else gets mapped to "Title"
I'm gonna keep the mapping between terms the same, but rearrange the order. I basically just moved segment below label. 
collection: Collection
series: Series
program: Program
number: Episode Number
epospde: Episode
episode: Episode
clip: Clip
advertis: Promo
trailer: Promo
promo: Promo
raw: Raw Footage
field tape: Raw Footage
element: Raw Footage
b-roll: Raw Footage
b roll: Raw Footage
album: Album
label: Label
segment: Segment

**Comment by jasoncorum** [comment]
making a note that @sroosa, @cmhosale and I reviewed sorting by title with the Watergate exhibit.
