### ISSUE TITLE
Remove ported pages from blog

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#134]
Static pages will be ported from the blog (#133). Original list: (might be updated)
-    http://www.americanarchive.org/about-the-american-archive/
-    http://www.americanarchive.org/contact-us/
-    http://www.americanarchive.org/participating-orgs/
-    http://www.americanarchive.org/email-list/

post-launch, remove these pages from the blog.
(blog --> site redirects probably not necessary, but get confirmation.)

**Comment by mccalluc** [comment]
@sroosa: The site is up, so do you want to get rid of the redundant pages on the blog? No urgency: just want to minimize the possibility for confusion.

**Comment by sroosa** [comment]
@mccalluc  Casey wanted to keep the contact us and the email list pages on the blog. I've already taken down the participating orgs and about pages from the blog.

**Comment by mccalluc** [comment]
ok, close this if nothing else needs to be done?
