### ISSUE TITLE
Link to Supplemental Materials

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1340]
Add a section to the record page that says "Supplemental Materials Available" and then show links to open pdfs, jpgs, etc.

Metadata will look like, pbcoreAnnotation= "Type of Material" ; @annotationType = "Supplemental Material" ; @ref = "url on S3"

Done when:
- [x] a decision is made about where to put this section on the record page
- [x] annotations are added to the metadata
- [ ] links in the section open a new tab/popup that displays the item being linked to

**Comment by sroosa** [comment]
@caseyedavis12 @cmhosale : Let me know what you think about the idea below. 

We're trying to figure out where to put the links to supplemental materials (like the Ken Burns pdf transcript with his notes handwritten on them). The main space of real estate open on the screen is under the top portion, but over the titles and identifiers section. @jasoncorum's thinking of using a header and a horizontal bar to set that section apart from the rest of the metadata there.

**Comment by caseyedavis12** [comment]
@sroosa: this idea sounds good to me. Can you send a mock-up when it's ready?

**Comment by sroosa** [comment]
@jasoncorum: The metadata is ready for this. I'll send the pbcore xml attached to an email. For now, let's put the section just above the Titles/Identifiers section.

**Comment by jasoncorum** [comment]
@sroosa - i ended up liking it better below the titles. here's a screenshot. let me know if you'd like to see any variations!

![screen shot 2017-10-03 at 9 02 43 am](https://user-images.githubusercontent.com/3814190/31126476-e530bebc-a819-11e7-9229-882b3eb8b93f.png)
