### ISSUE TITLE
Wash U thumbnails not appearing

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1343]
Thumbnails for many of the Washington University programs are not appearing on the website:

http://americanarchive.org/catalog?f%5Bmedia_type%5D%5B%5D=Moving+Image&f%5Borganization%5D%5B%5D=Film+and+Media+Archive%2C+Washington+University+in+St.+Louis+%28MO%29&q=&f[access_types][]=digitized

**Comment by afred** [comment]
@caseyedavis12 I'm not seeing the thumbs in S3. Can you confirm whether or not they were put up there? Thanks!

**Comment by caseyedavis12** [comment]
@afred: @cmhosale is looking into this.

**Comment by sroosa** [comment]
closed outside of github
