### ISSUE TITLE
Index non-PopUp Archive transcripts

### ISSUE THREAD

**Issue by cmhosale** [WGBH/AAPB2#1344]
Transcripts that we put up for the online reading room need to be indexed (presuming that they haven't been). Going forward, we need the workflow for ingesting those transcripts to include indexing. We also need to test that having NewsHour transcripts indexed doesn't blow up searching on the AAPB in general.

**Comment by cmhosale** [comment]
Is there any way we could get this done by the CLIR visit, September 13th?

**Comment by jasoncorum** [comment]
In working on #1341, I realized we DO need to update the ingest code a little bit for non-json transcripts. Specifically this method on pb_core.rb:

``` ruby
def self.transcript_url(id)
  transcript_id = id.tr('_', '-')
  transcript_base = 'https://s3.amazonaws.com/americanarchive.org/transcripts'
  "#{transcript_base}/#{transcript_id}/#{transcript_id}-transcript.json"
end`

Need to be able to check for .txt transcripts on S3 as well.
