### ISSUE TITLE
Bring View All Exhibit Page in line with Special Collections design

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1349]
We want to update that View All Exhibits page (http://americanarchive.org/exhibits) to look like the Special Collection page. @caseyedavis12 will provide language for the blurb at the top for both Special Collections and Exhibits pages.

**Comment by jasoncorum** [comment]
@sroosa - How does this look? Will need new intro text for the this page as well.

![screen shot 2017-09-19 at 9 21 29 am](https://user-images.githubusercontent.com/3814190/30594426-056055de-9d1c-11e7-8ee5-301613a59ac0.png)

**Comment by sroosa** [comment]
@jasoncorum: This looks great! @caseyedavis12: Do we have language for Exhibits landing page? If not, can you send us some whenever it's approved?

**Comment by caseyedavis12** [comment]
@sroosa still waiting........
________________________________
