### ISSUE TITLE
Add annotations to Special Collections records

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1351]
All  records that we want to appear in a special collection need to have an annotation added in the metadata. The annotation should look like:

Annotation: name of the markdown file that holds the special collection content.
Annotation Type: "special_collections"

**Comment by jasoncorum** [comment]
@sroosa - In the refactor on this, we switched to a single value for this in the schema. The expected annotation is now:

<pbcoreAnnotation annotationType="Special Collection">ken-burns-civil-war</pbcoreAnnotation>

The value should equal the SpecialCollection markdown file name (with no file extension).

**Comment by sroosa** [comment]
completed in the AMS and sent annotation values to @jasoncorum over email.

**Comment by sroosa** [comment]
completed in the AMS and sent annotation values to @jasoncorum over email.
