### ISSUE TITLE
Add Events and Funding Opportunities under Whats New page in sidebar

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1360]
We need the Events and Funding Opportunities sub-pages to appear under the new Whats New page in the About sidebar.

**Comment by caseyedavis12** [comment]
@sroosa - is this easily done? Can it be prioritized?

**Comment by sroosa** [comment]
@caseyedavis12 I assume so. I'll put it high up and check in with Jason before he starts the actual work.

**Comment by jasoncorum** [comment]
@caseyedavis12 - is there a branch out there with these pages? is it whats-new-1?

**Comment by sroosa** [comment]
@jasoncorum yes, that's the one!

**Comment by caseyedavis12** [comment]
@jasoncorum - yes that's the correct branch, but it's not ready to be merged.

**Comment by jasoncorum** [comment]
Like this @caseyedavis12? I just added them towards the bottom, so feel free to let me know if you'd like them to appear in a different slot.

![screen shot 2017-10-10 at 2 26 38 pm](https://user-images.githubusercontent.com/3814190/31403533-526e73d6-adc7-11e7-8263-9f8dadf6a63e.png)

**Comment by caseyedavis12** [comment]
Hi @jasoncorum: Events and Funding Opportunities are sub-pages of the What's New page. Could they be indented  under What's New?

**Comment by jasoncorum** [comment]
@caseyedavis12 - We weren't using this functionality previously, but it's there. Here's what it currently looks like. If needed we can tweak the styles a bit.

![screen shot 2017-10-10 at 2 34 35 pm](https://user-images.githubusercontent.com/3814190/31403827-50c37d8c-adc8-11e7-88a0-ff221e6283a8.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: that's fine!

**Comment by sroosa** [comment]
Closed by #1388
