### ISSUE TITLE
Add Special Collections to floating nav and welcome panel

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1376]
We need to add Special Collections to the floating nav on the homepage and to the welcome panel.

If you need to shorten the text for it to fit, you can change the text to say:
"Organizations"
"Special Collections"
"Exhibits"
"Browse"
"Our Story"

![screen shot 2017-10-27 at 7 57 28 am](https://user-images.githubusercontent.com/5992135/32102986-99ef1c9c-baec-11e7-822b-b7eeb9b179fd.png)
![screen shot 2017-10-27 at 7 57 34 am](https://user-images.githubusercontent.com/5992135/32102987-99fc99c6-baec-11e7-930a-d1dc04adbc96.png)

**Comment by caseyedavis12** [comment]
@jasoncorum can this be done for next Monday/Tuesday's final redeploy?

**Comment by jasoncorum** [comment]
@caseyedavis12 - how does this look?

![screen shot 2017-10-27 at 11 42 43 am](https://user-images.githubusercontent.com/3814190/32114169-b0750160-bb10-11e7-80b5-438272da6f5d.png)

![screen shot 2017-10-27 at 11 43 01 am](https://user-images.githubusercontent.com/3814190/32114174-b6f11cc2-bb10-11e7-9348-ae97f890e7fa.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: awesome!
