### ISSUE TITLE
Watergate Exhibit LOC Image Captions

### ISSUE THREAD

**Issue by jasoncorum** [WGBH/AAPB2#1381]
We need to include an in page caption for LOC images in the Watergate exhibit.

**Done when** LOC images in the Watergate exhibit have their captions listed in page like the below screenshot.

![screen shot 2017-10-27 at 12 05 48 pm](https://user-images.githubusercontent.com/3814190/32114042-38200480-bb10-11e7-8a9d-7797233cf721.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: can you do this on the What's New page as well? I used one of the LOC images on the What's New page.
