### ISSUE TITLE
Remove "Suggested searches" on Special Collections search results

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1384]
Remove "Suggested searches" on Special Collections search results

![screen shot 2017-10-28 at 9 21 58 am](https://user-images.githubusercontent.com/5992135/32134751-f9a34520-bbc1-11e7-8b42-3ec12489da70.png)

**Comment by jasoncorum** [comment]
@caseyedavis12 - How does this look? Apologies I missed these when I did the work to hide them (if not included in the Special Collection markdown). This matches the same behavior.

![screen shot 2017-10-30 at 11 32 11 am](https://user-images.githubusercontent.com/3814190/32179680-6983c036-bd66-11e7-96b0-1cf883b4b090.png)

**Comment by caseyedavis12** [comment]
@jasoncorum: looks good.
