### ISSUE TITLE
Why aren't NewsHour .srts being shows as CC, when other .srts are?

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1414]
NewsHour .srts have been added to s3 since the initial 40,000 hours. While the other records with .srts have captions appear in the player and have a CAPTION_ANNOTATION added on ingest, these NewsHour ones don't. Besides being added later, these records also have both a .txt transcrit and a .srt caption file, so that could also be the root of the difference. 

Done Looks Like: an explanation of why this is happening and a plan to refactor, update metadata, etc. to address the problem so that transcripts and captions appear as desired. We would currently like both to appear (the transcripts in the viewer and the captions as captions on the video)

**Comment by foglabs** [comment]
It looks like this is just a matter of missing 'Captions URL' annotations, as mentioned - the captions_src method relies on the annotation to attempt to download the SRT.
