### ISSUE TITLE
NAEB Special Collection

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#1416]
@jasoncorum, I created an NAEB special collection here: https://github.com/WGBH/AAPB2/blob/naeb-special-collection/app/views/special_collections/naeb.md

The featured items are all audio. Do I need to upload the audio thumbnail and link to it in the Featured Items section, or will it automatically pull the audio icon if it doesn't include an image?

**Comment by jasoncorum** [comment]
@caseyedavis12 - it does require an image to be included in the markdown, but it doesn't necessarily need to a new image be uploaded. i'm not entirely sure this will look good at our dimensions, but you can try just dropping the regular audio-only image URL in for them: http://americanarchive.org/thumbs/audio-digitized.jpg. If it doesn't look good, I can make a new crop.

**Comment by sroosa** [comment]
Closed by #1435
