### ISSUE TITLE
Update FIX IT section on homepage

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1445]
Updating this section to highlight all of the crowdsourcing efforts, not just FIX IT.

Add to labels above search box and floating nav – “Help us!” URL: americanarchive.org/#help-us

Header: Help Preserve Public Media!
Subheader: AAPB Citizen Archivist Toolkit
Descriptive text: You can make historic public radio and television programs from across America easier to search and access. Help AAPB archivists by participating in any of our Citizen Archivist tools – FIX IT, FIX IT+, or Roll the Credits! Your contributions will made available in the American Archive of Public Broadcasting.

Left box:
FIX IT logo
Play our game to correct speech-to-text transcripts (link to http://fixit.americanarchive.org/)

Middle box:
FIX IT+
Use this simple tool to correct speech-to-text transcripts ( link to http://fixitplus.americanarchive.org/)

Right box:
Roll the Credits
Transcribe credit information from digitized public television programs (link to https://www.zooniverse.org/projects/sroosa/roll-the-credits)

**Comment by jasoncorum** [comment]
@caseyedavis12 - i did up a couple screenshots of options for the section. i did one with and one without the fix it logo just to get a sense of what it would look like both ways. thoughts?

![screen shot 2018-03-14 at 3 30 46 pm](https://user-images.githubusercontent.com/3814190/37426975-4cc254e2-279e-11e8-8016-7688bcb9917c.png)

![screen shot 2018-03-14 at 3 31 27 pm](https://user-images.githubusercontent.com/3814190/37426977-4e6fdc42-279e-11e8-8aec-0ee9c0fa031d.png)
