### ISSUE TITLE
Updating embed video view

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1449]
Bring in Bootstrap and VideoJS to make video and text display fluid. The text should display to the right of the player, but stack when the view is narrowed. 

Change the information that appears around the video, deleting what is currently there (transcripts, etc.) and adding:
- Title, hyperlinked back to the record page
- Contributing Org
- By accessing this content you agree to the AAPB's Online Reading Room Rules of Use. (hyperlinked)

**Comment by jasoncorum** [comment]
@sroosa - here is the responsive embed player in an iframe. @caseyedavis12 took a quick look on friday before she left, but it wasn't quite finalized yet. thoughts?

![screen shot 2018-03-19 at 9 47 08 am](https://user-images.githubusercontent.com/3814190/37599251-ac621b0c-2b5a-11e8-8800-7e52952414aa.png)

![screen shot 2018-03-19 at 9 47 31 am](https://user-images.githubusercontent.com/3814190/37599255-ae219468-2b5a-11e8-89ac-b835998c0bdb.png)

**Comment by sroosa** [comment]
@jasoncorum: Looks good to me! Let's go with it!

**Comment by caseyedavis12** [comment]
Thank you, @jasoncorum and @sroosa! When this is ready and live, please let me know so that I can have our colleagues at Bunk History test it.
