### ISSUE TITLE
Getting a 404 on Transcript API

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1457]
http://americanarchive.org/api/cpb-aacip_37-83xsjcdw/transcript is giving me a 404, even when I have credentials and have checked that the metadata and transcript are in place. 

Is it possible the API isn't giving a transcript because the Transcript Status annotation is Indexing Only Transcript? The access we want to provide is to any transcript (Online Reading Room Transcript or Indexing Only Transcript) if the Level of User Access is Online Reading Room.

**Comment by jasoncorum** [comment]
@sroosa - I just reviewed the code and that is correct: the api doesn't present the transcript because it is marked as an Indexing Only Transcript.

**Comment by sroosa** [comment]
@jasoncorum ok. I'll make a new ticket to update the API to allow for presentation of Indexing Only Transcripts.

**Comment by sroosa** [comment]
This is not an error, the code just doesn't do what we were trying to have it do.
