### ISSUE TITLE
Change copyright label to copyright date

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1465]
The label for copyright date is just "Copyright" It's a little confusing in the UI, so it should be changed to Copyright Date

**Comment by jasoncorum** [comment]
@sroosa - do you have an example record for this? i think i see where this is coming from in the code, but i don't think we have any test records using it. it would be good to get one in our tests. thanks!

**Comment by caseyedavis12** [comment]
@jasoncorum, here is an example: http://americanarchive.org/catalog/cpb-aacip_23-913n63j1


cc @sroosa

**Comment by jasoncorum** [comment]
@caseyedavis12 - Thanks!

**Comment by jasoncorum** [comment]
@sroosa @caseyedavis12 - just as an fyi on this, the vocab map for the copyright text gets applied during ingest, so any record that we want to have the updated label will need to be re-ingested.

**Comment by afred** [comment]
Changing a label should't rely on a re-ingest. I wasn't aware that was the case.
