### ISSUE TITLE
Handle assets with "No AAPB Contributor" as org

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1470]
In the NET collection there are some assets that we don't know of any copies of held by any organizations. These have been grouped into No AAPB Contributor, which is exported as the organization they belong to, the same way a record would have WGBH as it's organization. We would like to have these assets just not have a Contributing Org at all, rather than showing the value No AAPB Contributor.

**Comment by jasoncorum** [comment]
@sroosa - how tied are we to `<pbcoreAnnotation annotationType="organization">No AAPB Contributor</pbcoreAnnotation>'? i think it looks weird to do that in the xml and i think it might be easier to handle without a `annotationType="organization"` at all.

**Comment by sroosa** [comment]
@jasoncorum yes, I agree. However, the AMS requires an organization, and so we had to create something that explained these didn't really have an org, but still satisfied the AMS's requirements. The AMS then inserts that annotation on export. If we wanted to remove it when the metadata gets prep-processed and validated for ingestion that would be fine too.
