### ISSUE TITLE
Handle assets with multiple organizations

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1471]
Starting with NET, AAPB will have assets that have multiple Contributing Organizations. The metadata will have these as sibling elements (I'll provide an example xml file over email). All contributing organizations should be listed on the record page, and the record should show up when faceted by any of the contributing organizations names.

**Comment by sroosa** [comment]
In the search results design, if the organization is shown, then list the organizations with commas between the names if there are multiple.

**Comment by jasoncorum** [comment]
Note: this also allows for multiple states as that is needed for multiple orgs.
