### ISSUE TITLE
Add Producing Organization and switch Contributing Organization

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1495]
We are now using a Creator Role "Producing Organization" which we would like to pull out separate from other Creators. 

This field is repeatable, we'd like it to be keyword searchable, and we'd like it to be facetable, although we know that will be a very long facet. It should also be displayed in the search results in addition to Contributor/Organization. 
Producing Organization should also come above Contributing Organization on the side menu on the record page.

 Contributing Organization should no longer come from the "organization" typed annotation in the xml. It should instead come from each instantiation. It should still be repeatable, keyword searchable, and facetable.

**Comment by jasoncorum** [comment]
from @sroosa:

[5:26 AM] Sadie Roosa: Hey! We had a change of heart with this ticket: https://github.com/WGBH/AAPB2/issues/1495
[5:26 AM] Sadie Roosa: At first it said to replace a lot of the instances of Contributor/Organization with Producing Organization, but now we just want them both.
[5:26 AM] Sadie Roosa: Sorry to change it in the middle of your work!
[5:27 AM] Sadie Roosa: Let me know if you have any questions about the new acceptance criteria.

**Comment by jasoncorum** [comment]
@sroosa - how do these look?

![screen shot 2018-06-29 at 10 14 49 am](https://user-images.githubusercontent.com/3814190/42105519-6ec4596a-7b85-11e8-99f5-7e79e4c58baf.png)

![screen shot 2018-06-29 at 10 15 23 am](https://user-images.githubusercontent.com/3814190/42105526-7193eade-7b85-11e8-94ad-ba6d92af3c70.png)

**Comment by sroosa** [comment]
@jasoncorum Great! Can you change the Facet from Organization to Contributing Organization? Otherwise, all good!

**Comment by sroosa** [comment]
@jasoncorum and can you have the Producing Organization facet come above Contributing Organization facet?

**Comment by sroosa** [comment]
Closed by #1490
