### ISSUE TITLE
Add text box to AAPB Contributor Holdings section

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1498]
As in teh redesign pdfs, under the AAPB Contributor Holdings header on a record page, there should be a box under all of the entries that says: If you have a copy of this asset and would like us to add it to our catalog, please contact us. 

If there are no entries for the AAPB Contributor Holdings section, the section should still appear and should just have that box.

**Comment by jasoncorum** [comment]
Included in this PR: https://github.com/WGBH/AAPB2/pull/1490

**Comment by sroosa** [comment]
Closed by #1490
