### ISSUE TITLE
Create licensing info modals

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1505]
## Description 
We want to add a button that pops up a modal with language about licensing content on some detail pages. Button will only appear if there's a value to display. See below for design ideas.

Data model: single value per item, does not need to be keyword searchable or facetable. 

Data in the PBCore xml: It will come in <pbcoreAnnotation annotationType="Licensing Info"></pbcoreAnnotation>
Sample xml file in comments below. 

## Done Looks Like
- [x] Button appears on a record page when Licensing Info exists for a record. 
- [x] Button does not appear on a record page when no Licensing Info exists for a record.
- [x] When a user clicks the button a modal pops up with the Licensing Info content. 
- [x] Design of the button and modal are approved by PM
- [x] Licensing Info we have is moved into Annotations in the AMS
- [x] Update fixtures

**Comment by sroosa** [comment]
@caseyedavis12 can you let us know how you want this to appear on the page?

**Comment by sroosa** [comment]
Here's a sample xml record with this type of annotation. {"Attachments":[{"IsIrmRestricted":false,"__type":"ItemIdAttachment:#Exchange","ItemId":{"__type":"ItemId:#Exchange","Id":"AAMkADY1NTI0OThmLTBmYWQtNDViZC1iZjJkLWNkZTE2MjQyYjVhOABGAAAAAABPgvogbGbGQ5tsFcVKLtk6BwBQCvY184aDTqXc0PPCxVbBACnH9emJAABJ+qdpW6s1Q6QKt3+Y8iUQAALn840NAAA=","ChangeKey":null},"Name":"AMS XML Export","IsInline":false}]}

**Comment by jasoncorum** [comment]
<img width="1273" alt="screen shot 2018-10-03 at 11 41 23 am" src="https://user-images.githubusercontent.com/3814190/46431870-c04d8280-c701-11e8-9b04-ef1c77f6fc5c.png">

How does this look @sroosa? I'm using the special collection design for some more consistency across the site in modals.

**Comment by sroosa** [comment]
@jasoncorum I like the modal and I love that it's consistent with other ones we use on the site. @caseyedavis12 what do you think of the modal and how about the design and placement of the button to get the modal to pop up?

**Comment by caseyedavis12** [comment]
Looks great! @jasoncorum @sroosa

**Comment by sroosa** [comment]
closed by #1590
