### ISSUE TITLE
Fix links out to media on new record page designs

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1545]
http://54.146.149.53/catalog/cpb-aacip_15-9fj29c7n
This record is supposed to have the link out underneath the player, like it does in current production: http://americanarchive.org/catalog/cpb-aacip_15-9fj29c7n

**Comment by foglabs** [comment]
Seems to be fixed in current master:

![screen shot 2018-08-22 at 3 02 44 pm](https://user-images.githubusercontent.com/8140840/44484709-80807f00-a61c-11e8-8cb4-995158f1ce39.png)

**Comment by sroosa** [comment]
@foglabs great! I'll make sure to test again on demo before we release.

**Comment by sroosa** [comment]
I think this was also sometimes being a problem because of that video player issue, that was fixed by #1599
