### ISSUE TITLE
Add abilty to show SRTs in the transcript viewer

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1550]
For files that have an SRT file and don't have a corrected transcript, we'd like to display the SRT file in the transcript viewer.

DONE WHEN:

- [x] Transcript Viewer can display SRTs

- [x] SRTs display in view, if 1. they exist and 2. transcript status /= Online Reading Room Transcript

**Comment by foglabs** [comment]
I fixed the srt_to_html method for CaptionConverter - the output will work with the transcript viewer now, but the breakpoints are pretty close together; we might want to think about gluing the content from each set of three breakpoints together.

**Comment by sroosa** [comment]
Closed by #1669
