### ISSUE TITLE
Update Library of Congress logo

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1569]
New logo for the library of congress. Shared several versions in the dev channel. Need to replace current logo and double check that the new one looks okay everywhere that the logo appears on AAPB.

**Comment by foglabs** [comment]
<img width="1332" alt="screen shot 2018-09-28 at 2 37 39 pm" src="https://user-images.githubusercontent.com/8140840/46227221-8a3c8700-c32c-11e8-9831-0f29d845c689.png">

**Comment by caseyedavis12** [comment]
@henryneels: Can we make it a little smaller? It looks bigger than WGBH.

**Comment by sroosa** [comment]
@caseyedavis12 it's not taller than the WGBH one. They actually have a wrapper around them that makes then the exact same height. It is wider, but we can't change the proportions. Do you think we need to spend some time figuring out how to make them appear more than same size?

**Comment by sroosa** [comment]
closed by #1584
