### ISSUE TITLE
custom 404?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#161]
Do we need a custom 404 page? Should it share the header and footer, or be its own thing?

**Comment by caseyedavis12** [comment]
Good idea. Let's keep the header and footer and have it say:

"404: Page not Found
Sorry, but the page you are looking for has not been found. Try checking the URL for errors and then hit the refresh button on your browser, or use the links or the search feature in the header to see if you can navigate to the page you're looking for. If you still can't find it, [contact us] and we'll try to help."
