### ISSUE TITLE
Dates in facet

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#164]
@mccalluc @sroosa -- Can we hide the "years" in the facet that occur before the 20th century? :-)

**Comment by mccalluc** [comment]
@sroosa : unless you're planning to do some bulk cleaning, I could clear those as part of ingest. Talk in person?

**Comment by mccalluc** [comment]
We will just remove it from the xml at ingest.
```xml
<pbcoreAssetDate dateType="broadcast">0000-00-00</pbcoreAssetDate>
```

**Comment by caseyedavis12** [comment]
Great, there are a few other years that are appearing prior to the 20th century currently including:


  *   0000<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0000&q=&search_field=all_fields>99
  *   0004<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0004&q=&search_field=all_fields>1
  *   0005<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0005&q=&search_field=all_fields>1
  *   0007<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0007&q=&search_field=all_fields>2
  *   0008<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0008&q=&search_field=all_fields>1
  *   0199<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0199&q=&search_field=all_fields>1
  *   0200<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0200&q=&search_field=all_fields>1
  *   0201<http://beta.americanarchive.org/catalog?f%5Byear%5D%5B%5D=0201&q=&search_field=all_fields>1

**Comment by sroosa** [comment]
@caseyedavis12  We're just removing any pre-1900s Asset Date at ingest.
