### ISSUE TITLE
Labels on detail page should not appear if there is no data

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#165]
I think this should apply to all fields (ex. Asset Type, Duration, etc.), and also the section headers that Mike has included (ex. "Dates" over a list of all the dates and date types, "Titles" over all titles and title types, "Identifiers" over all identifiers and sources).

**Comment by sroosa** [comment]
Or we could have the section headers appear all of the time, and if there is no date it could say "No dates available." @caseyedavis12 what do you prefer? or should this be a design question?

**Comment by caseyedavis12** [comment]
Hmm.. Thinking from the perspective of the user, date is definitely something the user will be looking for. I think we should keep the user informed about the status of the record as much as possible. I like the idea about adding "No dates currently available. This record has not been cataloged. If you know the date, we want to know! Contact us if you want to provide information about this item."

How does that sound? We can reword, but something to that effect.

Sorry  -- I can't find it in my notes --  but what did we decide about the Comment Box for April? Can we add the Facebook comment box for April? @murazsko, have you found the Facebook comment box to be a useful way of generating new metadata? How do you get notified when a user has commented?

**Comment by caseyedavis12** [comment]
Hi,

Updating my suggestion:

"No dates currently available. This record has not been cataloged. If you know more information about this asset, we want to know! [Click here] to contact us."

The Contact Us box doesn't need to have the subject line feature by April unless it is easy to do.

Best,
Casey

**Comment by sroosa** [comment]
@caseyedavis12 I don't want to say that the record hasn't been cataloged. Many of the records that have been cataloged will still not have dates.

**Comment by caseyedavis12** [comment]
Ok, you can remove that sentence from the statement.
