### ISSUE TITLE
Default message on detail page if there are no dates in data

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#167]
Under the Dates section on the details page, if there is no date data, then it should read "No dates currently available. If you know more information about this asset, we want to know! [Click here] to contact us."

**Comment by mccalluc** [comment]
That's a lot of text, and I'm not sure dates are that special: Any of the fields might have bad data that we would like to have improved. --> I think we need to think this through more carefully.

**Comment by mccalluc** [comment]
casey writes:
>
What about adding similar text (like the caution banner) at the bottom of the Detailed Record Page like:
>
"If you have more information about this item than what is listed in our record, we want to know! [Contact us], indicating the AAPB ID (cpb-aacip/…), to provide us with better information."
>
Then, just don't show any label if there is no data in a certain field.

**Comment by mccalluc** [comment]
Examples:
- http://beta.americanarchive.org/catalog/cpb-aacip_55-74cnq4jz
- http://beta.americanarchive.org/catalog/cpb-aacip_52-79v15pj1

**Comment by mccalluc** [comment]
Fixed in #175
