### ISSUE TITLE
Record pages with multiple special collection tags display a banner for each special collection

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#1732]
Here's a record with 2 special collection tags that needs to display both special collection banners. Right now, it's returning a 500 error. http://americanarchive.org/catalog/cpb-aacip_512-wp9t14vq4k

**Comment by jasoncorum** [comment]
@sroosa - it looks like the issue here is that one of the SpecialCollections is "peabody" which hasn't been published on AAPB yet. do we want to just skip a collection in the display if it can't be found?

**Comment by sroosa** [comment]
@jasoncorum yes, skip if it can't be found! That will be much easier for us!
