### ISSUE TITLE
Get example of AMS record with Ci-ID

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#228]
@foo4thought : could you point me at one AMS record that has the Ci-ID in the place it should be? I know it's gone back and forth. Just pasting in this bug would be fine.

**Comment by foo4thought** [comment]
GUID='cpb-aacip/17-00000qrv'
https://ams.americanarchive.org/records/details/285233
Here's the load:
<?xml version="1.0" encoding="UTF-8"?>
<pbcoreDescriptionDocument xmlns="http://www.pbcore.org/PBCore/PBCoreNamespace.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcore.org/PBCore/PBCoreNamespace.html http://www.pbcore.org/xsd/pbcore-2.0.xsd">
  <pbcoreAssetType>Episode</pbcoreAssetType>
  <pbcoreIdentifier source="http://americanarchiveinventory.org">cpb-aacip/17-00000qrv</pbcoreIdentifier>
  <pbcoreIdentifier source="LPB">LSWI-19830729</pbcoreIdentifier>
  <pbcoreIdentifier source="LPB">LSWI-644</pbcoreIdentifier>
  <pbcoreIdentifier source="Sony Ci">202918e4b19141c0ad0428da668222ea</pbcoreIdentifier>
  <pbcoreTitle titleType="Episode">Episode 644</pbcoreTitle>
  <pbcoreTitle titleType="Series">Louisiana: The State We're In</pbcoreTitle>
  <pbcoreDescription descriptionType="Abstract">n/a</pbcoreDescription>
  <pbcoreGenre>Newsmagazine</pbcoreGenre>
  <pbcoreRelation>
    <pbcoreRelationIdentifier>LSWI</pbcoreRelationIdentifier>
    <pbcoreRelationType>Is Part Of</pbcoreRelationType>
  </pbcoreRelation>
  <pbcoreCreator>
    <creator>Louisiana Public Broadcasting</creator>
    <creatorRole>Production Unit</creatorRole>
  </pbcoreCreator>
  <pbcorePublisher>
    <publisher>Louisiana Educational Television Authority</publisher>
    <publisherRole>Copyright Holder</publisherRole>
  </pbcorePublisher>
  <pbcoreInstantiation>
    <instantiationIdentifier source="Louisiana Public Broadcasting Archives">LSWI-19830729</instantiationIdentifier>
    <instantiationDate dateType="created">1983-07-29</instantiationDate>
    <instantiationDate dateType="issued">1983-07-29</instantiationDate>
    <instantiationPhysical>3/4 inch videotape: U-matic</instantiationPhysical>
    <instantiationLocation>LPB Tape Library - SWI Shelf</instantiationLocation>
    <instantiationMediaType>Moving Image</instantiationMediaType>
    <instantiationGenerations>Master</instantiationGenerations>
    <instantiationDuration>00:28:56</instantiationDuration>
    <instantiationChannelConfiguration>Ch 1 MOS; Ch 2 Full Mix</instantiationChannelConfiguration>
    <instantiationAlternativeModes>N</instantiationAlternativeModes>
    <instantiationExtension>
      <extensionWrap>
        <extensionElement>AACIP Record Nomination Status</extensionElement>
        <extensionValue>Nominated/1st Priority</extensionValue>
        <extensionAuthorityUsed>AACIP</extensionAuthorityUsed>
      </extensionWrap>
    </instantiationExtension>
  </pbcoreInstantiation>
  <pbcoreInstantiation>
    <instantiationIdentifier source="mediainfo">cpb-aacip-17-00000qrv.j2k.mxf</instantiationIdentifier>
    <instantiationDate dateType="encoded">2013-04-30</instantiationDate>
    <instantiationDigital>application/mxf</instantiationDigital>
    <instantiationStandard>OP-1a</instantiationStandard>
    <instantiationLocation>N/A</instantiationLocation>
    <instantiationMediaType>Moving Image</instantiationMediaType>
    <instantiationGenerations>Preservation Master</instantiationGenerations>
    <instantiationFileSize unitsOfMeasure="GiB">11</instantiationFileSize>
    <instantiationDataRate unitsOfMeasure="Mbps">52</instantiationDataRate>
    <instantiationTracks>1 video, 1 audio</instantiationTracks>
    <instantiationChannelConfiguration>4 channel</instantiationChannelConfiguration>
    <instantiationEssenceTrack>
      <essenceTrackType>video</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">2</essenceTrackIdentifier>
      <essenceTrackStandard>NTSC</essenceTrackStandard>
      <essenceTrackEncoding source="mediainfo" ref="http://www.morgan-multimedia.com/JPEG 2000/">JPEG 2000</essenceTrackEncoding>
      <essenceTrackDataRate unitsOfMeasure="Mbps">47</essenceTrackDataRate>
      <essenceTrackFrameRate>59.940</essenceTrackFrameRate>
      <essenceTrackBitDepth>8</essenceTrackBitDepth>
      <essenceTrackFrameSize>720 x 486</essenceTrackFrameSize>
      <essenceTrackAspectRatio>2.963</essenceTrackAspectRatio>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
      <essenceTrackAnnotation annotationType="colorspace">YUV</essenceTrackAnnotation>
      <essenceTrackAnnotation annotationType="subsampling">4:2:2</essenceTrackAnnotation>
    </instantiationEssenceTrack>
    <instantiationEssenceTrack>
      <essenceTrackType>audio</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">3</essenceTrackIdentifier>
      <essenceTrackEncoding source="mediainfo">PCM</essenceTrackEncoding>
      <essenceTrackDataRate unitsOfMeasure="Kbps">3072</essenceTrackDataRate>
      <essenceTrackSamplingRate>48.0 KHz</essenceTrackSamplingRate>
      <essenceTrackBitDepth>16</essenceTrackBitDepth>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
    </instantiationEssenceTrack>
    <instantiationAnnotation annotationType="encoded by">OpenCube MXFTk Advanced 2.4.6.0.1</instantiationAnnotation>
  </pbcoreInstantiation>
  <pbcoreInstantiation>
    <instantiationIdentifier source="mediainfo">cpb-aacip-17-00000qrv.mpeg2.mxf</instantiationIdentifier>
    <instantiationDate dateType="encoded">2013-04-30</instantiationDate>
    <instantiationDigital>application/mxf</instantiationDigital>
    <instantiationStandard>OP-1a</instantiationStandard>
    <instantiationLocation>N/A</instantiationLocation>
    <instantiationMediaType>Moving Image</instantiationMediaType>
    <instantiationGenerations>Mezzanine</instantiationGenerations>
    <instantiationFileSize unitsOfMeasure="GiB">13</instantiationFileSize>
    <instantiationDataRate unitsOfMeasure="Mbps">63</instantiationDataRate>
    <instantiationTracks>1 video, 1 audio, 1 text</instantiationTracks>
    <instantiationChannelConfiguration>4 channel</instantiationChannelConfiguration>
    <instantiationEssenceTrack>
      <essenceTrackType>video</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">2</essenceTrackIdentifier>
      <essenceTrackStandard>NTSC</essenceTrackStandard>
      <essenceTrackEncoding source="mediainfo">MPEG-2 Video</essenceTrackEncoding>
      <essenceTrackDataRate unitsOfMeasure="Mbps">48</essenceTrackDataRate>
      <essenceTrackFrameRate>29.970</essenceTrackFrameRate>
      <essenceTrackBitDepth>8</essenceTrackBitDepth>
      <essenceTrackFrameSize>720 x 486</essenceTrackFrameSize>
      <essenceTrackAspectRatio>4:3</essenceTrackAspectRatio>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
      <essenceTrackAnnotation annotationType="colorspace">YUV</essenceTrackAnnotation>
      <essenceTrackAnnotation annotationType="subsampling">4:2:2</essenceTrackAnnotation>
    </instantiationEssenceTrack>
    <instantiationEssenceTrack>
      <essenceTrackType>audio</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">3</essenceTrackIdentifier>
      <essenceTrackEncoding source="mediainfo">PCM</essenceTrackEncoding>
      <essenceTrackDataRate unitsOfMeasure="Mbps">12</essenceTrackDataRate>
      <essenceTrackSamplingRate>48.0 KHz</essenceTrackSamplingRate>
      <essenceTrackBitDepth>16</essenceTrackBitDepth>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
    </instantiationEssenceTrack>
    <instantiationEssenceTrack>
      <essenceTrackType>text</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">2-1</essenceTrackIdentifier>
      <essenceTrackEncoding source="mediainfo">EIA-708</essenceTrackEncoding>
    </instantiationEssenceTrack>
    <instantiationAnnotation annotationType="encoded by">OC   OCTk 2.4</instantiationAnnotation>
  </pbcoreInstantiation>
  <pbcoreInstantiation>
    <instantiationIdentifier source="mediainfo">cpb-aacip-17-00000qrv.h264.mov</instantiationIdentifier>
    <instantiationDate dateType="encoded">2013-04-30</instantiationDate>
    <instantiationDigital>video/mp4</instantiationDigital>
    <instantiationStandard>QuickTime</instantiationStandard>
    <instantiationLocation>N/A</instantiationLocation>
    <instantiationMediaType>Moving Image</instantiationMediaType>
    <instantiationGenerations>Proxy</instantiationGenerations>
    <instantiationFileSize unitsOfMeasure="MiB">179</instantiationFileSize>
    <instantiationDataRate unitsOfMeasure="Kbps">856</instantiationDataRate>
    <instantiationTracks>1 video, 1 audio, 1 menu</instantiationTracks>
    <instantiationChannelConfiguration>2 channel</instantiationChannelConfiguration>
    <instantiationEssenceTrack>
      <essenceTrackType>video</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">1</essenceTrackIdentifier>
      <essenceTrackEncoding source="mediainfo" ref="http://developers.videolan.org/x264.html">AVC</essenceTrackEncoding>
      <essenceTrackDataRate unitsOfMeasure="Kbps">723</essenceTrackDataRate>
      <essenceTrackFrameRate>29.970</essenceTrackFrameRate>
      <essenceTrackBitDepth>8</essenceTrackBitDepth>
      <essenceTrackFrameSize>480 x 360</essenceTrackFrameSize>
      <essenceTrackAspectRatio>4:3</essenceTrackAspectRatio>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
      <essenceTrackLanguage>eng</essenceTrackLanguage>
      <essenceTrackAnnotation annotationType="colorspace">YUV</essenceTrackAnnotation>
      <essenceTrackAnnotation annotationType="subsampling">4:2:0</essenceTrackAnnotation>
    </instantiationEssenceTrack>
    <instantiationEssenceTrack>
      <essenceTrackType>audio</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">2</essenceTrackIdentifier>
      <essenceTrackEncoding source="mediainfo">AAC LC</essenceTrackEncoding>
      <essenceTrackDataRate unitsOfMeasure="Kbps">128</essenceTrackDataRate>
      <essenceTrackSamplingRate>48.0 KHz</essenceTrackSamplingRate>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
      <essenceTrackLanguage>eng</essenceTrackLanguage>
    </instantiationEssenceTrack>
    <instantiationEssenceTrack>
      <essenceTrackType>menu</essenceTrackType>
      <essenceTrackIdentifier source="mediainfo">3</essenceTrackIdentifier>
      <essenceTrackEncoding source="mediainfo">TimeCode</essenceTrackEncoding>
      <essenceTrackDuration>00:29:16</essenceTrackDuration>
      <essenceTrackLanguage>eng</essenceTrackLanguage>
    </instantiationEssenceTrack>
    <instantiationAnnotation annotationType="encoded by">Apple QuickTime</instantiationAnnotation>
  </pbcoreInstantiation>
  <pbcoreAnnotation annotationType="last_modified">2015-03-12 12:57:21</pbcoreAnnotation>
  <pbcoreAnnotation annotationType="organization">Louisiana Public Broadcasting</pbcoreAnnotation>
</pbcoreDescriptionDocument>
