### ISSUE TITLE
Set up AMS for new media download location?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#230]
@foo4thought : So, once the Ci IDs have been imported into and exported from the AMS, and imported into the americanarchive, the `*.americanarchive.org/media/[id]` forwarder can be used instead of Crawford for displaying media in the AMS. 

One small difficulty is that the old ids were all dashes, I think, while the new IDs replace the slash with an underscore. I also don't know whether this url is represented explicitly for each record, or if there's just one place that specifies the hostname, and then an ID is just concatenated to that.

**Comment by foo4thought** [comment]
I don't understand the assignment.

**Comment by foo4thought** [comment]
OK, we have spoken.  The function you want to overrride/co-opt in the current AMS is this called function proxy_files

It's in core/MY_Records_Controller.php

and looks like this:

```php
	function proxy_files($guid)
{
$proxy_guid = str_replace('/', '-', $guid);
$proxy_response = file_get_contents("http://cpbaaaccess.crawfordmedia.com/xml.php?GUID=$proxy_guid");
$x = @simplexml_load_string($proxy_response);
if (is_object($x))
{
$data = xmlObjToArr($x);
$child = $data['children'];
if (isset($data['name']) && $data['name'] == 'error')
{
return FALSE;
}
else
{
if (isset($child['mediaurl'][0]))
{
$media['url'] = $child['mediaurl'][0]['text'];
}
if (isset($child['format'][0]))
{
$media['format'] = $child['format'][0]['text'];
}
return $media;
}
}
return FALSE;
}
```

We agree that the best place to inject our data to the existing system is within this function where it fetches from the xml.php process at crawford.com

Set the $x to your XML string instead of crawford's and get out of Dodge clean.

Here's what crawford currently returns, both from a good argument and a bad one.

```bash
proxy_guid='cpb-aacip-138-74cnpdc8'
http://cpbaaaccess.crawfordmedia.com/xml.php?GUID=$proxy_guid




mylocal:~ kevin_carter$ curl -i "http://cpbaaaccess.crawfordmedia.com/xml.php?GUID=$proxy_guid"
HTTP/1.1 200 OK
Date: Tue, 17 Mar 2015 20:05:06 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powered-By: PHP/5.3.10-1ubuntu3.16
Vary: Accept-Encoding
Content-Length: 177
Content-Type: text/xml; charset=utf-8
```
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<data>
   <format>mp3</format>
   <mediaurl>http://cpbaaaccess.crawfordmedia.com/data/138/cpb-aacip-138-74cnpdc8.mp3</mediaurl>
</data> 
```
```bash
mylocal:~ kevin_carter$ proxy_guid='cpb-aacip-138-655dvb2t'
mylocal:~ kevin_carter$ curl -i "http://cpbaaaccess.crawfordmedia.com/xml.php?GUID=$proxy_guid"
HTTP/1.1 200 OK
Date: Tue, 17 Mar 2015 20:05:43 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powered-By: PHP/5.3.10-1ubuntu3.16
Vary: Accept-Encoding
Content-Length: 107
Content-Type: text/xml; charset=utf-8
```
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<error>media file for cpb-aacip-138-655dvb2t doesn't exist!</error>
```

**Comment by mccalluc** [comment]
todo: make an end-point on aa that emulates the old behavior.

**Comment by mccalluc** [comment]
(We realized that the access control we needed could only be provided by the AMS, so throwing this back to Kevin.)

**Comment by foo4thought** [comment]
The nightmare is over - for now.  BASH script now exists to generate the XML string formerly gotten from a PHP process at Crawford.  Said script depends on existence of two different identities:  mysql user 'amsread'@'localhost' and the Sony Ci user as articulated in file 'ci.yaml' located in the app's config directory.  The Sony stuff was easy; passing a token from between AMS objects was NOT.

**Comment by mccalluc** [comment]
@foo4thought: awesome. Only because I'm paranoid: the ci.yaml is not checked in, and there is an appropriate .gitignore to make sure it doesn't get checked in?

**Comment by foo4thought** [comment]
file system is cleaned up, yaml is gitignored and changes are pushed.
