### ISSUE TITLE
id duplicated in featured list

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#235]
```
- id: cpb-aacip_217-22h70wc4
  org_name: WKAR
  name: "Evening with the Governor"

- id: cpb-aacip_217-22h70wc4
  org_name: WHUT
  name: "At Howard: Julian Bond"
```

The machinery could check for duplicates... or would that be excessive?

**Comment by sroosa** [comment]
Not excessive, if it's not too much work on your end, @mccalluc

**Comment by caseyedavis12** [comment]
Are we sure that this is not an issue with the script or indexing?

I just searched for cpb-aacip_217-22h70wc4 and retrieved only one (1) record in the AMS. The record was for WKAR "Evening with the Governor."

I searched for "Julian Bond" and filtered to WHUT and retrieved three records:

cpb-aacip/293-09j3tz4m<https://ams.americanarchive.org/records/details/1443414>
cpb-aacip/293-43nvx4bj<https://ams.americanarchive.org/records/details/1443424>
cpb-aacip/293-78gf239p<https://ams.americanarchive.org/records/details/1443434>

There are no records retrieved in this search that look like cpb-aacip/217.

**Comment by sroosa** [comment]
@caseyedavis12 @mccalluc Oops, that's my fault. I was copying and pasting and forgot to copy GUID into the WHUT entry, so it was just the WKAR GUID from the entry I had copied.

**Comment by caseyedavis12** [comment]
Oh ok, so you have found 2 records with the same GUID for WKAR and another two records with a different same GUID for WHUT?

**Comment by sroosa** [comment]
@casey. No, this github issue is only for the featured thumbnails in the galleries. I just put the wrong GUID in the yml file. These have nothing to do with the GUID duplication in the AMS/AAPB as a whole.

**Comment by caseyedavis12** [comment]
Gotcha, thanks!

**Comment by mccalluc** [comment]
fixed some time ago.
