### ISSUE TITLE
Can CSS accommodate multiple <dd>s? 

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#245]
@Hammicakes : Can / should the CSS work with multiple `<dd>` elements under a single `<dt>`?  See screenshot. It'd be trivial to spit out a blank `<dt>`, which would shove over the `<dd>`... but that feels like it could be a mistake.

Thoughts?

![screen shot 2015-03-20 at 8 41 34 pm](https://cloud.githubusercontent.com/assets/730388/6762995/2c2922c2-cf42-11e4-8314-5422e23553d9.png)

```xml
<dt>Description</dt>
<dd>On Camera, Greg Alan at Farm, ...</dd>
<dd>Norman Borlaug Documentary Raw and Work Tapes</dd>
```

**Comment by mccalluc** [comment]
(`<dd>` might also be repeated for creator/contributor/publisher.)

**Comment by Hammicakes** [comment]
Shouldn't be a problem but ultimately will need to see the code

**Comment by mccalluc** [comment]
This is fixed.
