### ISSUE TITLE
reassign DNS entries.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#249]
@caseyedavis12 : With the new server setup we're doing, the DNS entries for staging and beta need to be tweaked again. (Turns out, EIPs can not be transferred between real and virtual machines, which is what we need.)

Hopefully this will be the last tweak for these:

beta.americanarchive.org: 52.0.243.127
staging.americanarchive.org: 52.0.119.89

(We do not have the servers running on these yet, but I'm comfortable with the transfer being made now, but you can wait if you want.)

**Comment by caseyedavis12** [comment]
Done

**Comment by mccalluc** [comment]
@caseyedavis12 : thanks. Closing.

(If you say "fix #249" in an email, it would close it automatically.)
