### ISSUE TITLE
Fix BL deprecations

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#254]
After gem updated we get these in the test run. Frustrating because it seems to be internal to the gem: the stacktrace doesn't reference our code.

```
DEPRECATION WARNING: Configuration is now done via blacklight.yml. Suppport for solr.yml will be removed in blacklight 6.0.0. (called from connection_config at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight.rb:81)
DEPRECATION WARNING: Configuration is now done via blacklight.yml. Suppport for solr.yml will be removed in blacklight 6.0.0. (called from connection_config at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight.rb:82)
DEPRECATION WARNING: Blacklight::Solr::Document::Email is deprecated; use Blacklight::Document::Email instead. (called from extend at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight/document/extensions.rb:27)
DEPRECATION WARNING: Blacklight::Solr::Document::Sms is deprecated; use Blacklight::Document::Sms instead. (called from extend at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight/document/extensions.rb:27)
DEPRECATION WARNING: Blacklight::Solr::Document::DublinCore is deprecated; use Blacklight::Document::DublinCore instead. (called from extend at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight/document/extensions.rb:27)
```

**Comment by cbeer** [comment]
> DEPRECATION WARNING: Configuration is now done via blacklight.yml. Suppport for solr.yml will be removed in blacklight 6.0.0. (called from connection_config at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight.rb:81)

You should rename your `./config/solr.yml` to `./config.blacklight.yml`

> DEPRECATION WARNING: Blacklight::Solr::Document::Email is deprecated; use Blacklight::Document::Email instead. (called from extend at /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p353/gems/blacklight-5.11.1/lib/blacklight/document/extensions.rb:27)

In your `SolrDocument` model, you're probably using `Blacklight::Solr::Document::Email` (and should rename it to `Blacklight::Document::Email`)

**Comment by mccalluc** [comment]
@cbeer : yep, that seems to do it. (It helps if I actually read the error messages.)

Merge coming soon...
