### ISSUE TITLE
clip reel on about page

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#267]
@sroosa, could you please add this iframe to the top of the about page (/about-the-american-archive) on the AAPB website?

```<iframe src="https://player.vimeo.com/video/108272934" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="https://vimeo.com/108272934">American Archive of Public Broadcasting: Every Picture Tells a Story</a> from <a href="https://vimeo.com/aapb">American Archive</a> on <a href="https://vimeo.com">Vimeo</a>.</p>```

**Comment by sroosa** [comment]
Chuck did this.
