### ISSUE TITLE
Vimeo Clip Reel

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#273]
@sroosa -- could you remove the ```<p>``` tag from the Vimeo HTML?
Would it be possible to center the video player?

**Comment by caseyedavis12** [comment]
@mccalluc, @sroosa  said that you would do this. 

Removing the ```<p>``` tag is higher priority. Centering is lower priority.

**Comment by mccalluc** [comment]
This is done https://github.com/WGBH/AAPB2/commit/98b516d993f13298a93729eb826ad7cfe114ee51#diff-8a85618b848f9267e569263189631a24

We are not redeploying with every commit. There are ways of doing that ("continuous integration"), but it's not something we've set up.
