### ISSUE TITLE
Smal Search in banner and right column not picking up latest styles

### ISSUE THREAD

**Issue by Hammicakes** [WGBH/AAPB2#283]
In the screen shot, local verses latest release.  The search in the banner and right column doesn't seem to be picking up on the latest CSS.

Wrong heights and magnifying glass with purple background are wrong.

![screen shot 2015-03-27 at 10 05 25 am](https://cloud.githubusercontent.com/assets/10867460/6869225/d83f70ea-d468-11e4-871d-682d1528146d.png)

**Comment by mccalluc** [comment]
fixed with latest push.
