### ISSUE TITLE
Windows user experience on homepage

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#293]
My LOC counterpart tested the website using Chrome Version 41.0.2272.101 m, Windows 7.

On the homepage, the drop-down menu next to the large search bar displayed all white text, which is only visible when you over over with the cursor. 

cid:image001.png@01D06C5E.5386E760

**Comment by caseyedavis12** [comment]
![image001](https://cloud.githubusercontent.com/assets/5992135/6941963/00f280d0-d852-11e4-8e91-97975791032b.png)

**Comment by mccalluc** [comment]
@foo4thought @afred : do either of you have privs to install Chrome on the Windows machine at the end of the row? I can log in, but I can't install anything new.

**Comment by afred** [comment]
there is also browserstack (and others), if we want to be more thorough in checking browsers on other operating systems, without having to install all combinations ourselves.

**Comment by foo4thought** [comment]
Nothing I tried worked.  The machine doesn't exist here officially - IT has provided it as a favor - so I won't file a service ticket; I'll walk over today and get what we need.



-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.
________________________________

**Comment by Muraszko** [comment]
@foo4thought @mccalluc 
Dani has a Windows laptop in her office, you can try that maybe?  I'm not sure if it's an "off-network" one though.

**Comment by mccalluc** [comment]
On macs, the system UI widgets are used for selectors. On windows, in this case, the browser takes care of rendering that menu, and in application.css we set both the background and the text to white.

```
494:
.search-query-form .input-group .search-btn {
	background-color:#FFF;
```

I'm not sure about the right direction here: we might be trying to replace the select with a div under browser control on all platforms, or we could drop the contradictory styling on windows. We might also do something as a stop-gap, and then change it for the long term.

**Comment by afred** [comment]
yeah... i'd have to see some code to have an opinion. Not sure what it would look without trying it.
