### ISSUE TITLE
UI treatment for missing descriptions?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#297]
@caseyedavis12 / @sroosa : Should there be any particular treatment for records without descriptions? 

https://ams.americanarchive.org/xml/pbcore/key/b5f3288f3c6b6274c3455ec16a2bb67a/guid/15-042rd7dg :
```xml
...
<pbcoreDescription/>
...
```

These didn't ingest on the first pass: I've fixed that, but now they'll just have a "Description" label in the UI, with nothing to follow.... which I'm happy with, but wanted to make you aware.

**Comment by caseyedavis12** [comment]
>>they'll just have a "Description" label in the UI, with nothing to follow

@mccalluc: fine with me.

Thank you.
