### ISSUE TITLE
UI: get the fields for search results

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#30]

**Comment by sroosa** [comment]
Updating this list too. Final version here:
Title(s)
Date(s)
Organization
First # of characters in the Description
Thumbnail
Availability status: Not digitized, Digitized and available on location at GBH and LOC, Digitized and available online

**Comment by mccalluc** [comment]
Close enough:
-- how to truncate description can be deferred until we have more design.
-- availability has its own bug: #75
