### ISSUE TITLE
Gallery title goes opaque on hover

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#303]
The blue background to the title text is 100% opaque on hover. Perhaps not what we want?

![screen shot 2015-04-02 at 3 04 19 pm](https://cloud.githubusercontent.com/assets/730388/6971414/53590954-d94a-11e4-95de-be5547dcaaec.png)

**Comment by Hammicakes** [comment]
That is intentional.  It provides a darker bg on hover to make the text easier to read as well as providing additional feedback to the user on hover state.

I can easily update this style if you like.

**Comment by mccalluc** [comment]
nope, looks good.
