### ISSUE TITLE
AAPB logo in Browser tab

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#306]
Can we add the AAPB logo (four square version) in the tab that appears in one's browser? (See the picture below for an example of the Open Vault logo in the browser tab.) If this is possible, I will give you the appropriate logo version to use.
![screen shot 2015-04-02 at 7 16 26 pm](https://cloud.githubusercontent.com/assets/5992135/6975665/dba5823e-d96c-11e4-8179-99e644a1bac5.png)

**Comment by mccalluc** [comment]
If you have something of exactly that resolution, great. If not, it might be as helpful to describe what you want.

**Comment by mccalluc** [comment]
fixed and deployed
