### ISSUE TITLE
UI: get the fields for details

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#31]

**Comment by sroosa** [comment]
I just realized there are a few other fields that I didn't give you before. Casey did final approval of these so, we should be done making changes now. 
Additional to what I told you before, we're going to want pbcoreIdentifiers and the availability status (which we'll build from both the presence of a Ci ID and then the rights link data we'll be adding to designate digitized asset as on-location and streaming).

**Comment by mccalluc** [comment]
@sroosa : could you paste the final list in here? Thanks!

**Comment by sroosa** [comment]
Organization
Asset Type
Media Type (video or audio)
Duration 
Title Type: Title (often multiple Title Types and Titles)
Date Type: Date (sometimes multiple Date Types and Dates)
Description
Subjects (often do not exist but sometimes they do)
Genre(s)
Creators and Creator Roles
Contributors and Contributor Roles
Publisher and Publisher Roles
Rights Information
Identifiers (asset level, not instantiation level)
Thumbnails
Availability status: Not digitized, Digitized and available on location at GBH and LOC, Digitized and available online

**Comment by mccalluc** [comment]
Organization: tested
Asset Type: tested
Media Type (video or audio): tested (actually "moving image")
Duration: tested
Title Type: tested (type and title itself)
Date Type: tested (type and date itself)
Description: tested, but unsorted. That's #33.
Subjects: tested
Genre(s): tested
Creators and Creator Roles: tested
Contributors and Contributor Roles: tested
Publisher and Publisher Roles: tested
Rights Information: tested
Identifiers (asset level, not instantiation level): TODO!
Thumbnails: Will eventually be just a splash, but we should still stub it. TODO!
Availability status: TODO!

**Comment by mccalluc** [comment]
IDs in ui and tested.
imgs in and tested.
Availability refiled as #75.
