### ISSUE TITLE
Update blog link on homepage

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#321]
@mccalluc: once we figure out the DNS record issue, we need to update the blog link on the new homepage.

**Comment by mccalluc** [comment]
(As mentioned in email, I'm a little confused by the current state of things: I'm guessing @afred tweaked the live code to point at americanarchivepb.wordpress.com, but I'm not sure.)

**Comment by afred** [comment]
@mccalluc no tweaking of live code from me.

**Comment by mccalluc** [comment]
No news here, but wanted to update with what I know:
- The links to the blog on the homepage are not something we make by hand: they come through the API.
- We are referencing "blog.americanarchive.org" in the code. (See _blog.html.erb.)
- That name is CNAMED:
```
blog.americanarchive.org. 3202	IN	CNAME	americanarchivepb.wordpress.com.
americanarchivepb.wordpress.com. 13973 IN CNAME	lb.wordpress.com.
```
- `curl -I blog.americanarchive.org` is simply unresponsive: Are they checking UAs?
- In any event, it gets redirected.

--> The problem and the fix are in WP land: the Ruby code is fine.

**Comment by afred** [comment]
i'm getting an expected response from `curl`...

```
;^) curl -I blog.americanarchive.org
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 13 May 2015 13:14:46 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Cookie
Location: http://americanarchivepb.wordpress.com/
X-ac: 1.ewr _dca
```

what is the **done when** for this? I can't remember what we decided what to change the links to.

**Comment by caseyedavis12** [comment]
We decided to change the link for the blog to news.americanarchive.org, since blog.americanarchive.org was moved permanently.

**Comment by mccalluc** [comment]
@caseyedavis12 : I'm guessing this isn't happening? Can it be closed.

Also, in the footer, there's already a link to the blog, though it's an icon. I feel uncomfortable with duplicate links. Can we get rid of the icon if you want a text link?
