### ISSUE TITLE
UI: all descriptions

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#33]
Sadie is determining order of precedence to decide on "main" description. Also determining order for display on detail page.

**Comment by sroosa** [comment]
Order for deciding "main" description.

If there is only one description, then that one is the main description.
If there is more than one description and they don't have description types, then have the first description be the main description.
If there is more than one description, and there are types, then use the following order of precedence to choose the main description:

Raw Footage Description
Element
Raw Footage
Clip Description
Clip
Segment Description
Segment
Promo Description
Promo
Episode Description
Episode
Program Description
Program
Description
Abstract
Log
Rundown
Shot List
Transcript
Series Description
Series
[Any other value]

**Comment by mccalluc** [comment]
(We're showing all the descriptions right now: worrying about precedence is a lower priority than other things.)

**Comment by mccalluc** [comment]
This seems to overlap a bit with the asset type list, which isn't a problem... but if you'd just like the same used for both, I could do that, too.

**Comment by mccalluc** [comment]
Added `description-type-map.yml` to handle this: So we get all the string normalization logic, along with reordering. Hope that's ok.
