### ISSUE TITLE
Title types

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#34]
- Sadie will supply mapping
- Sadie will supply order of precedence to determine "main" title
- display all on details (Sadie will give order to display in)
- Sadie will supply specification for which titles and how to display in search results (Probably 2 most granular)

**Comment by sroosa** [comment]
I think the mapping for this is already in the config/vocab-maps folder. If not, @mccalluc  will you let me know?

**Comment by mccalluc** [comment]
@sroosa: no: https://github.com/WGBH/AAPB2/tree/master/config/vocab-maps: It only has the asset type map. Feel free to make a PR.

**Comment by mccalluc** [comment]
Titles are being mapped, and we display them all on the item page. Tested. Not going to worry any more about this: design will handle it.
