### ISSUE TITLE
Add Player

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#343]
When we start back on development in May, Karen would like to prioritize adding the Player to the records so that we can begin making content in Ci accessible asap.

**Comment by mccalluc** [comment]
This has nothing to do with page download speed.

**Comment by caseyedavis12** [comment]
Oops, I interpreted speed label as a higher priority item.
________________________________________

**Comment by mccalluc** [comment]
@afred : drew, this blocks on having a way to deploy ci.yml to production server. Thoughts?

**Comment by afred** [comment]
@mccalluc splain?

**Comment by mccalluc** [comment]
@afred : to show the videos, it needs a ci.yml. I could just scp it to a server, but if there's a better way to do it as part deploy, that might be good to sort out. 

Thinking about it, I can make it fail gracefully (ie, just the status quo) if not configured, and the question of how to get the config out there can be handled separately.

**Comment by afred** [comment]
Ah.. "ci" as in Sony Ci... i was thinking "continuous integration", and wondering what it had to do with anything.

Deploying production config is a use case that keeps coming up. Two strategies I've considered are...
  1. Keep production config in a private git repository (Stash) and write some custom capistrano tasks to pull it down and overwrite the defaults.
  1. Set production config values using environment variables that can be specified during the deployment.... e.g. `CI_API_KEY=xyz RAILS_SECRET_KEY=pdq [...] cap deploy`. Then you could have your YAML files use `ENV['CI_API_KEY'] || "some-default-value"`. Or.. you could write some capistrano tasks to build the actual files themselves from these values. We could even use capistrano's `ask` method to prompt for required environment variables, and fail the deployment if they are invalid.

Do either of those sound sane? Other ideas?

**Comment by mccalluc** [comment]
Done. (Redeploy of config still needs some thought.)
