### ISSUE TITLE
Curating Exhibitions

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#345]
By October, AAPB staff should be able to curate a group of related materials on the website. One example is a curated exhibition on Civil Rights materials. 

We do not require that AAPB staff can login and create the exhibition ourselves. We want to be able to provide the content to Chuck or Sadie who will add it to the site.

**Comment by mccalluc** [comment]
Can you be more precise about what is required? Casey can already create pages with any text, links, and images you want.
