### ISSUE TITLE
Digitized Filter

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#346]
@mccalluc: when you return to AAPB next week, please work on fixing the digitized filter. Currently a few thousand items that are not digitized appear when one filters to digitized. We want the digitized filter to only retrieve items that have been digitized.

**Comment by mccalluc** [comment]
Done. Sorry to put this off. I was worrying about the *right* way to do it too much.

For reference:
```
browser:
  http://americanarchive.org/catalog?f[access_types][]=Digitized&per_page=100
console:
  $.grep($('a').map(function(i,el){return el.href.replace(/.*catalog\//,'')}), function(s){return s.match(/cpb/)}).join(' ')
server:
  perl -ne 'chomp; print `bundle exec ruby scripts/download_clean_ingest.rb --batch-commit --same-mount --stdout-log --skip-sitemap --just-reindex --ids $_`'
paste and repeat.
```
