### ISSUE TITLE
Digitization/Access Status not easily apparent

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#349]
We are currently using thumbnails to indicate digitization status. I don't think that this is good enough. 

We need an FAQ page or some other way to communicate that there are 2.5 million assets and only 68,000 are digitized. "Searching the Website" page should be able to communicate this but I don't think it does so effectively enough. 

We should think about how to improve user experience and understanding of what is available.

**Comment by mccalluc** [comment]
Proposal:
![screen shot 2015-05-12 at 3 07 51 pm](https://cloud.githubusercontent.com/assets/730388/7596037/c6197c34-f8b8-11e4-882a-cedb496ba6b9.png)
Make it checked by default.

... which is great for now, but down the road there will be the set of objects which are digitized but not visible. I'd suggest that the vast majority of users are not interested in the 3-way distinction: Either they can view it, or they can't. For records which are digitized but not viewable outside wgbh/loc I suggest that be presented as a note at the bottom of just that record.

Thought?

**Comment by caseyedavis12** [comment]
This sounds great to me. Can you hold off on this until next week, though? Karen, Alan and I are meeting on Thursday and Friday and will review this suggestion and other usability needs.  Will have answers on Monday.

**Comment by caseyedavis12** [comment]
see #410
