### ISSUE TITLE
Figure out how to handle dates

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#35]
sadie: We were expecting exactly one `pbcoreAssetDate`: No longer true. Figure out what we want going forward.

Sadie will supply order of precedence to determine "main" date. Search results will only show "main" date.
Details will show all date and label each. Sadie will supply display order.

**Comment by sroosa** [comment]
If there are multiple Asset dates, but no date types, then use the first date as the main date. 
If there are date types for Asset Dates, then use the following order of precedence to determine which date is the main date, as well as to determine the order the dates should be displayed in details:

broadcast
created
revised
copyright
[any other value]

**Comment by mccalluc** [comment]
fixed.
