### ISSUE TITLE
Google Search Results for "American Archive of Public Broadcasting"

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#354]
The robots.txt is no longer mentioned in the description that appears in google search results, but now it pulls the most recent blog post. 

"Check out the new AAPB website at americanarchive.org! We're thrilled to announce the launch of the American Archive of Public Broadcasting website at ..."

We would prefer that it pull from the "About the AAPB" section on the homepage, since it provides an overall description of the AAPB.

"We are a collaboration between WGBH and the Library of Congress with a long-term vision to preserve and make accessible significant historical content created by public media..."

**Comment by mccalluc** [comment]
meta tags look like the way to do this: https://support.google.com/webmasters/answer/35624?hl=en

(If anyone else is researching it, don't get confused by docs on the search appliance, which would offer you more control. That's not the boat we're in.)
