### ISSUE TITLE
Grid View of Thumbnails 

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#355]
When a user views search results in the Grid View, ten thumbnails appear per page. This causes the 10th thumbnail to appear much larger than the other thumbnails.
Perhaps a solution is to list 15 search results per page, since this would allow 3 thumbnails to appear per row.

![screen shot 2015-04-10 at 8 22 18 am](https://cloud.githubusercontent.com/assets/5992135/7087567/c0e5c190-df5a-11e4-8062-773d26475b33.png)
.

**Comment by mccalluc** [comment]
Make the window narrower and you get two columns, and unless we worked with multiples of 6 (which would be a little bizarre), you'd be in the same place. Prefer a CSS fix so last row is sized consistently.

**Comment by mccalluc** [comment]
Another idea: responsive styles accommodate 2, 4, or 5 items across, and results can be viewed 20 or 100 at a time. (we also tweak it so that last items aren't oversized.) Would that work for everyone?

**Comment by caseyedavis12** [comment]
I'd rather not just show two items across, since that may yield a lot of white space. Would displaying four items across make the page look crammed? Would displaying 20 items at a time cause the site to load slowly?

**Comment by caseyedavis12** [comment]
@Hammicakes is fixing this by taking out some of the bootstrap code.

**Comment by mccalluc** [comment]
PR #685 isn't perfect. In general, let's not close bugs at least until PRs get merged, and (sometimes) until we've seen it live, if it's particularly finicky.

**Comment by mccalluc** [comment]
Try grabbing code from #685. Check that it fixes #384 as well.

**Comment by mccalluc** [comment]
At some point we got rid of gallery view. Problem solved.
