### ISSUE TITLE
Ci Upload Script Fails with files >700MB

### ISSUE THREAD

**Issue by Muraszko** [WGBH/AAPB2#375]
Possibly related to #8 when running 
$ ruby scripts/ci/ci.rb
Files that are larger than 700MB appear to fail, the Ci web UI reports them as "Failed" and looking at the upload logs the status is reported as "Uploading" or nothing at all.

To temporarily work around this issue, with proxy files larger than 700MB I converted them with ffmpeg to a smaller file size using this bash.
```
$ ffmpeg -i /SOURCEFILE.mp4 -vcodec libx264 -crf 30 OUTPUTFILE.mp4
```

They ingest into Ci successfully after that conversion has been done.

**Comment by mccalluc** [comment]
Ci stuff got moved. Closing this.
