### ISSUE TITLE
Discuss: Facet behavior can be misleading for fields that are usually single-valued.

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#377]
@mccalluc @sroosa @caseyedavis12

For instance, the "Organization" facet. Here's an exercise that highlights the confusion:
  1. Do a search for "marathon"
  1. Open the "Organization" facets and notice that KCAW has 16 results, and KCTS has 33 results.
  1. Now click on KCAW. Notice that KCTS now has 0 results.

This is because Solr is calculating the number of records that have _both_ KCAW **AND** KCTS.

This method of faceting works great when filtering on multiple fields. For instance, if I filter on "Organization" and "Asset Type" I would expect the search to return results that match _both_ of my criteria, using **AND** (as opposed to matching _either_ of my criteria, using **OR**).

It also makes sense for truly multi-valued fields, like Genre, which an have any number of values for any single record. When I filter on "News" and "Music", I would expect to get results that satisfy _both_ of those genres.

It gets less user-friendly though, when we have a field like "Organization" or "Media Type". The common case for these fields is to only have one value -- e.g. the "Media Type" is _either_ "Moving Image" **OR** "Sound", but rarely both (if ever).

It might be worth it to see what happens if we switch to using single-valued fields for those fields that have single values most of the time. I think these would include "Organization", "Media Type", "Asset Type", and "Access".

I have not seen how Blacklight deals with this, so it would be an experiment, but it might make the facets more intuitive and useful.

I'm guessing we defaulted to multi-valued fields everywhere to stay flexible, and be able to handle those rare cases when, for instance, a record legitimately has 2 organizations. But if we can get better UI by handling the edge cases a little differently, it could be worth it.

**Comment by mccalluc** [comment]
@afred: 
- Organization *is* single-valued in the schema:
```xml
   <field name="organization" 
          type="string" indexed="true" stored="false" multiValued="false"/>
```
- I think that what we want is to be able to OR facet values which are mutually exclusive: ie find "marathon" in KCAW or KCTS, but only those two. Is this what you think is missing?
- What would the UI for this be in your mind? One possibility:
  - Click on the first station.
  - Facet list remains open; Click on the second.
  - Results are ORed: http://americanarchive.org/catalog?f[genres][]=News&f[genres][]=Call-in&f[organization][]=Minnesota+Public+Radio+%28MN%29&f[organization][]=KUSP+%28CA%29 should mean `("News" AND "Call-in") AND ("MPR" OR "KUSP")`

**Comment by mccalluc** [comment]
More research:
- There's no switch in solr to enable this: https://issues.apache.org/jira/browse/SOLR-1223
- It looks like the way to do it now is to construct a fq with ORs:
```ruby
> solr.get('select', params: {fl: 'id', fq: 'organization:"KQED (CA)" OR organization:"WGBH (MA)"'})['response']['numFound']
 => 3
2.0.0-p353 :014 > solr.get('select', params: {fl: 'id', fq: 'organization:"KQED (CA)"'})['response']['numFound']
 => 1
2.0.0-p353 :015 > solr.get('select', params: {fl: 'id', fq: 'organization:"WGBH (MA)"'})['response']['numFound']
 => 2
```
- I haven't found any suggestion that this kind of query construction is built into BL.

**Comment by afred** [comment]
in my mind, "mutually exclusive" and "single-valued" are synonymous, in the context of a given field. E.g. If Organization is single-valued, then it is mutually exclusive with itself.

I don't think we have a case were a value from one field would be mutually exclusive with a value from another field. E.g. there is never a case where we would want to return results where Genre=Music OR Organization=KQED. (At least I can't think of a case -- let me know if you can think of one).

I would expect that Blacklight has a way of dealing with single-valued. If it's true that Organization (and other fields) are single-valued within the Solr schema, perhaps there is some Blacklight config that is necessary to get the UI to treat them as such. If there is, I'm not sure how BL will handle the UI.. but we should see what BL is capable of before rolling our own.

**Comment by mccalluc** [comment]
Sorry not to write more clearly: I was addressing this suggestion:

> what happens if we switch to using single-valued fields for those fields that have single values most of the time.

and only wanted to point out that these are already single-valued in the schema. Sorry if I'm missing the point.

Posted to the mailing list: https://groups.google.com/forum/#!topic/blacklight-development/ucEylXEgbNM

**Comment by caseyedavis12** [comment]
@mccalluc: did you hear anything back from the blacklight development Google Group about using single-valued fields for those fields that have single values most of the time?

**Comment by mccalluc** [comment]
Yes: see the above link.
