### ISSUE TITLE
put a ci.yml on the server

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#378]
@Muraszko : unless you think we should create a separate ci account for it, could we put the ci.yml you've been using on the server? That, and a restart, and I think the videos will be playing.

**Comment by Muraszko** [comment]
Does it need the .yml file to playback the video?  If so then we should probably have them set up a specific website account to be used because the one I'm using has my login/user information.

**Comment by mccalluc** [comment]
Yes, it needs a yml for video playback: In order to get a temp url, it needs to talk to the Ci API. I don't see an option for adding a team member in the UI... do we reach out to the sony folks for this? Would you like to handle that?

**Comment by Muraszko** [comment]
@caseyedavis12 Could you please get that from Sony?

**Comment by caseyedavis12** [comment]
Will do. Should have this within the next couple of days.

**Comment by mccalluc** [comment]
Video plays on http://americanarchive.org/catalog/cpb-aacip_37-010p2nvv

(It should be limited to requests from within wgbh+loc... but if anyone has an outside connection, it'd be good to confirm that that's true.)

**Comment by caseyedavis12** [comment]
@mccalluc: Awesome!

This note confirms that video is playing at WGBH; however, when I try to listen to digitized audio, an error appears stating "No compatible source was found for this video."
