### ISSUE TITLE
Default search results has changed

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#382]
When I conduct a search now, the default search results page is a grid view. This has changed in the past few days. Can we switch it back to list view as default? We will want grid view as default for Curated Exhibitions (October Deliverable).

**Comment by mccalluc** [comment]
There has been no change to the code in this regard. The choice of grid vs list view does persist across sessions, and it has always done this. If it hasn't been an annoyance before now, I am very reluctant to add more patches at this point.

I would like to close this unless there's a misunderstanding on my part...

**Comment by caseyedavis12** [comment]
This does not seem to be an issue anymore.
