### ISSUE TITLE
Grid view in Safari

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#384]
When a user conducts a search in Safari, the grid view appears horizontally across the page, requiring the user to scroll left and right across the page. The thumbnails do not appear stacked in columns of three as in other browsers. 

Done when:
Search results (grid view) in Safari behaves the same way as Chrome or Firefox

**Comment by mccalluc** [comment]
Just confirmed that it's something in our local tweaks: At other institutions, gallery looks fine:
- http://searchworks.stanford.edu/?q=china&search_field=search&utf8=✓&view=gallery
- http://search.library.wisc.edu/catalog?utf8=✓&q=map&page=1&per_page=10&sort=score+desc%2C+year_sort+desc%2C+title_sort+asc&uwsystem=off&search_field=all_fields&view=grid

**Comment by mccalluc** [comment]
(It might also be good to do a blank slate install of blacklight + blacklight-gallery, just to see if the same problem presents itself even then.)

**Comment by mccalluc** [comment]
@caseyedavis12 : It's been a while since I've looked at this, but picking it up again.
