### ISSUE TITLE
Sharing record page on Facebook or other social media

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#387]
As a user or administrator, when I share the URL of a digitized asset's record page on Facebook and Twitter, I want Facebook (or other social media platform) to pull the thumbnail and part of the description for the digitized asset into the post. 
![screen shot 2015-05-08 at 9 32 27 am](https://cloud.githubusercontent.com/assets/5992135/7537238/37a87208-f565-11e4-9263-885e08e89377.png)

**Comment by caseyedavis12** [comment]
This is currently what happens when I try to share a digitized asset's record page on Facebook: 
![screen shot 2015-05-08 at 9 35 21 am](https://cloud.githubusercontent.com/assets/5992135/7537280/ae838f7a-f565-11e4-8c4c-a5cd35a71752.png)

**Comment by mccalluc** [comment]
The media server is set up to respond to requests only if the referrer is one of the sites we run. This was set up before my time so I am very reluctant to unilaterally disable it.
(More details on how FB chooses the image to thumbnail here: stackoverflow.com/questions/689295)

options:
- disable all referrer checks for AAPB: I'm not comfortable with this.
- try to determine the FB requesting UA or IP, and allow it: This might be fragile.
- have a separate (symlinked?) directory for FB thumbnails which is referenced with meta tags, but not as an img: folks could still leech off of us, but it would require more than a right click to get the image url: Seem to me like the best option, right now.

**Comment by caseyedavis12** [comment]
What is the concern about disabling referrer checks?

**Comment by mccalluc** [comment]
@afred: are you ok with turning of referer checks for aapb thumbnails? (another apache tweak.)

**Comment by afred** [comment]
@caseyedavis12 is it ok if any can grab thumbnails from AAPB site? Or did we want to make that hard?

**Comment by afred** [comment]
^^ if we don't need to be paranoid about thumbnails, then there's no need for the referrer check.

**Comment by caseyedavis12** [comment]
We don't need to be paranoid about the thumbnails.

**Comment by afred** [comment]
OK that's good. However, I'm not entirely sure how to turn off the policy for just AAPB thumbnails. It's a server wide policy the way that it's currently implemented.

I'm not crazy about the idea of trying to figure out how to put conditional logic in Apache directives based on the requested resource. And I'm not crazy about testing it.

Perhaps another reason to consider moving AAPB thumbs to Amazon S3?

**Comment by caseyedavis12** [comment]
Yes, I think that moving thumbnails to S3 is a good idea.

**Comment by caseyedavis12** [comment]
@mccalluc: can you work on moving the thumbnails to S3 this week?

**Comment by afred** [comment]
keep in mind, S3 is quite cheap, but [it's not free](http://aws.amazon.com/s3/pricing/). I think we'll stay safely in the "negligible" price area, but confirm?

**Comment by caseyedavis12** [comment]
Confirmed

**Comment by caseyedavis12** [comment]
The price being negligible is confirmed. Chuck is going to continue investigating which is the better solution.

**Comment by caseyedavis12** [comment]
This is no longer necessary, as Facebook now allows you to upload an image to accompany a link.

**Comment by caseyedavis12** [comment]
Reopening this issue. Facebook lets pages add images to links but our users will not know or care to do this. This is a request from the social media group at WGBH.

**Comment by jasoncorum** [comment]
How this is implemented will be effected by changing the ORR redirect to a popup https://github.com/WGBH/AAPB2/issues/1134

**Comment by jasoncorum** [comment]
assigning to @afred for pull request review. https://github.com/WGBH/AAPB2/pull/1233
