### ISSUE TITLE
Click-through to view content in Online Reading Room

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#392]
By October, a user will be required to click-through and acknowledge a terms and conditions (currently in review by Legal Counsel) prior to viewing or listening to the first video or audio item in their research session. This could be managed by cookies.

**Comment by mccalluc** [comment]
(modal or interstitial are both ok.)

**Comment by caseyedavis12** [comment]
@mccalluc: is this done? Last week I asked Sadie if she could provide you with an example of a PBCore record with access layer metadata so that you can complete this work. But if it is already complete, can we close?

**Comment by mccalluc** [comment]
@caseyedavis12 : There's a longer thread over at PR #423, which is not yet merged. Biggest blockers, in my view:
- We need the actual language from the lawyers.
- I worry a little about this getting in the way of search-engine bots. @afred: thoughts? Maybe just doing it in JS would be better? Or UA sniffing?

(It will do it for any record right now, but making it more selective could be hooked in later.)

**Comment by caseyedavis12** [comment]
Thanks, @mccalluc.

Language from lawyers is still in review. Let's focus on ensuring that the Rules of Use do not interfere with google's ability to crawl the site.

**Comment by mccalluc** [comment]
(Now just blocked on lawyers: If the UA matches `/spider|bot/i` we allow it.)

**Comment by mccalluc** [comment]
Deployed to demo.
