### ISSUE TITLE
Episode title/number as Title Header

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#395]
Sometimes it is problematic to use the episode title/number as the title header on a record page. See here: http://americanarchive.org/catalog/cpb-aacip_15-26m0cr6g.

Maybe it would be better to concatenate the program title followed by a colon, then the episode title for the Title Header?

**Comment by caseyedavis12** [comment]
(Or just use the program title in the Title Header)

**Comment by caseyedavis12** [comment]
Well, here is an example of a record using the Series title as the Title Header: http://americanarchive.org/catalog/cpb-aacip_46-07gqnmfv.

But in this example, there are two series titles, and the other is actually more descriptive of the content. 

How are Title Headers selected?

**Comment by sroosa** [comment]
So Episode numbers are not going to be used as Headers, unless they are mislabeled as Episode, rather than Episode Number (I already am working on a fix for this for WGBH's records, since that's a big problem for them).

**Comment by sroosa** [comment]
As for the 2 series titles, that's a problem with the AMS autofilling in things, which we've pretty much resolved,

**Comment by sroosa** [comment]
Title Headers go in order of granularity skipping Episode Number.

**Comment by mccalluc** [comment]
@caseyedavis12 : What do you want done here? For things like this, there are essentially three ways to make a change:
- Change the cataloging info.
- Change the clean-on-ingest logic. (and reingest.)
- Change the display code.

**Comment by caseyedavis12** [comment]
For now, could @sroosa update the cataloging info on this record: http://americanarchive.org/catalog/cpb-aacip_15-26m0cr6g

This record is part of the rotating gallery, so any records in the rotating gallery should look clean and accurate.

**Comment by sroosa** [comment]
Fixed in the AMS, will be reflected on website when we reingest data.
