### ISSUE TITLE
Capitalize Titles

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#396]
@sroosa: can we capitalize titles of all items in the catalog

**Comment by caseyedavis12** [comment]
@mccalluc: look into doing this programmatically. Perhaps ingest time cleanup. Call letters will need to be disregarded because we want those capitalized.

**Comment by mccalluc** [comment]
I'm going to close this: PR is merged... but note that nothing really changes until there's a reingest. If you want to reopen/refile specifically for that, feel free.
