### ISSUE TITLE
"field" in title

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#397]
There are six records for Antiques Roadshow that have "field" as the segment title. Can we fix this?

**Comment by sroosa** [comment]
I can't isolate these, can you send me GUIDs?

**Comment by caseyedavis12** [comment]
Can't send all right now, but here is an example: http://americanarchive.org/catalog/cpb-aacip_15-hx15m62g9n

**Comment by mccalluc** [comment]
@sroosa / @caseyedavis12 : Use the title links in the left sidebar: http://americanarchive.org/catalog?f[segment_titles][]=field

Then:
```
$('a[data-context-href]').each(function(key,el){console.log( el.href.replace('http://americanarchive.org/catalog/',''))})
cpb-aacip_15-jw86h4d05v
cpb-aacip_15-hq3rv0d52h
cpb-aacip_15-hx15m62g9n
cpb-aacip_15-cc0tq5rh3g
cpb-aacip_15-ns0ks6jb3b
cpb-aacip_15-qf8jd4px3r
```

**Comment by mccalluc** [comment]
I believe this is a cataloging task? Assigning to @sroosa .

**Comment by sroosa** [comment]
fixed in AMS
