### ISSUE TITLE
Default sort for search results

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#398]
We would prefer that the default search results be alphabetical by Series Title. If no Series Title exists, sort by Program Title for those assets. If a title begins with a special character such as ", please disregard. I would also like for An, The, and A disregarded in the Title alphabetization.

**Comment by caseyedavis12** [comment]
Casey will talk with alan about why he thought this was better than relevancy default.

**Comment by mccalluc** [comment]
@caseyedavis12 : any news? I strongly believe that making the default anything other than relevancy would be a mistake... but if the TF-IDF weighting needs to be tweaked, or something should change in the actual title sort, I'd be glad to know more.

(#441 does add article stripping to title sort.)

**Comment by caseyedavis12** [comment]
@mccalluc: this is included in the long email to Karen and Alan on which I am awaiting feedback.

**Comment by caseyedavis12** [comment]
I asked Alan why he preferred Title to Relevancy sort. His response: I often find that “Relevancy” sorts are not very useful. If you search the website for “civil rights” with quotes, the first two titles you get have civil rights as part of the title, but they are not listed in any particular order, as far as I can tell. There  was a series titled “Civil Rights,” produced by WGBH, that does not appear at the top of the list and may very well be more relevant that the two programs listed first. It also is very possible that a more relevant program will not have “civil rights” in the title. So I am skeptical that a “Relevancy” sort does present programs in the most relevant order.

**Comment by mccalluc** [comment]
For reference, here's how to get a list of queries from the logs:
```
grep '/catalog[?]' current/log/production.log | grep 'q=[^"&]' | head -n 100 | ruby -pne '$_.gsub!(/.*"(.*)".*/,"\\1");$_.gsub!(/.*q=([^&]*).*/,"\\1")'
```

**Comment by mccalluc** [comment]
Taking a few of these:
- WOMAN++WNED : 278 results
  - http://americanarchive.org/catalog?q=woman+wned : 1st result is the series "Woman" from WNED.
  - title sort : "1. Brother Augustine Interview/ 2. Woman's Promos"
- agriculture : 11k results
  - http://americanarchive.org/catalog?q=agriculture :  series record for "Market to Market"
  - title sort : "1. Cartography, Department of Geosciences. 2. Engineering Physics Program. 3. Agriculture Department Promo. 4. KSMU Transmitter Dedication."
- esperanto : 12 results
  - http://americanarchive.org/catalog?q=esperanto : 1st result "International group speaks Esperanto in Brattleboro"
  - title sort : "848", a talk show from WBEZ, one segment of which is about constructed languages.

I could continue, but "relevance" sort really seems to bring the more relevant results to the top, which isn't surprising. I think it would be a good idea, though, to weight titles more heavily when searching, and I've filed #465 for that. Closing.
