### ISSUE TITLE
Genres filter

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#401]
In the genre filter, only show genres in the AAPB controlled vocabularies for genre. All other genres can be placed in a Miscellaneous genre filter.

**Comment by sroosa** [comment]
So do you not want to other genres appearing in the records at all? So like on ingest, if it doesn't have an AAPB genre source, it should just replace it with "Miscellaneous?" Or do you want just in the facet?

**Comment by caseyedavis12** [comment]
We could keep the other genres in the record. This is just for the facet.

**Comment by mccalluc** [comment]
@sroosa : We need the vocab mapping file checked in?
@caseyedavis12 : While we could keep both the mapped and unmapped genre, we haven't done that for other mappings... are we sure this one needs to be a special case?

**Comment by caseyedavis12** [comment]
Didn't we do this for Asset Type, except for the "Miscellaneous" request? If combining non-controlled vocabulary genres under "miscellaneous" in the genre facet would be too time-consuming, we could disregard this component of the request. We could instead only display controlled genres in the facet.

**Comment by sroosa** [comment]
For Asset Type we changed the data after it was exported from the AMS and before it was ingested into solr, so it doesn't appear on the website. If we did it the same way, then only the Genres that are inline with our vocab would make it onto the website at all. Can we handle Genre the same way?

**Comment by sroosa** [comment]
Talked with @caseyedavis12 offline and she said that she's happy to follow what we did for Asset Type. So we should be able to proceed that way.

**Comment by mccalluc** [comment]
@sroosa:
Plain "Performance" comes up a lot: I'm going to add it to the list, but we can revisit that.

**Comment by mccalluc** [comment]
PR merged. We will revisit to split genre(?)/topic(?), once we know what to call them. Closing.
