### ISSUE TITLE
Search within Genre

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#403]
When a user conducts a search, we would like to add the ability to search within Genre.

**Comment by mccalluc** [comment]
You mean the same way we search within title or contributors? That seems odd to me: I feel like we want to be moving this towards a controlled mapped vocabulary, and in that case, a better interface is to offer a (not-too-overwhelming) list and they can find the terms that match their interests.

This requires a reindex of everything, which takes some time, so I want to be sure we're doing the right thing.

**Comment by caseyedavis12** [comment]
Good point. Yes, I agree. Perhaps we could think about providing a list somewhere on the homepage of genres available for browsing. Maybe a new section on the homepage called "Browse by Topic"? We could provide a hyperlinked list of popular topical and format genres, which if clicked could take the user to a search results page with the genre filter applied.

**Comment by mccalluc** [comment]
@caseyedavis12 : can this be closed now that #417 exists?
