### ISSUE TITLE
Add Glossary to Website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#405]
@sroosa: we need a glossary of terms for the website.

**Comment by sroosa** [comment]
Do you mean like the controlled vocabularies, or the element definitions, or what?

**Comment by caseyedavis12** [comment]
Element definitions initially.

**Comment by mccalluc** [comment]
@sroosa: Is this still in progress? (I'm not sure that I see the necessity, but whatever.)

**Comment by sroosa** [comment]
@mccalluc: @caseyedavis12 told me not to worry about it for now. So I think it's a post-October task. Do you want to keep it on the list? Maybe tag it with something indicating low priority?
