### ISSUE TITLE
Review items with years prior to 1935

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#409]
This is probably 100 items. Let's review these items to see if this year is accurate. LOW PRIORITY

**Comment by sroosa** [comment]
Changed dates that were incorrect in the AMS, and left dates that I verified were accurate.

**Comment by caseyedavis12** [comment]
@sroosa : Alan would suggest checking later early items as well. For cpb-aacip/62-4947ddbv, the program consists of two radio programs from 1947 and 1951, but it is listed as a 1942 program. cpb-aacip/80-91sf8b3f was recorded in 1944, but is listed at a 1941 program.

**Comment by sroosa** [comment]
I will check all dates up to 1950, just to be safe. I'll take care of this in the AMS, so I'm closing the ticket here, now.
