### ISSUE TITLE
Consider Browse by Topic/Format section on Homepage

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#417]
Adding this as a separate item since not completely related to focus of #403.

It would be good to add a new section to the homepage that lists hyperlinked controlled genres as a way to browse by topic or content format.

**Comment by mccalluc** [comment]
@caseyedavis12 : Would you like to get some design advice first, or should I just do something, and try not to make it too ugly?

**Comment by caseyedavis12** [comment]
Let's hold off and chat in person next week about whether you would feel comfortable implementing. I can provide detail about how we envision this to be displayed. Have a good weekend!

**Comment by mccalluc** [comment]
( @caseyedavis12 : I'll probably get free food at noon, but apart from that should be at my desk: whenever is good for you.)

**Comment by mccalluc** [comment]
@caseyedavis12 / @sroosa : Usability thoughts? I reduced the font size in the browser: Normally, this would just about fill the screen. Is it tolerable?
![screen shot 2015-05-18 at 11 47 36 am](https://cloud.githubusercontent.com/assets/730388/7684420/d323cbec-fd53-11e4-9bfe-a5cb91185101.png)

If it's ok, great... if not:
- Trim the list?
- Sub categories?
- tag cloud? (probably passé)

**Comment by caseyedavis12** [comment]
Standby…awaiting feedback from Karen and Alan.

**Comment by caseyedavis12** [comment]
This may be better suited for a page under "Research" tab than on the homepage. Any thoughts, @sroosa or @mccalluc?

**Comment by mccalluc** [comment]
- I would trust Design's judgement about usability questions before I would trust my own.
- I am not sure what problem we're trying to solve here is.
- I don't believe that burying information in static pages is likely to solve access issues.
- I think it would be really good to think about some way of testing usability alternatives. Printed out mockups and hallway testing / looking at analytics before and after / something else.
... but I don't find this so ugly that I would object to just merging as-is.

**Comment by caseyedavis12** [comment]
We would like to publish this new section on the homepage after a reindex of solr. Could you also limit the retrieved records to only items that have been digitized?

@sroosa: are there any topics or formats in the list that have not been used in your application of genre to the metadata records? If so, could you comment and list the ones that haven't been used? We can remove those from the list.

We could shorten the list by putting "Animals" into "Nature"; "Business" into "Economics". 

"News Report" and "Educational" should go into the "Format" list.

Below "Browse the Collection," could you add a sentence stating:
"This list of content formats and topics link to selected records of digitized content, arranged by broad categories. Categorization is an ongoing process, so if you do not find what you are looking for by using the browse function, consider conducting a keyword search in the search box above."

**Comment by caseyedavis12** [comment]
Two commits:

-UI stuff is its own commit (search keyword)
-Split up facet into Topic and Format

**Comment by mccalluc** [comment]
This is deployed. When/if we distinguish topic/genre (or whatever we call them) it will be tweaked, but there's nothing else to do now. closing.
