### ISSUE TITLE
UI: See actual thumbnails on results

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#42]
@Muraszko : could you give me an example of a thumnail url for AAPB?

**Comment by mccalluc** [comment]
@Muraszko : I'm going to go forward with this assumption:
- Given pbcore with ID `cpb-aacip/240-12893cp0`
- The thumbnail will be at `http://mlamedia01.wgbh.org/aapb/thumnail/cpb-aacip/240-12893cp0.jpg`

Features:
- deep folder structure rather than putting more info in filename
- just use the slash in the id as a filepath slash, rather than agreeing on an escape scheme.

The one complication of this approach is that the file to be saved is just 240-12893cp0.jpg: the ID needs to be truncated.

Sound ok?
**done when**
I've seen a thumbnail on the site, even if just on development.

**Comment by Muraszko** [comment]
That sounds good.  I'll remove the "cpb-aacip" from the filename after it's generated.

**Comment by mccalluc** [comment]
Remember that the born digital files have longer file names. Mike will shorten these up as part of ingest. For reference, see #2.

**Comment by mccalluc** [comment]
yep, I've seen thumbnails.
