### ISSUE TITLE
Search within Year

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#421]
Could we add the option of searching with year [yyyy]?

**Comment by mccalluc** [comment]
@caseyedavis12 : We already have a year facet... Like any limited vocabulary field, it doesn't feel right to make it an option on the free-text search. Talk to clarify?

**Comment by caseyedavis12** [comment]
The Library recommended this as a way to allow researchers to begin their search with a browse, instead of having to first conduct a keyword search and then limit by a year. Some researchers, like those who want to begin their research by browsing a topic or format genre, may want to begin by looking at all content created within a certain year. Do you think there is a better way to achieve this than a free-text search?

Thank you!

**Comment by mccalluc** [comment]
> begin their research by browsing a topic or format genre, may want to begin by looking at all content created within a certain year.

Right: so there is the PR for putting this browse list on the home page, and then they can limit with the year facet. Seems to be exactly what you want?

Also: Nothing is stopping anyone from just searching for a year: The results they get are almost the same as just using the year facet, only a little broader: Here's what 1977 looks like:
```
...
1974 1
1976 2
1977 2,823
1978 3
1979 1
...
```

**Comment by caseyedavis12** [comment]
Right: so there is the PR for putting this browse list on the home page, and then they can limit with the year facet. Seems to be exactly what you want?

>> I was thinking that this would be a separate way for users to begin their search. Instead of browsing by genre first, they would browse by year first.

Also: Nothing is stopping anyone from just searching for a year: The results they get are almost the same as just using the year facet, only a little broader.

Yes, good point.

This is a low priority request at the moment. Will talk more with the Library about why they think this is necessary.
