### ISSUE TITLE
Title Sort 

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#425]
Remove numbers, special characters and articles from beginning of title sort.

**Comment by caseyedavis12** [comment]
If the title is all numbers, then sort to the end.

**Comment by caseyedavis12** [comment]
@mccalluc: can you work on this issue this week?

**Comment by mccalluc** [comment]
(Note that this is an indexing change, so nothing will actually change on the site without a full reindex after the PR is merged and deployed.)

**Comment by caseyedavis12** [comment]
@mccalluc: Have we conducted full reindex since this bug was fixed? In title sort, special characters are not being ignored.

**Comment by afred** [comment]
@caseyedavis12 I would think so.. but I'll double check. Stand by.

**Comment by mccalluc** [comment]
@caseyedavis12 / @afred : Looking back at the [commit](https://github.com/WGBH/AAPB2/pull/441/files#diff-cbf5de7e2e35fbc5ad607e47a07a526dR458), I notice that it handles articles, and does some normalization that wasn't requested in the original bug, but does nothing about non-word characters at the start of the string. Here's the last page of results that begin with non-letter characters: http://americanarchive.org/catalog?f[access_types][]=all&page=1243&sort=title+asc

I've filed #946 and will close this, to help keep it clear what the work to be done is.

(@caseyedavis12 : If you're looking at a page which demonstrates a problem, please always note the url. It takes very little time, and in other cases it may be harder for use to recreate the problem.)
