### ISSUE TITLE
On-location only warning

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#426]
Casey will draft language and consider placement of new warning that will appear in October for items digitized by not available in online reading room.

**Comment by caseyedavis12** [comment]
Please note: This item has been digitized but is only available for research on location at WGBH and the Library of Congress, due to rights or other legal restrictions. For information about conducting on-location research, click here.

**Comment by mccalluc** [comment]
This duplicates #577 and is implemented in PR #643.
