### ISSUE TITLE
Separate `genre` facet 

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#427]
**done when**
  1. two new multi-valued, facetable solr fields are added to the solr schema: `topic` and `category`
  1. the `genre` solr field is removed from the schema
  1. values from `genre` have been appropriately re-assigned to corresponding `topic` and/or `category` fields

NOTE: as a migration of index data, this will involve mapping the data from the old fields to the new before removing the old field from the schema.

**Comment by afred** [comment]
@mccalluc @caseyedavis12 Is `category` suitable?

**Comment by caseyedavis12** [comment]
Hmm…topic and category sound synonymous to me.

**Comment by afred** [comment]
Maybe "style"? Or we could keep "genre", and simply add "topic"?

**Comment by caseyedavis12** [comment]
I like "genre" and "topic." Waiting to hear Karen and Alan's opinion.

**Comment by mccalluc** [comment]
@caseyedavis12 : is this still blocked on getting feedback?

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, I have a long email with requested feedback about the website out to Alan and Karen. I will ping them.

**Comment by mccalluc** [comment]
@caseyedavis12 : still blocked?

**Comment by caseyedavis12** [comment]
Still blocked. Should have an answer by mid-next week. This is part of the long email that Karen and Alan are reviewing.

**Comment by caseyedavis12** [comment]
This comment confirms that we can split <pbcoreGenre> into Genre (Format) and Topic (Topical).

**Comment by mccalluc** [comment]
Fixed by #466, which has been merged.
