### ISSUE TITLE
Proposal: provide some context when viewing exhibit results?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#432]
@caseyedavis12 : Thinking some more about the problem of providing some context when viewing an exhibit result set. What I think might be possible would be to supplement the list of facets at the top.
![screen shot 2015-05-22 at 1 24 35 pm](https://cloud.githubusercontent.com/assets/730388/7776089/5551fb72-0086-11e5-87b5-764c83922496.png)

The text there could be the first *x* characters in the description, or we could create a new field just for this.

I'm not super enthusiastic about this, but it probably wouldn't be that hard to do, either.

**Comment by caseyedavis12** [comment]
Sounds good to me! Another question is how we add the exhibition context within the metadata record for each item the exhibit. We can do this by adding the item-specific metadata in the AMS as another description, and having a descriptionType="bizarre pets exhibit".

We could have @hammicakes find a place for item contextual descriptions with the exhibit descriptionType attribute to appear in the metadata record for that asset. He could update the metadata record CSS template for items in exhibits.

We also need a notice on the metadata record that an item is part of an exhibit.

So, each individual item that is part of an exhibit should have:

-item contextual description: supplied in AMS with new descriptionType
-notice that this item is part of an exhibit: Could this appear at the top of the record like the warning that currently appears in the search results? It could say that this item is part of an exhibit on Bizarre pets. To explore this exhibit, click here.

Let me know if you need clarification.

**Comment by mccalluc** [comment]
If we could keep it clear what each issue is about, that would help immensely: This is only about a top level exhibit description which would show on search results, and whether that is even a good idea. Per item exhibit descriptions are #433. Thanks.
