### ISSUE TITLE
Proposal: provide context on individual items in exhibits

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#433]
![screen shot 2015-05-22 at 1 43 37 pm](https://cloud.githubusercontent.com/assets/730388/7776397/a8d851ea-0088-11e5-8f26-c7afe747fc0f.png)

@caseyedavis12 : This is probably a bad idea, but wanted to put it out there. Instead of just supplying a list of IDs, it could be a hash, with the value of each pair being an in-context description. Just as we add exhibit membership information on ingest, we could add more description to individual records. (Probably record it as another description, with an identifying attribute.) Then it could be shown in the results list, and/or on individual records.

(Individual record pages are state-less: It would be a really bad idea to show it differently, depending on how you got to it.)

**Comment by caseyedavis12** [comment]
Let's discuss in person next week. Happy Memorial Day weekend!

**Comment by mccalluc** [comment]
I believe the outcome of that discussion was that Casey wanted this to happen.

**Comment by caseyedavis12** [comment]
Will also get feedback from @hammicakes on this when he starts work on AAPB design round 2.
