### ISSUE TITLE
Re-deploy of AAPB website code caused issues with markdown

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#437]
After the website was redeployed, something happened with the markdown on organization pages: http://americanarchive.org/participating-orgs/1844

**Comment by mccalluc** [comment]
https://github.com/WGBH/AAPB2/commit/b235bb10 : html_safe was moved to markdowner, which would have been fine, except it didn't make it into the PR: https://github.com/WGBH/AAPB2/pull/412, so the current code is missing the html_safe in both places.
```
$ git blame lib/markdowner.rb
933cc5b8 lib/markdowner.rb     (Chuck McCallum 2015-03-19 11:54:37 -0400  7)     @@markdown.render(md_text)
```
I am confused about the history, but I'll try to get a fix in.
