### ISSUE TITLE
Proposal: strip HTML on ingest?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#439]
There are a fair number of records with raw HTML: If the ugliness of the data is a concern, maybe we should look into this?

(There's a lot of overlap between these sets: the numbers can't be added.)
- 5724: http://americanarchive.org/catalog?q=href
- 5294: http://americanarchive.org/catalog?q=div
- 7248: http://americanarchive.org/catalog?q=nbsp
- 11172: http://americanarchive.org/catalog?q=quot ("quote" stems down to this, but if the character entity shows up in the description, it probably shows up multiple times, so TF-IDF ranks it highly.)

We have lots of straight-up html, but also cases where it looks like a half-assed cleanup was done at some point: the angle-brackets might be missing but the tag names are still in place, for example.

options:
- Status quo? Maybe the links there will be useful to someone.
- Try to preserve HTML semantics / white listing. (Would really advise against this.)
- Render to text at ingest
- ... and maybe preserve `<p>` or `<div>` as line breaks in resulting text?
- Render AND do some adhoc regexes to clean up the stuff that can't render?
- Or render to text at render time? Small overhead on each page view; wouldn't require reingest; I'd feel uncomfortable with this as a long term fix, but as a trial to see if we like the result, it's not a bad approach.

(I've just been looking at the descriptions, though there are some of the same problems in [other fields](http://americanarchive.org/catalog?search_field=titles&q=nbsp) as well.)

**Comment by afred** [comment]
@foo4thought @caseyedavis12 @sroosa @mccalluc Can we check to make sure the AMS is not introducing HTML cruft into descriptions, titles, etc?

**Comment by afred** [comment]
@mccalluc Re: your options above...

Let's try to stay consistent with the expectation that title, description, et al, should contain _data without formatting_. So basically, throw all style away, excepting things that may have been intended as line breaks.

p.s. not sure what you mean by "Maybe the links there will be useful to someone."
p.p.s. [oh my](http://americanarchive.org/catalog/cpb-aacip_211-278sfngw)

**Comment by afred** [comment]
reopening until we confirm we're not adding to the problem using the AMS (see above).

**Comment by caseyedavis12** [comment]
Hmmm….the example that Drew pointed out does not have all of the html formatting when you look at the record in the AMS: https://ams.americanarchive.org/records/details/4757106

However, if you click "edit asset" and scroll down to Description field in the web form, one will see that the formatting is present.

**Comment by foo4thought** [comment]
something specific to check would be helpful, e.g., an asset number or URL

Then I can check to see where the "cruft" is introduced.



-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.
________________________________

**Comment by afred** [comment]
@foo4thought, I think we concluded that AMS isn't responsible for introducing cruft -- it's relic cruft from cut & paste jobs. Closing this one.
