### ISSUE TITLE
Captions, for everything that was originally broadcast that way.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#444]
According to Casey:
>
We will need to provide closed-captioning for materials that were originally broadcast with closed captioning. The Library has all of these files and will need to provide them to us.

@caseyedavis12 : When will we know how these will be delivered? I'm going to expect that we just get a big zip file at some point, but if there's an API that would be better.

Roadmap:
- Check in the provided SMI and SRT as fixtures.
- Confirm that they represent the same underlying data.
- Figure out the player stuff: which format works better?
- Pin down details of delivery.
- Commit changes to solr schema and ingest code to store transcript. (Everything right now is done through the PBCore object, so my first preference would be to store it in the pbcore xml, though it could also be put in as a new solr field. TBD.)
- Commit changes to display code, once we know where to pull from.
- Identify records that need reingest, and reingest them.

**Comment by caseyedavis12** [comment]
@mccalluc: We will probably receive them all as a zipped file. We may receive them from the Library or Crawford. We also may not receive all of them by October due to delayed ingest. 

We are talking with the lawyers about whether we can make a good faith effort to get as many of the files by October and just have a note on the website stating that we will be adding the rest of the closed-caption files over the course of the next few months following October 2015.

**Comment by mccalluc** [comment]
- We can deal with a zip: Probably just unzip it to a directory which is accessible during ingest.
- Potential data quality issue: The SRT looks like
```
1
00:01:08,667 --> 00:01:09,934
CKASF CI

2
00:01:09,934 --> 00:01:13,400
 WAIN SIS PALCE

3
00:01:13,400 --> 00:01:19,033
  HHILOICALIEFS

4
00:01:27,667 --> 00:01:29,267
 Betty Mae Lewis:
 WILLIAM SEWARD WOULD BRING

5
00:01:29,267 --> 00:01:31,868
 IMPORTANT PEOPLE WHO VISITED
 HIM IN WASHINGTON UP HERE.
```

- ... but there's actually a different talking head at 58 seconds.
- and what are those first lines of gibberish?
I don't think we're going to fix this: Mostly just wanted to note that there may be data quality things outside of my control.

**Comment by mccalluc** [comment]
I've verified that following the [instructions](https://github.com/videojs/video.js/blob/master/docs/guides/tracks.md) works with the sample SRTs, but if we upgrade videojs past 4.11 it [may break](https://github.com/videojs/video.js/issues/1956). I've filed #447 for this: I don't think we need to block on that.

**Comment by mccalluc** [comment]
@afred: I had made a branch with a captions controller, and was thinking of storing the captions in solr... but as I think about it now, it's really just about serving static files, and that is all unnecessary overhead. New approach: Unzip it on AWS, create a symlinked directory under `public`, and just serve it from the files directly. Does this sound ok to you?

**Comment by afred** [comment]
how hard would it be to write something to take a WebVTT string, stick it into S3, and put the S3 URL into Solr docs?

would that be more/less complicated than have a fat directory on the web machine with a bunch of files that would have to stick to some kind of naming convention

**Comment by mccalluc** [comment]
More complicated, unless I'm missing something. 
- We have to upzip the files somewhere in AWS in either case: the difference is just whether they need to be kept around, and I think the storage costs either way are negligible.
- We'll need to rely on the files adhering to some convention in either case: That's how we tell which file is which.

The S3 approach is a lot like another Ci: in which case we're talking about all the steps in that workflow:
- Keep track of the AAPB-to-S3 mapping as they are ingested.
- Pass that file to Kevin so he can do some adhoc SQL to put it in the AMS
- *or* we make the AAPB download_clean_ingest also read this file.
not impossible, but I

**Comment by caseyedavis12** [comment]
We will receive several batches of the SRT files over the course of the next several months. The files will be organized like

Folder = [guid]
-->srt_cc1.xml
-->srt_cc2.xml

Update: We will only need to provide existing closed captions for materials that are in the Online Reading Room. We do not need to provide existing closed captions for materials that are digitized but only available on location.

**Comment by afred** [comment]
@caseyedavis12 so how many things are we talking about? And do we expect it to grow?

**Comment by caseyedavis12** [comment]
@afred: There are 15,861 closed caption files out of all digitized assets. Per most recent update, we will probably only need to provide existing closed caption files for materials that are available in the Online Reading Room. Right now we have a list of 5,000 items in the Online Reading Room, but we haven't investigated which ORR items have closed caption files, and the ORR list will continue to grow. Number of closed caption files will not grow until we add a new collection to the Archive (such as NewsHour if funded).

**Comment by afred** [comment]
@caseyedavis12 so we can expect multiple SRT files per video? (looking at your description from yesterday)

**Comment by afred** [comment]
Also.. I'm pretty sure that SRT is the format (not xml), so the files would probably be named with a `.srt` extension. Right?

**Comment by caseyedavis12** [comment]
We will only want to use srt_cc1.xml, I think.

**Comment by caseyedavis12** [comment]
Yes, you're are right. They will be .srt.

**Comment by mccalluc** [comment]
@caseyedavis12 : It appears that the SRT files have been downloaded and placed on s3. Does anyone remember if they ever worked? I'm getting an error now in Chrome because of cross site security: #1005. FF is not displaying transcripts either, but there is no error message.

Going to close this since the original task of getting the transcripts has been completed.

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, I have successfully viewed captions on the website in the past. Like you, I am also not able to view captions now. In Google Chrome, I see no "cc" button in the player any more for items that have SRT files stored on S3.
