### ISSUE TITLE
schema.org markup so google will show thumbnails?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#445]
Do a little research to confirm, but I think currently the best way to get Google to show thumbnails in search results is schema.org (There used to be a separate video sitemap, but I don't think that's current.)

**done when**
We see thumbnails in Google search results.

**Comment by caseyedavis12** [comment]
Question related to #387: Will using the schema.org markup also allow for Facebook to harvest thumbnails when sharing link to a record page?

**Comment by mccalluc** [comment]
No, no relationship between the two that I can think of. FB is pushing their own opengraph metadata standard, but I'm not sure that we'd gain much from it either.

**Comment by caseyedavis12** [comment]
Is there a solution that will work for both #445 and #387? IMO - #387 is as important as #445.

**Comment by mccalluc** [comment]
If we can't let Google download the video, I'm pretty sure they won't index it as video, unless someone can point at evidence to the contrary.

Adding schema.org for its own sake doesn't get us anything. Closing.
