### ISSUE TITLE
Geoblock Reading Room content for users outside the US

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#446]
Lawyers don't want users outside the US to be able to access Reading Room media.
- Figure out GeoIP inside Ruby. (OV is doing it in Apache.)
- Non-US users shouldn't be given the EULA-click-through, since it doesn't do anything for them.
- They should go straight to the details page, but just get the splash image, and an apologetic info box, and no player.
- The `/media/xxx` URLs should also block them.

**Comment by caseyedavis12** [comment]
Casey: needs to think about policy for people in US trying to access AAPB ORR. Using a free version. Ask legal.

**Comment by mccalluc** [comment]
I think the code is in good shape, but there are policy questions. If someone claims to be in the US, and blocked, what then? I would argue for just saying "sorry, try someone else's wireless". Anything else gets really complicated. How do you know they actually are US? But your call.

For reference, here's the current test suite, with some of the odd responses: https://github.com/WGBH/AAPB2/blob/tos-click-through/spec/lib/geo_i_p_country_spec.rb

**Comment by caseyedavis12** [comment]
I'm working on this question. Will have more information by next Thursday (7/2)

**Comment by mccalluc** [comment]
My memory of this is that we decided this was the best we could do / good enough. The code is in in PR #423, and is waiting for the TOU to be finalized.

**Comment by mccalluc** [comment]
Deployed to demo. Concerns about the accuracy of *any* ip->geo mapping remain, but we have something that works.
