### ISSUE TITLE
Should text of captions be searchable?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#448]
It would require a little extra work to get captions searchable; There are also some downsides:
- Caption text may be lower quality than the rest of the metadata: There might be false matches because of misspellings.
- The whole CC text isn't shown at once: it might be inexplicable at first glance why a match was reported. (Showing matches in context with Solr isn't impossible, but it would be more work.)

If we did decide we needed this we might down weight caption text in the index.

**Comment by caseyedavis12** [comment]
Karen and Alan are leaning toward making the captions searchable. We are going to discuss and confirm next Thursday.

**Comment by caseyedavis12** [comment]
If this ever happens, it is low priority, beyond October 2015 launch of Final Website.

**Comment by caseyedavis12** [comment]
No since we got the IMLS transcripts grant. We'll eventually want to make the transcripts searchable. But that will happen within next 1 1/2 years.
