### ISSUE TITLE
Test the Open Graph metadata

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#454]
https://developers.facebook.com/tools/debug exists, but it needs the pages to be up. (Also requires a FB account, so I'll recuse myself from this.)

**Comment by caseyedavis12** [comment]
@mccalluc: can I help with this? What do you need from me?

**Comment by mccalluc** [comment]
Nothing for right now: We have not redeployed since the OG metadata was merged in, and I don't know what the process currently is for redeploying.

**Comment by caseyedavis12** [comment]
@mccalluc: I tested this functionality, and the Audio thumbnail was successfully harvested by Facebook:
![screen shot 2015-08-12 at 10 03 47 am](https://cloud.githubusercontent.com/assets/5992135/9225822/7ba00902-40d9-11e5-9f6c-1fc4175bee51.png)

But it is not working for digitized video thumbnail: 
![screen shot 2015-08-12 at 10 01 02 am](https://cloud.githubusercontent.com/assets/5992135/9225805/5675b5fa-40d9-11e5-8164-3d52efc5c0f6.png)

**Comment by caseyedavis12** [comment]
No longer necessary since Facebook allows you to upload a photo to accompany a post.

**Comment by caseyedavis12** [comment]
Reopening and related to #387

**Comment by jasoncorum** [comment]
How this is implemented will be effected by changing the ORR redirect to a popup https://github.com/WGBH/AAPB2/issues/1134

**Comment by jasoncorum** [comment]
@sroosa and @caseyedavis12 - Changing the ORR Rules to a popup fixed what I think was the primary issue behind this ticket - the redirect to the terms page. I also made some minor tweaks to add additional OG metadata. If the examples look good below, I can finish up tests and submit the PR.

Here are a few examples of posts:

<img width="503" alt="screen shot 2017-04-11 at 10 35 30 am" src="https://cloud.githubusercontent.com/assets/3814190/24915024/0675dd82-1ea4-11e7-92d3-08141759c548.png">

<img width="501" alt="screen shot 2017-04-11 at 10 40 27 am" src="https://cloud.githubusercontent.com/assets/3814190/24915029/09d6b942-1ea4-11e7-8170-6e0ecd3dfd8d.png">

<img width="502" alt="screen shot 2017-04-11 at 10 41 25 am" src="https://cloud.githubusercontent.com/assets/3814190/24915036/0e41799a-1ea4-11e7-814d-17f8d835fb80.png">

<img width="500" alt="screen shot 2017-04-11 at 10 42 21 am" src="https://cloud.githubusercontent.com/assets/3814190/24915043/1108be22-1ea4-11e7-8144-c0c03833ebda.png">

**Comment by sroosa** [comment]
@jasoncorum These look good to me! I'm especially happy the digitized video is appear as a full width image, not just a thumbnail on the side!

**Comment by caseyedavis12** [comment]
@jasoncorum amazing!

**Comment by jasoncorum** [comment]
assigning to @afred for pull request review. #1233
