### ISSUE TITLE
Weight titles more heavily in search

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#465]
There are some cases where the default relevance sort would be better if it weighted titles more heavily. (As it is, the title just goes in the bag of words along with the description and everything else.)

TODO: We need to identify more examples: For "Civil Rights", the WGBH series of the same name might come higher in the results.

**Comment by mccalluc** [comment]
Here are a few searches. A title search is essentially a normal search with an infinite weight on the title. If there were any examples where the title search *over* emphasized a particular result, that would be useful. "Well, yeah, the title of X has those terms, but it's not as good a result as Y" 

```
http://americanarchive.org/catalog?search_field=all_fields&q=vegetarian+cooking
	VEGETARIAN COOKING
	REGINA'S VEGETARIAN TABLE #707
	Vegetarian Cooking For Everyone
	Microwaves Are for Cooking 108; Vegetarian Cooking by Microwave
	Cooking Plain & Fancy
	KCTS Cooks
	Vegetarian - Who Knew # 114
titles:
	VEGETARIAN COOKING
	Vegetarian Cooking For Everyone
	Microwaves Are for Cooking 108; Vegetarian Cooking by Microwave
	Yan Can Cook 207; Vegetarian
	Meat and veggies: Meat and evolution / cooking meat / eating bugs / vegan diet / cooking vegetarian
	Cooking at the Academy 208; A Vegetarian Menu
	
http://americanarchive.org/catalog?search_field=all_fields&q=edge+of+the+world
	The Bridge At The Edge Of The World: Capitalism, The Environment, And Crossing From Crisis To Sustainability
	El Salvador The Edges of our world
	OVER THE EDGE OF THE WORLD: MAGELLANS TERRIFYING CIRCUMNAVIGATION OF THE GLOBE
	The Bridge At The Edge Of The World: Capitalism, The Environment, And Crossing From Crisis To Sustainability
	Sam Phillips 2001
	MOTORWEEK
titles:
	El Salvador The Edges of our world
	A Crack in the Edge of the World
	Over the Edge of the World
	{a series of numbered episodes from "A Crack in the edge of the world"}

http://americanarchive.org/catalog?search_field=all_fields&q=george+washington
	George Washington Williams
	George Washington's Documents
	PRESIDENTIAL VOICES: SPEAKING STYLES FROM GEORGE WASHINGTON TO GEORGE W. BUSH
	Young George Washington
	The Florida Repertory Theater is the venue for Sulgrave Manor, the ancestral home of George Washington.
	"George Washington Carver" -A Dramatic Reading by Leon Allen
	LIFE OF GEORGE WASHINGTON, THE #0
	THE GRAND IDEA: GEORGE WASHINGTONS POTOMAC AND THE RACE TO THE WEST
	George Washingtons Watch Key
	George Washington Carver	
titles:
	George Washington
	GEORGE WASHINGTON ID
	Young George Washington
	SLAVERY AT MT.VERNON
	FARMING MT.VERNON
	George Washingtons Watch Key
	George Washington's Documents
	GEORGE WASHINGTON
	LIFE OF GEORGE WASHINGTON
	
http://americanarchive.org/catalog?search_field=all_fields&q=frank+zappa
	Zappa Plays Zappa
	Frank Zappa Interview
	Frank Zappa
	2
	Frank Zappa on Censorship
	Reel # 1/2
	Reel # 2/2
	Inside Maryland/ Archive Tape # 184
	Frank Zappa
titles:	
	Frank Zappa
	Frank Zappa Interview
	Frank Zappa
	Frank Zappa on Censorship
	Frank Zappa Show Promo 1
	Frank Zappa
	The "Classical" Frank Zappa
	Zappa : Speaking Frankly on Censorship
	Frank Zappa: Performs Live at Veteran's Memorial Hall, Columbus, Ohio
```

**Comment by mccalluc** [comment]
... One additional thought: If we do go with a high weight on title, maybe we should just get rid of the separate title search? I guess the one thing the title search gives you is just the items you want... but it should be about the same as the top of a normal text+title search.

... And then should the same hold true for contributors?

**Comment by caseyedavis12** [comment]
Thanks for working on this, Chuck!

Is the weight applied to all types of title? I don't have a strong opinion on whether we should keep the title search. I think that some users will expect an ability to search titles only and they will not know that we have applied the weight to titles in the keyword search.

I think we should keep the contributor search.  When the metadata is improved, a lot of the cast will be listed in the contributor and creator fields (like the host of a program) but will not be listed in the title.

**Comment by mccalluc** [comment]
- yep, it's applied to all titles equally. (Could be possible to weight some title types more heavily, but I'd want to see solid evidence that would be useful before going down the path.)
- about contributor search. The idea would be to weight the contributor like this PR weights titles. but see #478: Maybe advanced search would be more clear?

Let's talk about direction rather than trying to sort this out here.
