### ISSUE TITLE
Do we need to make title search more obvious?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#469]
Colleague at LoC seemed to have trouble finding title search.
- Is this actually a problem? It's true there is nothing at first glance on the screen that tells you title / credits search is available.
- If there is a problem, is there a solution? Proposal below. (Not in the screen grab, but I also put hover text on it.)

![verbose-hint](https://cloud.githubusercontent.com/assets/730388/8335210/4eb852e0-1a6a-11e5-91a7-98d0b54b7b2a.png)

This is a small simple thing so we should do actual hallway tests: Grab a stranger, and give them a title search task, either on the current page, or a tweaked version. Report results below before doing anything.

**Comment by mccalluc** [comment]
... or maybe the solution is to just get rid of special searches entirely and give more weight to titles and credits? https://github.com/WGBH/AAPB2/issues/465#issuecomment-116711779

**Comment by caseyedavis12** [comment]
in favor of #478
