### ISSUE TITLE
Discuss: Metadata redundancy in list view

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#481]
There are cases where the metadata repeats itself in main title, the description, and the "program" title.

E.g. [do a search for "Kansas"](http://americanarchive.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=kansas)

Is this something the app is doing, or is this in the metadata?

Is it worth addressing?

**Comment by afred** [comment]
^^ @caseyedavis12

**Comment by caseyedavis12** [comment]
In this example, the issue in the metadata, not the web application. For now, Sadie and her interns are focusing on improving metadata for digitized assets. At some point we will address cleaning up metadata for records of non-digitized assets.

**Comment by mccalluc** [comment]
closing in favor of #482
