### ISSUE TITLE
Search by Map

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#485]
Just an image which has
- hover style for states and individual station push pins
- clicking does a facet constrained search, either to state or individual station.

Question:
- Where does it live? Is front page too long already?

TODO:
- We need a state facet. The data is clean; we just need to pull it out.

**Comment by caseyedavis12** [comment]
@mccalluc: If possible, we would like for the "click" on the station push pin to take the user to that station's page.

We would like for the map to go above the list of stations on the Participating Organizations page. Above the map, could we have a link that says "Explore list of stations" or "Explore map"?

**Comment by mccalluc** [comment]
Map is deployed; Folks are happy with it.
