### ISSUE TITLE
Many Title Headings not descriptive enough

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#497]
Right now, I believe the logic is for the most granular title to appear as the Title Heading on Search Results and Records page. Is this correct?

This causes issues when there is an Episode title that is numeric only and is not descriptive of the content, even if there is a broader series title that is descriptive but less apparent. Here is an example: http://americanarchive.org/catalog/cpb-aacip_15-959c53f470

Here is another example: http://americanarchive.org/catalog?utf8=%E2%9C%93&f%5Baccess_types%5D%5B%5D=Digitized&search_field=all_fields&q=%22evolution+of+jazz%22

Perhaps we could consider having the title header as the name of the series then a colon then the name of the program then the episode number in parenthesis. That might resolve the problem. In many cases, the series title is just as important for a user to know as the title, and the way the page is structured now, the series title is deemphasized.

For example, it would be good if the website looked for if data exists in the series field, then series plus colon plus space, then program title; if no series, then program title; etc.

**Comment by mccalluc** [comment]
I'm going to take the last comment on #508 as definitive for search results, and #560 requested that the title be removed from the details page. This has been superseded.
