### ISSUE TITLE
For same-mount check, follow symlinks

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#502]
There's actually a double symlink under the capistrano deployment, and right now the same-mount check is failing.

**Comment by mccalluc** [comment]
@afred : As I'm looking at it now, I don't see the double symlink, and unless I'm confused the solr index is actually mounted on the EC2 volume, rather than EBS

```
This code (/srv/www/aapb/releases/20150706190610/scripts/lib/mount_validator.rb)
and the solr index (/srv/www/aapb/releases/20150706190610/jetty/solr/blacklight-core/data/)
share a mount point: /
```

```
$ stat --format=%m /srv/www/aapb/releases/20150706190610/jetty/solr/blacklight-core/data/
/
```

Am I missing something?

**Comment by afred** [comment]
@mccalluc `/srv/www/aapb/releases/20150706190610/jetty/solr/blacklight-core/data/index` => `/mnt/aapb-solr/solr_index`
