### ISSUE TITLE
Getting bad rightsLink from AMS

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#504]
>
cpb-aacip/384-25k98wrb: Schema validation errors: Element '{http://www.pbcore.org/PBCore/PBCoreNamespace.html}rightsLink': This element is not expected.

**Comment by mccalluc** [comment]
Talked with Sadie: This is a cataloging issue. Reassign. Done when this and similar are fixed, and catalogers won't be making the same mistake.

**Comment by sroosa** [comment]
All done.
