### ISSUE TITLE
No videos are playing

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#506]
```
RuntimeError (Expected ["client_id", "client_secret", "password", "username", "workspace_id"] in ci credentials, not ["cli
ent_id", "client_secret", "password", "username"])
```

But really there's a process issue: What do we do so that we know if no videos are playing on the site?

**Comment by mccalluc** [comment]
@caseyedavis12 : added the missing workspace id: playing now.
@afred : any idea how the config got truncated?
all: process-wise, what do we do to make sure we can turn this around faster in the future?

**Comment by caseyedavis12** [comment]
Thank you, Chuck!

I get daily monitor reports but it only reports on the application, not the content. I should do better at manually checking the website content each morning. I check the website and AMS, but should spend a couple more minutes making sure content is viewable. Noted.

**Comment by mccalluc** [comment]
I've just added a monitor for the `media/` URLs, and am waiting to see if it works. I'm not sure right now whether it follows the redirect or not. This will also be a place we can test the geo-blocking.

I'll follow-up here if I get it working.

**Comment by afred** [comment]
@mccalluc the `workspace_id` is not part of the `ci.yml` file that is checked in to the `aapb_deployment` repo.

Don't remember where I grabbed that version of `ci.yml`, but it must have not been from production if `workspace_id` was there.

**Comment by afred** [comment]
^^ I'll add it now

**Comment by afred** [comment]
:+1: for monitoring, thanks @mccalluc

**Comment by mccalluc** [comment]
This was a configuration problem. Tweaked on live and hit restart.txt. Filed #507 for improved monitoring. Drew config in atlas: https://atlas.wgbh.org/stash/projects/MLA/repos/aapb_deployment/commits/f948480dcdd76e53b1acfedaaefe224766bbf3a2
