### ISSUE TITLE
Clarify design and implement exhibits index page

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#517]
@caseyedavis12 will clarify what the exhibits list page should look like.

Things to consider:
- Do all exhibits get listed? In an indented hierarchy? Or just the top level ones?
- Does any info about the contained items appear? (count?)
- Can we use the same summary for each that would occur on a constrained search page? (I hope so.)
- What order?
- Do we use the same sidebar as the "about" pages? Something different? Nothing?
- Does anything else go on this page? Header? sub headers?

I have some deep trepidation about just making it look like a search results page, because people will expect it to work like a search results page. On the other hand, if that's what we want, it wouldn't be impossible to make records from the exhibits, and I would much prefer that to getting successive requests to make it work more and more like a search results page. What you would lose then is the chance to treat the hierarchy of exhibits specially, or anything else that is particular to them.

**Comment by caseyedavis12** [comment]
o	Show all exhibits? In an indented heirarchy or just top level ones?
Show all exhibits. Just the top-level ones.
o	Does any info about the contained items appear (count?)
No
o	Do we display just Title or Summary?
Display Signature Image, Title, and possibly a one sentence summary
o	List view or grid view?
We would like this to be a grid view, but are wondering if @Hammicakes can increase the size of the images in the grid for the Curated Exhibits list page.
o	What order?
Alphabetically
o	Do we use the same sidebar as the "about" pages? Something different? Nothing?
Yes, keep the "about" sidebar, but if possible please add "Home" to the side bar.
o	Does anything else go on this page? Header? Subheaders?
No, but we're stil thinking of what to call the page.
