### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#530]
Three users have told me the following:
1) that they would like to see more than 10 titles appear in the search results
2) that they usually change the default to display 100 titles
3) the page then loads very slowly due to all of the thumbnails
4) they would rather just see all search results in one page, without having to scroll from page to page and without the thumbnail.

Is there a way that we can accommodate users who just want to see a list of search results without thumbnails and without having to scroll from page to page?

**Comment by mccalluc** [comment]
- Infinite scroll: Look at what Anthony did for stock-sales-take-1.
- Get rid of n-at-a-time option.
- Leave images: if only 10 at a time are loaded, we shouldn't have the same problem. (If we do, try CNAMES.)
- Leave an option to get next page of results for users who might not have js.

**Comment by mccalluc** [comment]
Implemented... but noticed that it's buggy: sometimes the last row gets loaded again and again. Filed #713

@caseyedavis12 : This is only on gallery -- Compare with regular and image google searches.
