### ISSUE TITLE
Proxies accessible in AMS but not on website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#535]
I have come across a couple of proxy files that are accessible in the AMS, have a Sony Ci ID, but are not available on the website. Both are from the same station (WYSO).

On the website, the audio thumbnail does not appear and neither does the player.

Example: 
AMS: https://ams.americanarchive.org/records/details/4893231
Website: http://americanarchive.org/catalog/cpb-aacip_27-nk3610w92h

AMS: https://ams.americanarchive.org/records/details/4893247
Website: http://americanarchive.org/catalog/cpb-aacip_27-kk9474784d

@sroosa @mccalluc  @foo4thought any ideas?

**Comment by caseyedavis12** [comment]
@sroosa @mccalluc @foo4thought: I think I know why this is happening. The media type for these assets is indicated as "other." It should be "audio." This should fix the issue.

**Comment by sroosa** [comment]
@caseyedavis12 I fixed the instantiationMediaTypes for those two assets. Do I need to fix anymore before I close this issue?

**Comment by mccalluc** [comment]
If we could keep this open until the two examples, at least, are working. Maybe a reingest will take care of it...

**Comment by caseyedavis12** [comment]
@sroosa: Alan came across two more than have the same issue:

cpb-aacip/27-rn3028q08x 
cpb-aacip/27-kp7tm72d66

These should both be "audio."

**Comment by mccalluc** [comment]
Is there a general problem here, of which these are only examples? When is it not ok for things to be "other"?

**Comment by mccalluc** [comment]
Chuck will collect all digitized "other"s, then talk with Sadie to identify a pattern.

**Comment by mccalluc** [comment]
@sroosa: http://americanarchive.org/catalog?q=access_types%3ADigitized+-media_type%3A*
5600 records, all different stations. Have fun?

**Comment by mccalluc** [comment]
@sroosa: Is this issue still outstanding, or could it be closed?

**Comment by sroosa** [comment]
@mccalluc It's still an issue, I think. It's pretty widespread, so I'm trying to figure out if there's a way to handle it programmatically, rather than me manually cataloging.

**Comment by caseyedavis12** [comment]
@mccalluc: Can we close this since all "other" will default to audio player?

**Comment by mccalluc** [comment]
I'm ok closing: Note that, if the metadata doesn't say it's audio, it still won't come up under the audio facet. If you want audio applied as a default when we don't know the media type, file new bug.

@sroosa: ok with this?

**Comment by sroosa** [comment]
@mccalluc I'm okay closing this.
