### ISSUE TITLE
Remove jetty, and put solr config into a solr_config directory.

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#537]
**Reasoning:** there is now a deployment scripts to fetch a fresh copy of jetty (from blacklight-jetty), so the only thing needed in the web app repo is the config specific to the web app.. which is just `solrconfig.xml` and `schema.xml`.

**Done when**
  1. extraneous jetty files are all removed from revision.
  1. relevant solr config is moved to a `solr_config` dir.

**Comment by mccalluc** [comment]
Fixed by #538.
