### ISSUE TITLE
update assets in homepage featured gallery

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#539]

**Comment by sroosa** [comment]
close by #563

**Comment by mccalluc** [comment]
Let's keep things open at least until they are merged, possibly until we see it on the live site, depending on the level of uncertainty. I don't want us to think we're farther along than we are. (Including "Fix #{bug number}" will close it automatically on merge.)

**Comment by mccalluc** [comment]
@sroosa : FYI:
All the images are on S3, but there's an ACL problem:
- This doesn't work:  https://s3.amazonaws.com/americanarchive.org/featured/cpb-aacip_235-870vv6wr_gallery.jpg
- and images are broken in the carousel
- but it is listed in the S3 console, and can be linked from there. (longer, signed url.)

Investigating...

**Comment by mccalluc** [comment]
Selected all items, "Actions" > "Make Public": Carousel now has images.
