### ISSUE TITLE
Organization links in AMS and in PBCore export

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#548]
- @caseyedavis12 will deliver a 2 column CSV to @foo4thought with AAPB ID and the links MPR wants.
- Get the data into the AMS.
- Exported in PBCore. Could be anywhere, but I'll expect:
```xml
<pbcoreAnnotation annotationType='Outside URL'>http://example.org/something</pbcoreAnnotation>
```
- Ingest and make sure it works.
(This will support the UI work in #536.)

**Comment by mccalluc** [comment]
@caseyedavis12 : Any progress?

**Comment by caseyedavis12** [comment]
@mccalluc: Kyle at MPR is working on providing us with an updated csv that includes the links as a new column. I will then coordinate with @foo4thought and @sroosa on inserting these URLs into the database.

**Comment by caseyedavis12** [comment]
@mccalluc: I haven't received MPR's metadata pointing to the external streaming audio yet, but since we have figured out this workflow, can I close this?

**Comment by mccalluc** [comment]
Closing. (You might open a new bug for your self just to keep in mind that we're still waiting on MPR, but your call.)
