### ISSUE TITLE
See "Private" "Level of User Access" in action

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#574]
@sroosa : If we're planning to depend on the private status (ie interviews with private individuals which are not clear for viewing even on site), we need to make sure it works. The code is looking for the string "Private" right now: When you have an example record on the AMS, let me know so that I can be confident that this works.

pb_core.rb:
```ruby
  def private? # AKA not even on site
    access_level == 'Private' # TODO: Confirm that this is the right string.
  end
```

**Comment by caseyedavis12** [comment]
@mccalluc: In the 'Access' facet, will Private be included in 'All Records' ?

**Comment by mccalluc** [comment]
@caseyedavis12 : yep: My understanding is that there's nothing secret about the metadata, it's just the media which we we should not allow access to.

**Comment by caseyedavis12** [comment]
@mccalluc: +1

**Comment by sroosa** [comment]
@mccalluc Did I send you an example xml record, with Annotation = Private? I'm sending one now, just in case.

**Comment by mccalluc** [comment]
`ruby scripts/download_clean_ingest.rb --stdout-log --skip-sitemap --same-mount --ids 384-032281wq`
- It shows up only under "all",
- and on the details page, it says it is only available at LoC.
