### ISSUE TITLE
Enforce some access_level for outside_url media

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#576]
Am I correct in thinking that all records with @annotationType="Outside URL" count as ORR for purposes of filtering? If this is the case, I would like to enforce consistency during ingest. I would lean towards requiring "Outside URL" records to also have "Online Reading Room" for "Level of User Access". Non conforming records will be rejected. OK? @sroosa / @caseyedavis12

**Comment by caseyedavis12** [comment]
@mccalluc: +1
________________________________
