### ISSUE TITLE
Staff photos CSS

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#596]
- @sroosa will get photos for the staff page
- Once there are images, apply CSS from #583 to make them circles.

**Comment by sroosa** [comment]
@mccalluc: Is there already a designated place I'm supposed to put the image files for this?

**Comment by sroosa** [comment]
@mccalluc: I uploaded two images to test this. I'm going to add them to the md page, so they will render there? And then you can apply the css to make them circles? Is that the best approach?

**Comment by mccalluc** [comment]
@sroosa: Yep: that all sounds good: make your MD edits in a branch, and I'll add the CSS before merging. Thanks.

**Comment by mccalluc** [comment]
Fixed by #602.
