### ISSUE TITLE
Default selection of access_level facet not applied consistently

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#601]
**To reproduce:**
  1. Start with clean index, and ingest fixtures according to README
  1. Click on search button without entering a search string.

  This will bring up the advanced search interface. Under the Media Type facet, you can see there are 7 records: 6 Moving Image, 1 Sound.

  1. Click on "Moving Image" facet, and suddenly it drops to 1 result. I _think_ this is b/c the access_level facet is now being applied, whereas it wasn't being applied when you first land on the page.

**The problem:**
  1. The default selection for access_level facet was not selected when I landed on the advanced search page, after doing an empty search. Not sure what the behavior _should_ be here, but I would think we would still want the default access_level selected.
  1. The default selection for access_level was applied after I clicked on a different, unrelated facet. This is confusing. Facet selections should stay the same when you click on a different facet.

**Done when**
  1. Default selection for Access Level is applied consistently when you come to the search page.
  1. Access Level selection (or non-selection) remains unchanged after clicking on a different facet.

**Comment by mccalluc** [comment]
> Not sure what the behavior should be here, but I would think we would still want the default access_level selected.

I agree, but I'm not sure how hard that would be: We're using the Blacklight special view which is triggered when there are no query params: Not sure how hard it would be to get it to apply when there are no params *except* for `access_types`

> The default selection for access_level was applied after I clicked on a different, unrelated facet. This is confusing.

This is coming from catalog_controller.rb:
```ruby
    elsif !actual_params.empty? && (!params[:f] || !params[:f][:access_types])
      # missing access_types:
      redirect_to "/catalog?#{params.except(:action, :controller).to_query}&f[access_types][]=#{PBCore::PUBLIC_ACCESS}"
    else
```

The idea is that `PUBLIC_ACCESS` is the default if no other access_type is specified. If we made sure every link that's out there includes this facet, then the redirect isn't necessary... I guess it just feels DRYer to have a redirect in one place, than to make sure every query link on the site includes this parameter. (orgs list, exhibits, front-page browse, probably others I'm not thinking of...)

I'll see if I can get advanced search to come up even with a param, and if that fails consider a different approach.

**Comment by afred** [comment]
@mccalluc maybe track facets' on/off values in the session?
