### ISSUE TITLE
"About" menu on demo.americanarchive.org

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#609]
On demo.americanarchive.org, if a user is on one of the "About" pages, the current selected page appears at the top of the "About" menu. I think it would be best if the current selected page stays in the same position on the "About" menu, and it is just highlighted purple when it is selected. 

Do others agree?

**Comment by mccalluc** [comment]
@Hammicakes : thoughts?

**Comment by mccalluc** [comment]
I'm comfortable with the status quo: If it was more of an application where the menu stayed at the same place on the screen, then highlighting the one we're on in the middle of the list would make sense... But as it is, I don't think we need to overemphasize that you're on topic 3, or whatever.

But if Mike thinks it's worth revisiting, I wouldn't object, either. Assigning.

**Comment by mccalluc** [comment]
@caseyedavis12 : I'm going to close this, but if you want to reopen, feel free. A decision just needs to be made.
