### ISSUE TITLE
Add "Exhibits" to "About" menu 

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#610]
Please add "Exhibits" to the "About" menu below "History" when exhibits are launched.

**Comment by afred** [comment]
@caseyedavis12 do you mean you want to add it to the left-menu on this page, just below "History"?

![image](https://cloud.githubusercontent.com/assets/1507490/11068825/334c8dce-87a1-11e5-9161-a37bfe18b25c.png)

**Comment by caseyedavis12** [comment]
@afred: yes
