### ISSUE TITLE
NAEB infrastructure

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#652]
- new dots on map (specified by Casie)
- `states.yml` which lets us supply an extra blurb at the top the state section.
- If there is only a blurb, but with no actual stations, do not show the 'show all' link in the upper right.
- Casie will supply the text for the blurb.

**Comment by caseyedavis12** [comment]
@mccalluc @sroosa: Here is the text for the blurb:

Audio content from [state] is part of the National Association of Educational Broadcasters (NAEB) collection, contributed by the University of Maryland to the AAPB. 

The NAEB was established in 1934 from a precursor organization that formed in 1925. In 1951, NAEB established a tape duplication exchange system in Urbana, IL, where programs produced by university radio stations across the country were copied and distributed to member stations, an early networking scheme that influenced the history of later public radio and television systems. The more than 5,500 NAEB programs available in the AAPB come from the 1950s and 1960s, and include radio documentaries, coverage of events (hearings, meetings, conferences, and seminars), interviews, debates, and lectures on public affairs topics such as civil rights, foreign affairs, health, politics, education, and broadcasting.

The states and their constrained searches include:
State: Kansas 
Text to appear: KANU, University of Kansas
Constrained search: "U. of Kansas"

State: North Dakota
Text to appear: KFJM, University of North Dakota
Constrained search: "KFJM"

State: South Dakota
Text to appear: KUSD, University of South Dakota
Constrained search: "KUSD"

State: Alabama
Text to appear: WUOA, University of Alabama
Constrained search: "WUOA"
