### ISSUE TITLE
Ability to cite records in AAPB: low priority

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#688]
It would be great if we could provide citations for AAPB records like we do on Open Vault. Here is an example: http://openvault.wgbh.org/catalog/wpna-bdd52a-interview-with-james-abrahamson-1987

Instead of "WGBH Media Library & Archives," the AAPB collection should be acknowledged as follows: [name of Contributing organization], American Archive of Public Broadcasting (WGBH and the Library of Congress), Boston, MA and Washington, DC.

If time permits before the October launch, great. If not, that's totally fine.

**Comment by mccalluc** [comment]
- A citation requires a title, and my impression is that we gave up on finding a single best title, instead just glomming everything together with semi-colons. Is that what should be used?
- Where should it go? (Perhaps the bottom of the page?)
- Is the same button idiom appropriate?

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, it would need to include the Title (all titles separated by semi-colons like on search results), date, if it exists, and URL to the record. Open Vault provides MLA, Chicago, and APA formatting.


The bottom up the page sounds good.

Perhaps we could use the small purple button that currently appears to "view all items in this exhibit" (the button that we used prior to the new graphic that Hammicakes created.
