### ISSUE TITLE
Captions just not showing up

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#699]
I felt like when I had stubbed out captions before I had at least gotten something on the screen, but now I'm not even able to do that. Have tried both 
- SRT from LoC and 
- VTT that works for other demos on the web.

 In the browser console, I can see that the request for the caption file is working, but it never shows up in the player. If it were a cross site security problem, it shouldn't be loading at all.

Strategy: start with a plain VideoJS player just on local html and see if that works.

**Comment by mccalluc** [comment]
D'oh: same-origin-policy: https://github.com/videojs/video.js/blob/master/docs/guides/tracks.md#subtitles-from-another-domain

Solutions:
- S3 can do CORS (A), I believe ...
- Or we can set up a subdomain for media.americanarchive.org and either
  - CNAME -> s3.amazonaws.com (B)
  - Enable S3 website hosting and then set the CNAME accordingly (C)

@afred / @caseyedavis12 : I think (B) is the simplest, but no strong preferences: Let me know if you have a preference.

**Comment by mccalluc** [comment]
@caseyedavis12 : could you delete the DNS record we just created, and instead:

`media1.americanarchive.org` -> `americanarchive.org.s3-website-us-east-1.amazonaws.com` 

(This works right now: http://americanarchive.org.s3-website-us-east-1.amazonaws.com/captions/cpb-aacip-322-03cz8wl6/cpb-aacip-322-03cz8wl6.srt1.srt)

**Comment by mccalluc** [comment]
@caseyedavis12 : I gave you the wrong information. Hopefully I've got it right this time:

`captions0.americanarchive.org` -> `captions0.americanarchive.org.s3-website-us-east-1.amazonaws.com`

(I've needed to set up a new bucket so that the host name matches the bucket name.)

**Comment by afred** [comment]
@mccalluc with the bucket-name the same as the subdomain of the CNAME, do you still need "website hosting" enabled?

**Comment by caseyedavis12** [comment]
@mccalluc: done

**Comment by mccalluc** [comment]
Thanks! upload and download work, just need to integrate with site now.
```
$ aws s3 cp ~/Downloads/ccExport.2 s3://captions0.americanarchive.org/ \
   --recursive --exclude '*' --include '*.srt1.srt' --acl public-read
$ curl http://captions0.americanarchive.org/cpb-aacip-322-03cz8wl6/cpb-aacip-322-03cz8wl6.srt1.srt
```

**Comment by afred** [comment]
@mccalluc did you look at [these docs for enabling CORS on S3](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors)?

If we bump into this more often in the future, this may be a more maintainable way, rather than adding CNAMES that match bucket names.

**Comment by mccalluc** [comment]
@afred: good call. In the end, same-origin is stricter than I remember: We could get it working that way... but there are a lot more hoops. I've just set CORS on the americanarchive.org bucket:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```
could be tighter, or could turn on caching, but I think this is good for now.
@caseyedavis12 : The extra CNAMES can be deleted: not using them after all.
