### ISSUE TITLE
Facet shows records from other orgs when viewing all records from one org

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#702]
If you go to the organization page and click on “View All Records” for the University of Maryland, you get 6,358 digitized records. But under “Limit your search” on the results page, many records from other organizations are included. For example, 2,228 records are listed for KQED. This is confusing. It implies that of the 6,358 UMD records, you can limit it to 2,228 records that also are KQED records, but this is not true. We have a total of 2,228 digitized records from KQED in the whole collection.

**Comment by mccalluc** [comment]
@caseyedavis12: Feature, not a bug. :)

```ruby
config.add_facet_field 'organization', ... tag: 'org', ex: 'org,state',
```
which goes back to c136aab0. At that point, the idea was that we wanted people to be able to select multiple institutions, yada yada....

--> We'll try some css to hide the numbers on that facet: it's just too much information, and alternatives, like listing all zeros isn't any better.
