### ISSUE TITLE
Advanced Search confusion

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#703]
On the advanced search page, if you enter “Frank Lloyd Wright” in the “All these words” box and “National Association of Educational Broadcasters” in the “This exact word or phrase” box, you get 21 digitized records, but there are only 3 NAEB records of programs with Wright. Not sure why the search retrieves 21, including records from stations like WILL and Wisconsin Public Television that do not contain the exact phrase "National Association of Educational Broadcasters."

**Comment by mccalluc** [comment]
Good catch. For background [lucidworks](https://lucidworks.com/blog/why-not-and-or-and-not/) is a good read. For us the part that matters is the idea that there are three different levels indicated by prefixes:
- `+`: Must
- (blank): Should
- `-`: Must not

So, the way advanced queries are constructed now, there are no prefixes, so as long as one term matches it is included in the result set. What we want instead is [`+Frank +Lloyd +Wright +"National Association of Educational Broadcasters"`](http://americanarchive.org/catalog?utf8=%E2%9C%93&f[access_types][]=digitized&q=%2BFrank+%2BLloyd+%2BWright+%2B%22National+Association+of+Educational+Broadcasters%22) which produces exactly three results.

Fix in the works...

**Comment by mccalluc** [comment]
Of course, it's not that simple:
- `+frank +lloyd +wright` : 18 digitized
- `frank AND lloyd AND wright` : 18, which makes sense
- `+franks +lloyding +wrightly` : 18, ie, it is stemmed
- `frank lloyd wright` : 25
- `franks lloyding wrightly`: 25

but OR does something different:
- `(frank  OR lloyd) wright` : 686
- `frank OR (lloyd  wright)` : 686
- `frank OR lloyd OR wright`: 686

and if you want more edge cases:
- `(frank lloyd wright) AND -(+frank +lloyd +wright)` : 686
- `(frank lloyd wright) AND NOT (+frank +lloyd +wright)`: 686
- `(frank lloyd wright)  NOT (+frank +lloyd +wright)`: 686
- `(frank lloyd wright)  -(+frank +lloyd +wright)`: 686

but:
- `(frank lloyd wright)  -frank -lloyd -wright` : 0
- `(frank lloyd wright)  -"frank lloyd wright"` : 670

The blog post above as much as says these should be equivalent:

> (X Y) … Disjunction, ie: (X ∨ Y)

but for us something is quite different between "A B" and "A OR B"...
