### ISSUE TITLE
add executive advisory council page to footer and sidebar menus

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#704]
@caseyedavis12  where do you want this in the order? @mccalluc I don't know how to add it to the sidebar, can you show me or do it?

**Comment by caseyedavis12** [comment]
@sroosa @mccalluc:

Footer: move Staff to below History. Put Executive Advisory Council above Acknowledgements

Sidebar: Put Executive Advisory Council above Acknowledgements

Sent from my phone while I have no wireless internet
________________________________

**Comment by sroosa** [comment]
@mccalluc - I just added a link to the page to the footer. So all that's left is putting it in the sidebar on the about pages.

**Comment by mccalluc** [comment]
fixed.
