### ISSUE TITLE
Homepage on mobile

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#708]
I think that @hammicakes is still working on the Browse the Collection design/buttons for the mobile version of the site. But I just noticed that the map no longer appears on mobile. It is just a blank section that continues down the page and is very long. The map worked fine on mobile before the previous redeploy.

**Comment by mccalluc** [comment]
@caseyedavis12 : I can't replicate your problem: I've tried Chrome and FF at a variety of widths and it's always there. Let's talk.

**Comment by mccalluc** [comment]
replaced by #710
