### ISSUE TITLE
Linking out to WGBH records

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#719]
Is there any way we could have the text of the link out to WGBH Open Vault say "View Online at WGBH Open Vault"? And have Boston Local TV News records say "View Online at Boston Local TV News Digital Library"? I understand that this will require customization. Since we will only have a few organizations doing this, we won't need much customization. I just think that the link that says "View at WGBH" may not communicate to users well enough that if they click the link, they will be taken to view the media online at Open Vault.

PS thank you for implementing this so quickly!!

**Comment by mccalluc** [comment]
Heard from Sadie that this will be sufficient:
> View online at WGBH.

or
> Listen online at WGBH.
