### ISSUE TITLE
add images to static pages

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#720]

**Comment by sroosa** [comment]
Currently waiting on the Library for their images

**Comment by caseyedavis12** [comment]
@sroosa: Karen and I are talking with Alan about this tomorrow. More updates tomorrow.

**Comment by mccalluc** [comment]
@sroosa: Looking at your branch: Probably better to drop the `<br>` and just leave a blank line between. Or an image tag with a pull left is another possibility.
```
## American Archive of Public Broadcasting National Digital Stewardship Residency Project
![AAPB NDSR](https://s3.amazonaws.com/americanarchive.org/org-logos/aapb_ndsr_logo.png)

The Institute of Museum and Library Services (IMLS) Laura Bush 21st Century Librarian Grant
```

![screen shot 2015-09-16 at 12 07 14 pm](https://cloud.githubusercontent.com/assets/730388/9910566/a49b561a-5c6b-11e5-8e1f-dd9708f1b62c.png)

**Comment by mccalluc** [comment]
@sroosa: Is this on-going? If there will be more images, should the text wrap around them? Trying to decide what the default should be.

**Comment by caseyedavis12** [comment]
@sroosa Would be good to add screenshots on "Searching the Website" page.

**Comment by sroosa** [comment]
@caseyedavis12  Sure! I can add screenshots. Do you need me to take them too? Or do you already have images you want to use? 
@mccalluc After these screenshots that should be it for this bug. I'll close then.

**Comment by caseyedavis12** [comment]
Done
