### ISSUE TITLE
Fix Blacklight deprecation warnings

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#725]
**Done when:**
The following warning does not appear during app initialization:
```
DEPRECATION WARNING: solr_search_params_logic is deprecated and will be removed from blacklight 6.0 (use search_params_logic instead). (called from block in <module:ControllerOverride> at /Users/andrew_myers/.rvm/gems/ruby-2.0.0-p353/gems/blacklight_range_limit-5.1.0/lib/blacklight_range_limit/controller_override.rb:11)

```

**Comment by mccalluc** [comment]
We started getting these when we brought in the range-limit widget: Probably make the most sense to fix it upstream...

**Comment by afred** [comment]
:+1: just confirmed we don't call `solr_search_params_logic` anywhere. Closing.
