### ISSUE TITLE
Wrap text around images on About pages

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#746]
When images are included within the text on the about/projects and about/funding pages, please wrap text around the images.

**Comment by mccalluc** [comment]
@caseyedavis12 : What about http://americanarchive.org/on-location ? If the default should be to wrap, I'll handle it one way, but if these are the special cases, I'll just put in `img` tags.

**Comment by caseyedavis12** [comment]
@mccalluc: yes, wrapping on default is good.
