### ISSUE TITLE
Clip reel not playing on demo site

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#747]
See img below.

@caseyedavis12 does Vimeo have a setting for entering hosts on which you may embed a video? If so, the this probably isn't a bug.

![image](https://cloud.githubusercontent.com/assets/1507490/10371010/60900ad8-6daf-11e5-84c1-ce9d7646ba14.png)

**Comment by caseyedavis12** [comment]
@afred: the video is restricted to play only on the domain americanarhive.org, so this issue can be closed.
