### ISSUE TITLE
Remind me how availability is determined?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#75]
@sroosa : Could you remind me? It should go on search results and details. Would it be ok to wait until we've confirmed that the information flow through the AMS is what we think we is? It's just complicated enough that I could imagine the details changing by the time we actually had supporting data.

**Comment by sroosa** [comment]
Yes. I'm fine waiting until we confirm the information flow. For reference, there are three levels of availability (or access). 
1. Streaming on the site. 
2. Digitized, but only available on location. 
3. Not digitized. 

We differentiate 1 and 2 from 3 by the presence of a Ci ID. And we use some code that we have yet to implement in the pbcorerightssummary field to differentiate 1 from 2.

**Comment by caseyedavis12** [comment]
For future understanding of the metadata among human catalogers and developers, I would prefer creating a separate annotation or rights summary that indicates whether the content falls within 1,2, or 3. The presence of a Ci ID may not clearly indicate to future catalogers and developers that the content is digitized. Also, if we one day move away from Ci, then that ID will become obsolete, and we will need to find another way to indicate that something was digitized.

**Comment by sroosa** [comment]
I don't mind having the non-digitized information somewhere else, so that we're not relying on the Ci id; however, I think that a single annotation or rights summary for all of this conflates two different types of information, and I would like to keep them separate. So there is information about whether something is digitized or not. Then there is information about level of access. 
I'm fine with this information conflated in the facet on the website, but I don't think it should be conflated in the pbcore.

**Comment by caseyedavis12** [comment]
@sroosa , what about <pbcoreAnnotation source="digitization status">Digitized</pbcoreAnnotation>
<pbcoreAnnotation source="digitization status">Not Digitized</pbcoreAnnotation>

For Availability Status, if it is digitized:

<pbcoreAnnotation source="availability">Website</pbcoreAnnotation>
<pbcoreAnnotation source="availability">On Location</pbcoreAnnotation>

**Comment by sroosa** [comment]
@caseyedavis12 I like your solution. We will have to get lists digitized GUIDs so that we can have the annotation added programmatically. And maybe also have the On Location annotation added to tall digitized assets as a default, and then we can change it to Website when we make that determination.

**Comment by sroosa** [comment]
@mccalluc I'm not exactly sure yet when we'll be able to see this in the data. We might have to wait until the AMS issues of data not appear get cleared up. Since there won't be any media on the site when it launches in March/April, I'm hoping this delay won't be too much of a problem.

**Comment by caseyedavis12** [comment]
Sounds good, @sroosa.

Once we have the Ci Ids we will be able to add the digitized annotation to all records with a Ci ID.

Good idea about adding on location to all records as a default at that time.

Best,
Casey

**Comment by caseyedavis12** [comment]
@Sroosa — good point. This functionality is an October 2015 deliverable.

**Comment by mccalluc** [comment]
@sroosa : Is this in the AMS yet?

**Comment by sroosa** [comment]
@mccalluc Annotations with type = Level of User Access have been added to all records that have a Sony Ci Id. All of those annotations currently = On Location
Kevin has a list of the records which need the annotation to be updated to = Online Reading Room, but I don't think he has made the change yet.

**Comment by caseyedavis12** [comment]
@sroosa and @mccalluc: How are we handling the new Access Layer, which is Digitized but not available on location until vetted? This will be the case for raw footage interviews with private people.

**Comment by sroosa** [comment]
@caseyedavis12 We are going to put some string in the Level of User Access annotation. We haven't determined the string yet. @mccalluc I don't know how the website will handle taking assets with that new string, and making it so that they don't appear on the website even at WGBH and LOC.
