### ISSUE TITLE
exec advisory council responsibilities not showing as bullets

### ISSUE THREAD

**Issue by rfraimow** [WGBH/AAPB2#750]
All bullets in the list of responsibilities for the executive advisory council are compressed into one paragraph: http://54.198.43.192/about-the-american-archive/executive-advisory-council

**Comment by rfraimow** [comment]
Still showing up incorrectly to me: http://americanarchive.org/about-the-american-archive/executive-advisory-council

**Comment by mccalluc** [comment]
@rfraimow : not deployed.

**Comment by rfraimow** [comment]
gotcha
