### ISSUE TITLE
Remove or update flash message about availability in Octover 2015

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#751]
@caseyedavis12 ideas for verbiage?
![image](https://cloud.githubusercontent.com/assets/1507490/10396373/2f991278-6e70-11e5-975e-da4183d2fb6b.png)

**Comment by caseyedavis12** [comment]
@afred @mccalluc: What about:


Please Note: Only some of the materials in the AAPB collection are available in the Online Reading Room. For more information about accessing the entire collection on location at WGBH or the Library of Congress, click here.

**Comment by mccalluc** [comment]
(@caseyedavis12 : Is just getting rid of that box an option? Maybe add a link to `/on-location` from the facet blurbs...)

**Comment by caseyedavis12** [comment]
@mccalluc: Good idea. Yes, we can just get rid of the box and add the link to on-location in the facet blurb.
