### ISSUE TITLE
Enable "Curated Exhibits"

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#765]
**DO NOT DEPLOY UNTIL Monday, 10/26**

**Done when:**
  * change any verbiage for "exhibition" to "exhibit"
  * section is added with title "Curated Exhibitions"
    * placement: below the map
  * contains rotating gallery -- may not need to rotate, since there are only 3 exhibitions
    * 3 items in rotating gallery contain the signature image (first img in markdown)
  * Add "Exhibitions" to main nav and floating nav for home page
  * Add "Curated Exhibitions" to the "about" menu, linking to /exhibits

**Comment by mccalluc** [comment]
@caseyedavis12 : Realize I don't understand whether
>
Add "Curated Exhibitions" to the "about" menu, linking to /exhibits

means adding a grey link to the banner at the very top, or adding it to the sidebar on the "about" pages.

**Comment by caseyedavis12** [comment]
@mccalluc: Please add to the sidebar on all the about pages.
