### ISSUE TITLE
External Reference URL annotation

### ISSUE THREAD

**Issue by rfraimow** [WGBH/AAPB2#771]
As per discussion this morning, metadata annotations of annotationType 'External Reference URL' should appear as part of the visible metadata on the website so that viewers can follow them to an external site. 

This is a workaround to allow external links for metadata-only assets for which we do not otherwise support playback.

**Comment by caseyedavis12** [comment]
@rfraimow @mccalluc: will these appear in the ORR filter? I hope so.

**Comment by mccalluc** [comment]
@caseyedavis12 : The ORR will still need to be set separately ... I think things get too weird if we let this override th

All: does this look like the logic we'll want?
```diff
     @access_level ||= begin
       access_levels = xpaths('/*/pbcoreAnnotation[@annotationType="Level of User Access"]')
       fail('Should have at most 1 "Level of User Access" annotation') if access_levels.count > 1
-      fail('Should have "Level of User Access" annotation if digitized') if digitized? && access_level
-      fail('Should not have "Level of User Access" annotation if not digitized') if !digitized? && acc
+      fail('Should have "Level of User Access" annotation if digitized or external url') if (digitized
+      fail('Should not have "Level of User Access" annotation unless digitized or external url') unles
       access_levels.first # Returns nil for non-digitized
     end
```

**Comment by rfraimow** [comment]
@caseyedavis12 @mccalluc Hmm, if I'm reading this right, we're requiring a "Level of User Access annotation" for an external URL, but I thought that was what we didn't want to do, and the reason for distinguishing between Outside URL and External Reference URL to begin with? The External Reference URL records shouldn't need a Level of User Access annotation, since we're not providing any media -- they're just metadata-only records in which the data happens to include a link to a location that may provide media, for which the AAPB is not responsible. But as metadata is visible for everything regardless, I don't think we should need a Level of User Access annotation.

**Comment by mccalluc** [comment]
Here's the direction I'm planning for this, starting from the user's experience. 
- We change the explanatory text on the facet:

old:
>
 **Available Online**
The default: All video and audio that can be viewed or listened to in the Online Reading Room. 

new:
>
 **Available Online**
The default: All video and audio available in the Online Reading Room *(add link to FAQ)* or elsewhere online.

- We use the same text on the item page regardless of whether it's an "Outside URL" or "External Reference URL":

>
View *(or listen)* online at Example Organization *(link)*

- I don't expect it to be common, but there can be multiples of these. Let me know if that should not be allowed.
- As with existing "Outside URL" items, these will not be playable on the AAPB, even if we do have media: If the idea is instead that there is supplementary information out there, but AAPB is still the best place to watch, (or if you think we might want to do that in the near-ish future,) please let me know.

@caseyedavis12 : I think this satisfies the underlying user need: I really, really to not want to get stuck on the idea that these should be in the ORR.
- From the user end, it just makes the concept of the ORR even more opaque if we claim it's in the ORR, but it's only playable on a third party.
- And from the back end, it will just be confusing if some xml isn't ORR, but the website claims it is.

**Comment by mccalluc** [comment]
We're all on same page: We do not know what what's on the other side of these URLs, so we won't do anything special with the faceting. Display message below player, though.
