### ISSUE TITLE
Style tweaks for grid view of exhibits items

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#774]
Done when:
  - [x] remove `.gallery` class (i.e. the flex grid stuff)
  - [x] use 3 cols for large screens, instead of 4
  - [x] use 2 cols for medium screens
  - [x] use 1 col for smallest screens, instead of 2
  - ~~set height of exhibit items to 400px~~ **no longer needed**

**Comment by caseyedavis12** [comment]
Thanks @afred. Is it possible for this to be added to the Launch milestone?

**Comment by afred** [comment]
refactored a bit to make one-off display logic for Exhibits "show all items" view a little less messy. Here are some screen shots...

**Exhibit blurb still displays, so hopefully no regression there.**
![image](https://cloud.githubusercontent.com/assets/1507490/10734641/a9103830-7bda-11e5-91a8-777f5f6d4959.png)

**Grid items are now height of 400px (and we can easily adjust this in css)**
![image](https://cloud.githubusercontent.com/assets/1507490/10734698/e8cfae42-7bda-11e5-80d2-ab805df3c20c.png)

**And if you remove the "Exhibit" facet from this page, it goes back to normal styling of search results (height=250px for grid items)."
![image](https://cloud.githubusercontent.com/assets/1507490/10734709/f440aae2-7bda-11e5-941e-661e8aa7bf6e.png)

**Comment by afred** [comment]
closed by #788
