### ISSUE TITLE
Reingest specific records

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#783]
**Done when:** records with the following IDs have been re-ingested.

cpb-aacip/28-kw57d2qp45
cpb-aacip/28-br8mc8rr6z
cpb-aacip/28-4t6f18sn70
cpb-aacip/28-cz3222rk4w
cpb-aacip/500-5q4rp59q
cpb-aacip/28-m61bk17469
cpb-aacip/28-sj19k46b34
cpb-aacip/28-2z12n4zs1w
cpb-aacip/28-h707w67k6x
cpb-aacip/28-k649p2wm6m
cpb-aacip/500-r785p02p
cpb-aacip/500-m9023j32
cpb-aacip/500-ff3m1j0m
cpb-aacip/500-cj87n27n
cpb-aacip/500-jq0svz1h
cpb-aacip/500-z60c1503
cpb-aacip/28-j09w08ws94
cpb-aacip/15-9862bb5r
cpb-aacip/28-xp6tx35q0h
cpb-aacip/15-289gj6vg
cpb-aacip/15-23612tg4
cpb-aacip/15-50tqk2fw
cpb-aacip/15-02c86fs0
cpb-aacip/15-945qgb91
cpb-aacip/28-bg2h70895r
cpb-aacip/28-zw18k75h85
cpb-aacip/15-9cj87k60
cpb-aacip/15-88qc028z
cpb-aacip/28-125q814w5v
cpb-aacip/28-mk6542jr2r
cpb-aacip/16-p843r0qc0z
cpb-aacip/46-65h9w6z2
cpb-aacip/15-7940r9m78p
cpb-aacip/15-2f7jq0sw07
cpb-aacip/16-9c6rx93p51
cpb-aacip/41-51vdnpkz
cpb-aacip/394-65h9wd4r
cpb-aacip/394-773txj1w
cpb-aacip/15-4947dkg7
cpb-aacip/16-222r49gf6t
cpb-aacip/15-3t9d50fw80
cpb-aacip/23-12m640f2
cpb-aacip/37-010p2nvv
cpb-aacip/15-87brvgz0
cpb-aacip/15-12m646qz
cpb-aacip/15-87brvgm3
cpb-aacip/15-1615f47p
cpb-aacip/28-1g0ht2gg9n

**Comment by caseyedavis12** [comment]
Please reindex when convenient. We are ready for go.

**Comment by caseyedavis12** [comment]
@afred: need to add one more record: cpb-aacip/15-9862bb5r 

If you have already started, don't worry about it.

**Comment by afred** [comment]
@caseyedavis12 `cpb-aacip/15-9862bb5r` is already in the list above

**Comment by caseyedavis12** [comment]
@afred: Whoops, nevermind. I thought I had put that one on hold.

**Comment by afred** [comment]
done! i have witnesses
