### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#791]
**Done when:** changes from all of the following branches have either been merged, or discarded, and branch has been deleted, or given a reason to keep it around:
  - About-Section-Navigation
  - Grid
  - Homepage-Navigation-Fix
  - curated-exhibits-page

**Comment by mccalluc** [comment]
- curated-exhibits-page: Originally, this was styling for the exhibits home page. I think we're happy with the way things are, and I've deleted the branch.
- Grid + About-Section-Navigation: @afred, you actually have the last commit on these, so I'll let you say if there's anything that should be preserved?
- Homepage-Navigation-Fix: was just the homepage navbar stuff. We have that problem with it not rendering on reload, and perhaps this was a stab at fixing that? I guess we should make sure we've got this solid before we delete old stuff we might look at for reference.

**Comment by afred** [comment]
`About-Section-Navigation` didn't have anything new. Deleted.
`Grid` just dried up `custom.jquery.js`, but another commit apparently did the same thing. Deleted.
`Homepage-Navigation-Fix`, :+1: for keeping until resolved. Is there a ticket?

**Comment by afred** [comment]
Whoops.. correction. The `Grid` branch actually [does other stuff](https://gist.github.com/afred/ca3d96ece1e8dea22d33) re: style, but I think it's all superseded by current design decisions. In any event, I learned [how to resurrect deleted branches](http://stackoverflow.com/questions/3640764/can-i-recover-branch-after-its-deletion-in-git) so if we decide we want anything from this, we can go get it.. but I think it's ok to keep it deleted.

**Comment by mccalluc** [comment]
At this moment, there is only a master branch.
