### ISSUE TITLE
Three items in Sadie's exhibit: Not in ORR

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#793]
There are three items in Sadie's exhibit which are not in ORR. We need to add these to the ORR.

**Comment by mccalluc** [comment]
@sroosa : update in AMS and then work with Kevin, or lean on us for a self-service option.

**Comment by sroosa** [comment]
@mccalluc I've got this sorted in the AMS, and can give someone a list of the GUIDs for which the new xml needs to be added to the website. I also noticed that the website doesn't seem to have updated which items are being pulled for the "Show All Items" results list. It's pulling at least one thing I deleted from my exhibition, and isn't pulling some of the things I added at the end.

**Comment by mccalluc** [comment]
@sroosa 
> It's pulling at least one thing I deleted from my exhibition
If you reindex that particular item it will know that it's no longer in the exhibit. (Exhibits don't keep track of what used to belong.)
> isn't pulling some of the things I added at the end
not clear whether you mean a redeploy or a reindex is necessary.

Still feels like a self-service reindex would help you guys, but I shouldn't be the one to push that.

**Comment by mccalluc** [comment]
@sroosa: Is anything blocking this?

**Comment by sroosa** [comment]
I fixed this in the AMS and had Kevin reingest all of the affected assets
