### ISSUE TITLE
Discussion: Make certain items available internationally?

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#804]
Could specific videos be made available without geo-blocking?

**Comment by mccalluc** [comment]
@caseyedavis12 : Sure, sounds like it's just some items, and not everything that's ORR? Hoping we get uniformity across all international regions? We'd make a new access level in the code, and decide how to represent it in the XML, both of which are easy. 

The tricky part I see is what to do with the facets: I could imagine we create a new subset of "online" (=ORR), maybe "online-int". This filter would only show up for international users (and they would not get plain "online" in the sidebar), and it would allow them to quickly focus on the media that will play where they are.

That's all that I can think of, so I'll close the discussion, but feel free to reopen or file a new bug for implementation.

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, for now it's just some items with no geo-restrictions. We are still waiting on research about opening up the entire collection.


Your idea for the Online-Int facet for people outside the US sounds great!

No action items here. Need to discuss with the legal counsel, but good to know that it can be done.
