### ISSUE TITLE
Clicking "View All Records" for an organization

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#816]
From Alan: When you click on “View All Records” for organizations, the left side menu has the “organizations” tab open with all the other organization listed. When you click on one, you get a list that adds the titles from that organization to the one originally selected. I can’t figure out the use of that. It only confuses things. If you don’t click on an organization and close that tab, then click on another limiting term, the organization tab opens again.

**Comment by mccalluc** [comment]
@caseyedavis12 : Not sure what he wants. Allowing the selection of multiple organizations was an explicitly requested feature. To remove an organization filter, you can either click the "X" beside it in the sidebar, or remove all filters on that field by clicking "X" in the filter list at the top.

**Comment by caseyedavis12** [comment]
@mccalluc: Could we just keep the organizations tab closed instead of expanding it?

**Comment by mccalluc** [comment]
@caseyedavis12 : Maybe: It's not something we've done before. Another possibility would be limiting the size of this list, and extra would need to be scrolled to, though that has its own problems. I'd want to understand the actual problem before jumping to a solution.

**Comment by caseyedavis12** [comment]
@mccalluc: I believe the reason why we wanted OR searches was to be able to show all records from one state, and to allow for OR searches across this facet in general. Here is Alan's response:

 Was the idea that users might want to see all materials from a particular state? If that was the intention, I can understand why this was done the way it was. But for me, the problem is two-fold: First, with the Organization tab automatically open, users have to scroll down quite a ways in order to limit the search by year, which I think will be a more common action than adding other organizations to the search. Second, this is offered under the “Limit Your Search” heading, but it actually adds to a search that begins with Organizations, rather than limiting it. So I think Casey’s idea is a good one, to keep the Organization tab closed until users manually open it themselves.
