### ISSUE TITLE
Sort by Title

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#818]
From Alan: It should ignore quotation marks at the beginning of titles. You may need to create a non-displaying “sort title” field, in which opening quotation marks are stripped out.

**Comment by mccalluc** [comment]
- see also #819 (transpose articles in titles)
- besides quotation marks: Initial articles? digits? non-alphanumerics?
- Implementation: This might be done just in solr, creating a new copy-to field with appropriate processing.
- As an index time feature, it requires a full reindex: We should be very sure we've covered all the cases... but we could do the reindex, and only after we're confident, change the UI to actually use the new sort field.

**Comment by caseyedavis12** [comment]
@mccalluc: From Alan: Is it possible to add the sort title field at this time and only change the ones in the ORR for now so that it does not require a full reindex? If so, the opening quotation mark is all that would need to be removed. (Titles with opening articles seem to fall into correct alphabetical order.) Another possibility would be to change sort titles for only the digitized material. In addition to double quotes at the beginning of titles, I found brackets, dollar signs, numbers, the symbol for number, single quotes, parentheses, and ellipses. In some cases, if you remove the first non-word character, another non-word character follows (e.g., #205).

**Comment by mccalluc** [comment]
Fix incoming. For debugging solr sorting, this is useful: http://localhost:8983/solr/#/blacklight-core/analysis?analysis.fieldvalue=the%20%22sorting%22%20test&analysis.fieldname=title

(Even on a stored field, the analyzed form isn't what comes back to us from a normal query.)
