### ISSUE TITLE
Articles in Titles

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#819]
Alan: Titles like “First Amendment, The” should appear as “The First Amendment” and can be sorted correctly if a non-displaying sort title field is created and populated with the correct way to sort titles.

**Comment by mccalluc** [comment]
- see also #818 (sort by title)
- How common is this? I'm reluctant to invest much time on this unless we actually have a fair number of docs that would be affected.
- Also do "A"/"An"? Foreign languages?
- Implementation: probably just at render time.
