### ISSUE TITLE
Review records for items in ORR

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#822]
From Alan: Items in the ORR need to be proofed better. For the “Civic Dialogue” series, the name of the series is often listed as an episode, so in the sort by title display, the episodes of the series are not listed together.

@sroosa: Can we put an intern on this?

**Comment by caseyedavis12** [comment]
@sroosa can I close this?

**Comment by sroosa** [comment]
@caseyedavis12: I think this fell through the cracks. I can take care of it this week, and I'll close it when I'm done.
