### ISSUE TITLE
Question: order of items in exhibit in "Show All Items"

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#824]
@mccalluc: If I were to number the items in an exhibit on each section page, will they appear in the order that I place them when a user clicks "Show all Items"? I am pretty sure that the answer is yes.

My next question is what if an item appears multiple times in an exhibit? Could I just put the same number next to that item every time it appears?

Thank you!

**Comment by mccalluc** [comment]
We just talked, and, no, that's not the way it works.
