### ISSUE TITLE
Missing thumbnails on ballet items?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#826]
http://americanarchive.org/catalog?q=ballet+competition&f[access_types][]=digitized

None of these have thumbnails. @Muraszko : Does this ring any bells? There are two plausible stories in my mind right now:
- Either these were skipped as a batch because they were adjacent during some stage of processing, and because of some hiccup they were missed.
- Or there's something weird about the underlying videos that tripped up your script.

Before closing this, would it be worth doing an inventory of the thumbnails and compare that to what's expected? I could help with the AWS scripting.

**Comment by caseyedavis12** [comment]
@mccalluc: these are Mississippi Public Broadcasting records. See #798 and #800 

cc @Muraszko

**Comment by caseyedavis12** [comment]
Actually, as @Muraszko pointed out to me, this is not the same issue as other Mississippi Public Broadcasting thumbnails. Other MPB thumbnails are looking for a GUID that has an underscore, and the GUID has a hyphen. But these MPB thumbnails for the ballet items have a hyphen in the thumbnail and in the record. Thumbnails should be named with an underscore. I do not know why they were named with a hyphen.

**Comment by Muraszko** [comment]
I can't seem to get the AWS command line tools installed on my machine.  But if someone with command line tools could connect to the AWS thumbnail bucket, they could do an "ls" for the file names, find the ones that have - or _ or whatever and rename the files?

**Comment by mccalluc** [comment]
I'll try...

**Comment by mccalluc** [comment]
The AMS link above is now happy, and the original link now has all the thumbnails that it should. Closing.
