### ISSUE TITLE
In Exhibits, Default sort by Year (oldest)

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#828]
Sorry if I'm beating a dead horse, but is it possible to sort by year (oldest) in exhibits and sort by relevance in regular searches?

Example: http://americanarchive.org/catalog?f[access_types][]=digitized&f[exhibits][]=civil-rights&sort=year+asc&view=list

**Comment by mccalluc** [comment]
Sure. Relevance order isn't useful here... but why not alphabetical? Date is fine, but if there is a motivation, that would be helpful to know.

**Comment by caseyedavis12** [comment]
@mccalluc: awesome! the motivation for sorting from oldest to most recent is so that people who explore the exhibit will do so chronologically. This is beneficial to all three exhibits and for future exhibits, in our opinion
________________________________
