### ISSUE TITLE
Future Development: About Menu drop down section for Projects

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#829]
In the future, we would like for the About Menu Projects tab to have a drop down section with sub-pages for each of our grant projects, so that we can have a page for each project and a place to post all of our required project reports.

**Comment by mccalluc** [comment]
@caseyedavis12 : got started on this with d8161768e86f.

![screen shot 2015-11-06 at 9 35 28 am](https://cloud.githubusercontent.com/assets/730388/10999708/8851feb4-846b-11e5-8431-1f98f4e509af.png)

- Does it look ok in menu in this screen shot?
- Is there still a "projects" page that stands on its own, or is it just a header for the list below? If it still exists, what goes in it?
- Titles? If there are shorter labels for the sidebar that would be awesome.
- I'll just move the content from the current projects page to the sub-pages, if that's ok?

**Comment by caseyedavis12** [comment]
@mccalluc: Thanks! Any chance we can have a bullet or hyphen next to each line? Currently it's hard to tell that these are four projects.


Suggested shortened versions:

Permanent Entity

NET Catalog

NDSR

Transcript Project

Yes for removing Projects page and putting project specific info on sub-pages. Thank you!

@sroosa - agree?

**Comment by sroosa** [comment]
@caseyedavis12 @mccalluc Looks good to me, guys!

**Comment by mccalluc** [comment]
> Any chance we can have a bullet or hyphen next to each line

With the shortened titles they won't line wrap and this will be more clear.
