### ISSUE TITLE
Links to NAEB content on Organizations page return no results

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#839]
@caseyedavis12 For a few organizations whose content was contributed by NAEB, we provide links that will conduct a search on the name of the participating organization. However none of these return any results. I understand the motivation here, but it seems misleading to provide a link to nothing useful.

Example: [Additional audio content from WUOA in Alabama](http://localhost:3000/catalog?&f%5Baccess_types%5D%5B%5D=all&q=%22WUOA%22)

**Comment by caseyedavis12** [comment]
@afred: this will change soon. We will be putting some NAEB material in the ORR very soon.

**Comment by afred** [comment]
sweet!
