### ISSUE TITLE
Help note for Year facet

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#841]
Please change this help text to say:

Cataloging in progress: less than half of records for digitized assets are currently dated.

**Comment by mccalluc** [comment]
@caseyedavis12 : Would you feel comfortable making this wording change yourself? You could [search](https://github.com/WGBH/AAPB2/search?q=%22Cataloging+in+progress%3A+Only+1%2F3+of+AAPB%22&type=Code) and then edit the files, just like you do for MD. Note that there are two files to be edited here, so you'd probably make a PR and edit one and then the other.

Or bounce to me if need be.

**Comment by caseyedavis12** [comment]
@mccalluc: yes, I can do this.

**Comment by caseyedavis12** [comment]
Fixed in #845
