### ISSUE TITLE
Homepage style regression

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#855]
The top padding of the `.jumbotron` which is currently set to `padding: 2em 1em;` on production, has somehow been lost, and is causing the following on my local machine. @mccalluc can you confirm please?

![image](https://cloud.githubusercontent.com/assets/1507490/11066036/6c9755f8-8794-11e5-9ff7-c4058782c2ac.png)

**Comment by afred** [comment]
@mccalluc this may have been introduced by #805, and I must not have gone back and looked at it like you asked me to do. Sorry about that.

**Comment by mccalluc** [comment]
@afred: Arg. Sorry. Yeah, I see that on my checkout too, and that's likely where it comes from. (Besides the plain rendering, it also needs to stick to the top during scroll.)
