### ISSUE TITLE
Discussion: Shared Solr instance or two Solr instances?

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#862]
Why would we want to share Solr instances on two servers? Is cost the only consideration?

**Comment by afred** [comment]
?? I'm just now seeing this. What is the context here?

**Comment by mccalluc** [comment]
@caseyedavis12 : I think we're comfortable with each web server having its own backing solr.
- If schema changes need to be made, that can be done on the secondary.
- If solr were shared, then it would need to be running on its own EC2, and we'd need to worry about communication between the web server and the rails server: Getting the right ports open, but making sure they are firewalled from the outside world.
- We'd also need to worry about building and maintaining the solr machine.

Closing.
