### ISSUE TITLE
Back-up server for AAPB public website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#863]
Can we pretty quickly get our back-up server up and running for this redeploy, or does it need to wait until December/January?

CC' @Muraszko in regard to developer time and consideration of other project timelines

**Comment by Muraszko** [comment]
December would be a good time for this, the rest of this month is busy with Fedora Camp and vacations, then in January Open Vault developer work can begin.  Does that work?

**Comment by caseyedavis12** [comment]
@muraszko: works for me

**Comment by mccalluc** [comment]
@caseyedavis12 : What do you want delivered for this? Two-server blue-green swapping (like OV) or something else?

**Comment by caseyedavis12** [comment]
@mccalluc: Yes, the two-server blue-green swapping like OV.

**Comment by afred** [comment]
**Done when**
  * can demonstrate a successful, full deployment, including provisioning with Ansible playbooks, and deploying with Capistrano.
  * can demonstrate a successful swap.

**Comment by afred** [comment]
this should have been closed a while ago. Not sure which tickets closed it, but both of the **done when** criteria are satisfied. Closing.
