### ISSUE TITLE
Weekly back-up of AMS XML

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#864]
We want a weekly back-up of PBCore XML (all 2.5 million records) from the AMS and stored on S3. 

Would weekly back-ups put too much strain on the server? Should it be monthly?

**Comment by mccalluc** [comment]
@foo4thought : Kevin, I think you're doing this?

**Comment by foo4thought** [comment]
Script is written and running on the host.  Let's watch to see what will be the period needed & frequency.  Backup to S3 to be created later, integrated, etc.

**Comment by caseyedavis12** [comment]
@foo4thought can I close this?

**Comment by foo4thought** [comment]
The operation completed and was so long-running, slow and problematic to be discounted as viable for anything but a "I need XML now."  The daily backup of mysql data to S3 is our friend here.
