### ISSUE TITLE
SDK scripts for website redeployment

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#865]
Developers to create an SDK script so that others can redeploy the AAPB website.

**Comment by caseyedavis12** [comment]
@mccalluc: given the Open Vault deadline, I don't think it's possible for us to complete this by February 1.

**Comment by mccalluc** [comment]
@caseyedavis12 : I believe this is what https://github.com/WGBH/aws-wrapper does. If you have something else in mind, please re-open.

**Comment by mccalluc** [comment]
oh, this is for AAPB. yeah, we're not using it here, yet.

**Comment by afred** [comment]
I think this is more of just demonstrating that the aws-wrapper scripts will work for AAPB too.

So far, I've run Ansible playbooks _and_ a Capistrano deployment on machines provisioned with the AWS Wrapper. There are more tweaks needed to get the website fully functioning, but those need to happen in other repositories.

Closing this, but if there is something else to be done here, please reopen and clarify.

cc @caseyedavis12 @mccalluc @Muraszko
