### ISSUE TITLE
Deploy code to AWS via OpsWorks

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#87]
There appears to be a few tweaks required to get it to deploy to our stack in AWS OpsWorks -- mostly adding special dependencies I think.

**done when**
Can deploy working code to AWS instance having been set up with OpsWorks
_OR_ we decide to abandon it for a regular old ec2 instance.

**Comment by caseyedavis12** [comment]
@afred: Is this done?

**Comment by afred** [comment]
no longer relevant
