### ISSUE TITLE
"About" Menu on Exhibits Page

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#872]
The "About" Menu on the Exhibits Page does not have the list of Projects in the Menu. 

Done when: List of projects appears below Projects on the About menu.

**Comment by caseyedavis12** [comment]
@mccalluc: can this be done for the 2/1 redeploy? I would do it but don't know where to look in the code.

**Comment by mccalluc** [comment]
Actually, on http://americanarchive.org/exhibits the "Projects" link in the sidebar is simply broken. Not sure why the sidebar here is different than other places.
