### ISSUE TITLE
americanarchiveinventory.org: CNAME & Redirect to fix host

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#878]
- Replace existing A record for americanarchiveinventory.org with a CNAME pointing to americanarchive.org
- In rails, redirect if we see this hostname on a request.

(Check to confirm that our DNS doesn't provide HTTP redirects.)

**Comment by mccalluc** [comment]
It looks like an S3 redirect was put in place, but to **www.**americanarchive.org, which is not a name we have registered. I'll file a new IT ticket, since I assume they are the folks who handle this.

Incident ID = 56916
>
I believe that you guys have S3 set up to redirect from americanarchiveinventory.org -> www.americanarchive.org
>
```
$ curl -I http://americanarchiveinventory.org
HTTP/1.1 301 Moved Permanently
x-amz-id-2: D19jSRTO+vlbY75dZKTPe6EsQ80AbX5fA/SaR5oaPq+O57kpbEVgDBsF+mAYjrpb24dtdvSxqyU=
x-amz-request-id: CC5ABF0B60E6A3DE
Date: Wed, 06 Jul 2016 17:35:39 GMT
Location: http://www.americanarchive.org/
Content-Length: 0
Server: AmazonS3
```
>
The "www." should not be there: That domain name is not registered. (The target hostname is also something you control: if you strongly believe "www." should be supported, we could consider that.)

**Comment by mccalluc** [comment]
Here's their response. I won't be able to follow up on this.
>
[Ryan Groth -- 07/12/2016 11:23:00 AM]
I'm not 100% clear on what you're asking/proposing... at the time of your request, www.americanarchive.org did exist, and because CNAME can not be done on the apex of a domain (or naked domain), and americanarchiveinventory.org is redirecting, going straight to www eliminates an additional s3 request and redirection. I'm guessing the www disappeared when you moved the nameservice to WordPress for americanarchive.org.
>
It's a commonly held best practice to use "www." for websites, as this eliminates the naked/apex domain issues in addition to eliminating issues with cookies.
>
I see that you're using an ELB in AWS anyway, so the best practice would be to point all the names that you'd like directly at the ELB.
>
More than happy to discuss further if you'd like, or about MLA's strategies in general. Let me know what you'd like.

**Comment by caseyedavis12** [comment]
@mccalluc: I think that this can be fixed in the Wordpress Domain Hosting. I can do this but would like to be there when I do it in case I have questions. I will be back in the office on Thursday.

**Comment by caseyedavis12** [comment]
I just checked and confirmed that americanarchiveinventory.org and www.americanarchiveinventory.org redirect to americanarchive.org.
