### ISSUE TITLE
access control on media, instead of just at the record level?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#879]
For the NH Presidential collection we'll be receiving audio files which need to be redacted. The original idea was to create two records, one ORR, and and on-site-only which is unredacted. This is clumsy for a number of reasons. (We'd be creating multiple records; how does an on-site user find the version that's good for them; the redacted one can go away once we get clearance from NPR, etc.)

Here's the code that matters:

`pb_core`:
```ruby
  def ci_ids
    @ci_ids ||= xpaths("/*/pbcoreIdentifier[@source='#{SONY_CI}']")
  end
  def media_srcs
    @media_srcs ||= (1..ci_ids.count).map { |part| "/media/#{id}?part=#{part}" }
  end
```
  
`media_controller`:
```ruby
  if can?(:play, pbcore) && (current_user.aapb_referer? || current_user.embed?)
    ci = SonyCiBasic.new(credentials_path: Rails.root + 'config/ci.yml')
    # OAuth credentials expire: otherwise it would make sense to cache this instance.
    redirect_to ci.download(pbcore.ci_ids[(params['part'].to_i || 1) - 1])
  else
    render nothing: true, status: :unauthorized
  end
```

@foo4thought : Ultimately, the distinction needs to be made in the AMS. Would it be possible to have something like ...?
```xml
  <pbcoreIdentifier source='Sony Ci' annotation='on-site-only'>a-32-digit-hex</pbcoreIdentifier>
  <pbcoreIdentifier source='Sony Ci'>another-32-digit-hex</pbcoreIdentifier>
```
so we can distinguish between the on-site and ORR media.

cc: @caseyedavis12

**Comment by foo4thought** [comment]
Yes, that makes sense to both man and machine.

**Comment by mccalluc** [comment]
@caseyedavis12 : trying to see into the future, do you think `unredacted` might be the best value to give the attribute? Or is that too specific?

@afred: So for the mechanics, I think we'll add another "can" to `Ability`: `can :play_unredacted`, perhaps? and then in the view:

```
<% if !@pbcore.media_unredacted_srcs.empty? && 
        !@pbcore.outside_url &&
        can?(:play_unredacted, @pbcore) %>
```
and then if there are media_unredacted_srcs, but they can't be played, include a brief note explaining that fact, and show only the plain media_srcs. @caseyedavis12 : does that sound ok for UI?

**Comment by afred** [comment]
@mccalluc would it make more sense to put the conditionals in the `MediaController`, along with the other ones (see above)?

**Comment by mccalluc** [comment]
They're complementary, and we need both: The MediaController is a backstop to prevent unauthorized access to media, but we also need the UI to be smart enough that only the appropriate media is requested in the first place.

**Comment by afred** [comment]
@mccalluc ok that's fine

**Comment by caseyedavis12** [comment]
@mccalluc: currently in February redeploy, but if not possible, please move to Spring 2016 redeploy. Either is fine.

**Comment by caseyedavis12** [comment]
@mccalluc and @foo4thought: The redacted proxies will have a -2 at the end of the filename. Only two files needed to be redacted. All others are fine and can be made available on-site and in the Online Reading Room.

**Comment by afred** [comment]
@caseyedavis12 after talking with @mccalluc we thought maybe it would be ok to just put up the redacted versions as the "main" versions, and when we eventually get clearance to put up the full versions, we'll just do a replacement.

The downside is that those who _do_ have permission to view the full, non-redacted, version would have to just wait until we got clearance for the public at large. The upside, is much less developer time figuring out how to accommodate two copies of media with different permissions, for a single item.

Is that ok?

**Comment by caseyedavis12** [comment]
@afred, @mccalluc, @foo4thought: Yes, this is fine with me.

**Comment by mccalluc** [comment]
Closing this. We can revisit in the future if it would be more useful.
