### ISSUE TITLE
New exhibit folder for presidential-elections

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#883]
@mccalluc: Can you create a new folder in the exhibits folder for presidential-elections?

**Comment by caseyedavis12** [comment]
@mccalluc: can you do this in my presidential-elections branch soon so that I will have the folder ready to add content over the next week?

**Comment by mccalluc** [comment]
This was put in place yesterday: https://github.com/WGBH/AAPB2/tree/presidential-elections/app/views/exhibits/presidential-elections

closing.
