### ISSUE TITLE
Add Presidential Elections exhibit to github

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#885]

**Comment by mccalluc** [comment]
@caseyedavis12 : your latest commit broke the build.

**Comment by mccalluc** [comment]
@caseyedavis12 : I made a branch that fixed the build, and then I made a branch from that for you to work on the presidential exhibit. https://github.com/WGBH/AAPB2/tree/presidential-elections. When it's ready to go, issue a PR for that branch.
