### ISSUE TITLE
organizations.yml: Wash U is 404

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#887]
http://library.wustl.edu/units/spec/filmandmedia/ is 404 right now.

**Comment by caseyedavis12** [comment]
@sroosa can you change this URL to http://library.wustl.edu/spec/filmandmedia/about/ in the Organizations.yml? I don't know where this is located.

**Comment by mccalluc** [comment]
@caseyedavis12 : Click on "Find File" on the homepage of this project -> https://github.com/WGBH/AAPB2/find/master

**Comment by caseyedavis12** [comment]
@mccalluc: it's not there.

**Comment by sroosa** [comment]
i just changed it. the file is in config, not app.

**Comment by sroosa** [comment]
Just doubled checked, and this is fixed.
