### ISSUE TITLE
The top image on collection pages should not have a space below

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#900]
civil-rights/people does it right:

```
![Thomas J. O’Halloran, photographer. ...](https://.../CivilRights_People.jpg "...")
Actions described include boycotts, sit-ins, voter registration drives, freedom rides, marches, 
and a host of direct action campaigns to confront segregation and discrimination.
```

If there's an extra new-line after the image, then it gets wrapped in its own `<p>`, and the text doesn't align to the top of the image.

**Comment by caseyedavis12** [comment]
@mccalluc: I can fix this. Do I need to create a new branch off of presidential-elections or commit to presidential-elections branch?


best,

Casey

**Comment by mccalluc** [comment]
@caseyedavis12 : just pushed a fix.
