### ISSUE TITLE
"Projects" link in footer is 500: Error

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#912]
We no longer have a general projects page, so we need to list all projects. Do we have room for a new column in the footer to list all projects?

**Comment by caseyedavis12** [comment]
@mccalluc: Can we list all Projects in the footer page and link to each project page? Or do you think we should recreate the general Projects page with links to each project page?

**Comment by mccalluc** [comment]
I'd like to separate the issues:
- Bad link: quickest fix is to delete, and we should also add more link checking machinery. I'll do this.
- Projects need more prominence? I think we have too many links in the header and footer and sidebar already. I think we should not add any more links, unless we can prune back some other ones.

that said:

- maybe could add it to footer. we'd need to combine two of the shorter columns. We need to do some indenting to make the linewraps more readable, but we have such a hodgepodge of links down here already that usability is compromised. 
- New "projects" page? sure. If we could get rid of the sublist in the sidebar, that would also be good.

**Comment by caseyedavis12** [comment]
@mccalluc: Thanks for parsing out the issue.


I say we

  *   Create new New "projects" page with links to each project
  *   Get rid of the sublist in the sidebar
  *   Keep general "Projects" page in footer

I can tackle this.



________________________________

**Comment by caseyedavis12** [comment]
This is fixed with recent merges #924
