### ISSUE TITLE
Acquisitions form: boxes on input areas?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#920]
Not a big deal, but if there were boxes or a very light background shading it would make the form a little easier to fill out. Without that visual indication, it's not obvious that it can be filled in in the PDF. (Particularly with the name fields, I first tried clicking to the right of the label, and that obviously wouldn't work.)

**Comment by caseyedavis12** [comment]
@mccalluc: We will fix this.

**Comment by caseyedavis12** [comment]
@mccalluc: This is fixed.

**Comment by mccalluc** [comment]
@caseyedavis12 : feel free to close issues when you think they're fixed, unless you want someone else to double check.
