### ISSUE TITLE
smart quotes on deed

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#921]
In the first paragraph, there a mix of quote styles that looks a little odd. Not a big deal.
<img width="596" alt="screen shot 2016-04-08 at 10 30 54 am" src="https://cloud.githubusercontent.com/assets/730388/14387365/0ef7c35c-fd77-11e5-91d8-c97135f6246e.png">

**Comment by caseyedavis12** [comment]
@mccalluc: Agree, not a big deal.
