### ISSUE TITLE
bad inside links

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#931]
- Got 404 from http://localhost:3000/net-catalog instead of 200
- Got 404 from http://localhost:3000/net-catalog/programs instead of 200
- Got 404 from http://localhost:3000/net-catalog/series instead of 200
- Got 404 from http://localhost:3000/net-collection/series/special-of-the-week instead of 200
- Got 404 from http://localhost:3000/net-collection/series/spectrum instead of 200
- Got 404 from http://localhost:3000/net-collection/series/whats-new instead of 200
- Got 404 from http://localhost:3000/projects instead of 200

**Comment by caseyedavis12** [comment]
@mccalluc: can you investigate and fix if needed?

**Comment by mccalluc** [comment]
none of those links are in the ignore file now, and there aren't any special cases in link_checker.rb, so I think it's fixed.
