### ISSUE TITLE
relative links are trouble

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#932]
-  advocacy
-  candidates
-  catalog/cpb-aacip_15-7940r9m823
-  catalog?f[organization][]=Appalshop, Inc. (KY) OR KET - Kentucky Educational Television (KY)
- (and all the other org links)
-  causes
-  communicating-art
-  impacts
-  net-catalog/programs
-  net-catalog/series
-  series/at-issue
-  series/fanfare
-  series/intertel
-  series/local-issue
-  series/music-strip
-  series/net-drama-festival
-  series/net-festival
-  series/net-journal
-  series/net-playhouse
-  series/net-playhouse-biography
-  series/net-symphony
-  series/perspectives
-  series/realities
-  series/special-of-the-week
-  series/spectrum
-  series/whats-new
-  solutions
-  voters-issues

**Comment by caseyedavis12** [comment]
@mccalluc: can you investigate and fix?

**Comment by mccalluc** [comment]
seems to be fixed.
