### ISSUE TITLE
"What's new" is missing

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#933]
@sroosa :
```
$ grep whats-new -r app/views
app/views/override/about-the-american-archive/projects/net-catalog/programs.md:**The Chamizal Story**: produced in 1964 by KUHT. *Aired as an episode of [Local Issue](/about-the-american-archive/projects/net-catalog/series/local-issue) and [What's New](/about-the-american-archive/projects/net-catalog/series/whats-new).*<br />
app/views/override/about-the-american-archive/projects/net-catalog/series.md:**What's New**: an anthology series focused on news and public affairs, with episodes from various producers. [More information about individual episodes](/about-the-american-archive/projects/net-catalog/series/whats-new).<br/>
```

but there is no corresponding markdown. My next PR will put a placeholder in there, but I'm not sure what content you want.

(To reiterate, I think trying to manage huge data rich pages like this in MD is not a good idea, in general.)

**Comment by sroosa** [comment]
@mccalluc I'm definitely seeing things your way. This page actually shouldn't exist, the link was put in there accidentally. There is one thing on the program.md page that also links to it, but I will be deleting that.

**Comment by mccalluc** [comment]
I've got a branch out where I'm working through a lot of these, so I'll fix it there. Thanks!
