### ISSUE TITLE
Popup archive getting 401 unauthorized when trying to access media URLs

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#944]
**background:** [In this code](https://github.com/WGBH/AAPB2/blob/3574dcb82e1870aefb79122bfe8899b86e3a9a07/app/controllers/media_controller.rb#L9-L15) we are hitting the `else` clause which responds with the "401 Unauthorized". The reason we're falling into the `else` is because the the `can?(:play, pbcore)` condition is failing, and that is failing because of [how it is defined](https://github.com/WGBH/AAPB2/blob/3574dcb82e1870aefb79122bfe8899b86e3a9a07/app/models/ability.rb#L7-L10)... in particular, because `popuparchive.org` is not considered "on site", it's requiring the check for TOS, which is failing.

This could be solved by just adding `popuparchive.org` to the IP ranges considered to be "on site". If we don't want to do that, then we need to adjust the conditional logic to make an allowance for the `popuparchive.org` referrer.

**Done when** media URLs do not return 401 when referrer is `popuparchive.com`

**Comment by afred** [comment]
@mccalluc this cropped up while you were gone. I got as far as PR #945, but I'm not sure it solves anything, because I've been having a hard time reproducing their error.

Any ideas on where things might be getting hung up?

**Comment by mccalluc** [comment]
Two lessons learned:
- `--referer 'http://americanarchive.org/;auto`
- DO NOT use `-I`: S3 does not accept `HEAD` requests, though it does accept `GET`.

**Comment by mccalluc** [comment]
@afred / @caseyedavis12 : I think we determined that it's not a problem with our code, but rather with the curl arguments they were using. I wasn't on the thread... can one of you follow up with them and close this is nothing else needs to be done on our end?

**Comment by caseyedavis12** [comment]
@afred would you be willing to send a note to Bailey and Anne confirming that we have done all we can do regarding this issue?

________________________________

**Comment by afred** [comment]
you bet. Stand by.

**Comment by afred** [comment]
followed up with email to Bailey and Anne, instructing to try the modified curl command, with the correct value for `--referer` and without the `-I` option, and if it still doesn't work, then we should set aside some time to do live trouble shooting.

closing.
