### ISSUE TITLE
Org page, states list in sidebar: can't see the bottom

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#948]
Because the menu now follows you, we can't actually get past "Missouri" (depending on how big your window is.) 
- Ignore?
- One off override for this page?
- Bigger tweak for multicolumn sidebar?

(I'm happy to ignore.)

**Comment by caseyedavis12** [comment]
@mccalluc: Can I see a screenshot or come over and look at your computer?


________________________________
