### ISSUE TITLE
Update AMS SSL key

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#949]
**Done when** tests that depend on communication with AMS no longer throw errors due to expired SSL cert.

**Comment by mccalluc** [comment]
@afred : Kevin just did the file by hand, but test failures will continue until AMS key is updated. Change title to reflect changed approach.

**Comment by afred** [comment]
@mccalluc updated the **done when**. Does that wound right?

**Comment by mccalluc** [comment]
Understanding that we actually want to update the key, rather than loosening the tests. Either approach is possible.
