### ISSUE TITLE
Remove deployment code from Stash?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#956]
@afred, could this be deleted? I'm going to change the README to remove this reference.

https://atlas.wgbh.org/stash/projects/MLA/repos/aapb_deployment

**Comment by afred** [comment]
@mccalluc No, that's the only place where that lives. It's in Stash because it has secrets

**Comment by mccalluc** [comment]
Got it: This is the Capistrano, and it has Ci keys, and so it needs to be private, while OV doesn't have any secrets, so it can be on github.
