### ISSUE TITLE
Menu overlapping content on cmless pages at certain widths.

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB2#961]
To reproduce:
  1. go to an "about" page that has sidebar navigation, such as /about-the-american-archive
  2. reduce window width from widest to just above the first break point.

Example:
![image](https://cloud.githubusercontent.com/assets/1507490/15046520/255a6180-12ae-11e6-93fc-ffb4249b990c.png)

**Comment by mccalluc** [comment]
Actually, this is related to the sticky sidebar. When that is reverted (PR #963), you no longer get this behavior. Wait to close this until that is merged.
