### ISSUE TITLE
AMS should know if there is a transcript, rather than pinging S3

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#971]
Deciding on a format (#970) is not strictly a prereq, but may be useful.
- @foo4thought will account for the existing SRTs, and think about how to accommodate the incoming data, in the AMS
- @mccalluc will adjust the ingest script to trust the AMS, rather than pinging S3

(Transcripts will still be stored on S3: that doesn't need to change.)

**Comment by mccalluc** [comment]
@foo4thought : Assigning this to you since the first step is the AMS. (Reminder to self that this isn't necessary on my end, but a decision about data management, and if it turns out to be hard, we could give up.)

**Comment by sroosa** [comment]
Being resolved in #1188
