### ISSUE TITLE
OAI: split titles in MODS

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#976]
Eben writes:
>
Right now it looks like the titles are a concatenation of "[series]; [episode number]; [episode title]", as in the case with item 'cpb-aacip_260-64gmsjf3':
>
```
  <titleInfo usage="primary">
    <title>"Main Street, Wyoming Classics"; 102; Heart Mountain</title>
  </titleInfo>
```
>
We'd recommend splitting this up in the MODS like so:
>
```
  <!-- episode title -->
  <titleInfo usage="primary">
    <title>Heart Mountain</title>
  </titleInfo>
  <!-- series title -->
  <relatedItem type="series">
    <titleInfo>
      <title>"Main Street, Wyoming Classics"</title>
    </titleInfo>
  </relatedItem>
  <!-- episode number -->
  <note>Episode Number: 102</note>
```
>
This way we can reliably determine what the series title is, and provide a way to link it in the metadata display, similar to how it's displayed on americanarchive.org.

**Comment by mccalluc** [comment]
@caseyedavis12 / @sroosa : could either of you comment on this? I have this vague memory that we decided to do the titles this way because the data-quality wasn't at a level where we could confidently confidently distinguish these different parts of the title.

**Comment by caseyedavis12** [comment]
@sroosa: Do you think that our data is good enough to separate by Series, Program, Episode, and Episode Number? We could also add a catch-all type "AAPB Title" for all titles that do not have any of these types associated with them.


What do you think?


cc @mccalluc

________________________________

**Comment by sroosa** [comment]
@caseyedavis12 and @mccalluc : I think that the data for the content in the ORR is probably good enough to split into the title types casey lists above. Using "Title," "Item Title," or "AAPB Title" for anything that doesn't have one of those four types seems like a good way to handle the remaining titles.

**Comment by mccalluc** [comment]
So we have a lot of potential title types: this list is derived from `title-type-map.yml`:
```
Label
Collection
Series
Program
Segment
Episode Number
Episode
Clip
Promo
Raw Footage
Album
Title
```
(The order here is the order titles come in the semi-colon delimited string. The general idea is that higher-level titles come first. It could have been done differently, but one advantage of this is that an alphabetical title sort on our site will reflect the hierarchical structure.)

Looking at the example from him, it seems like there are three possible ways of disposing of a title:
- It can be primary,
- it can actually be the name of a related item,
- or it can be shoved in a note.

I propose that:
- The last (ie finest grained) title is taken for the primary.
- Of those that remain "Label", "Episode Number", "Raw Footage", and "Title" are used as notes
- and the others are related items.

(For instance, an "Episode Number" isn't a type of item we can be related to: The others feel similar to me, so I'll put them in notes.)

**Comment by caseyedavis12** [comment]
@mccalluc: sounds good to me. Do you want to ask Eben if he agrees with this plan?


cc @sroosa

________________________________

**Comment by mccalluc** [comment]
@caseyedavis12 : just emailed him.
