### ISSUE TITLE
Add new orgs to the organization.yml file

### ISSUE THREAD

**Issue by sroosa** [WGBH/AAPB2#987]

**Comment by sroosa** [comment]
@mccalluc : I have these ready to go, and I was thinking I would add them when the current pull request for that branch got merged. Does that make sense? Also, I think there might be 1 problem, which is that 1 of the new organizations has a ID that has a space in it. Should I get Kevin to change the ID, so there is no space in it, or will it allow a space in the md file's name?

**Comment by mccalluc** [comment]
We talked: spaces in IDs might work, but probably could be confusing over time. Data will be updated in AMS, and then there will be a PR.

**Comment by mccalluc** [comment]
@sroosa : I believe the new MD files have been created. (Where the configuration now lives.) Is there anything else that needs to be done here? If not, close.
