### ISSUE TITLE
Organization logos not appearing on website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#993]
Participating Organization logos are not appearing on the website. Here are two examples:

http://americanarchive.org/participating-orgs/1293

http://americanarchive.org/participating-orgs/NCSG43

@mccalluc, could you make sure this is fixed before the next redeployment?

cc @Muraszko

**Comment by caseyedavis12** [comment]
@mccalluc I just noticed that this is still a problem. See here for example: http://americanarchive.org/participating-orgs/NCSG43

**Comment by mccalluc** [comment]
@Muraszko : It looks like the earlier PR was not deployed?

**Comment by Muraszko** [comment]
@caseyedavis12 @mccalluc Sorry guy, my fault.  I had another step to do and forgot.  I'm jumping on it now.

**Comment by Muraszko** [comment]
Fixed.
