### ISSUE TITLE
Media not playing on website

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#994]
From Alan Gevinson: When I click on the start button on a record with media, the button turns from white to gray and then nothing happens. I've tried to use Chrome and Safari. 

Confirmed by Casey.

@mccalluc, this is high priority.

cc @Muraszko

**Comment by mccalluc** [comment]
Videos are playing again. We did a swap yesterday, and didn't notice that videos weren't playing. Filing new bug for getting ci.yml to persist across deployments.
