### ISSUE TITLE
OAI-PMH feed: readme documentation

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#999]
Since only records that are available in the ORR are harvestable by the OAI-PMH feed, we should update documentation to clarify that only those records can be harvested that way.

Currently, the documentation states (emphasis added): 

"If you want **all** of our records, the best approach is OAI-PMH. We don't support all the verbs, or any formats beyond MODS, but this is enough to get the records:"

**Comment by mccalluc** [comment]
@caseyedavis12 : Edits to the documentation can be made just like you'd make edits to config files, and in less time than it would have took to file this bug. Am I missing something?

**Comment by caseyedavis12** [comment]
@mccalluc: can you clarify how many records are available using the PBCore API? All 2.5 million, all digitized or ORR only?

________________________________

**Comment by mccalluc** [comment]
From my email yesterday:
>
https://github.com/WGBH/AAPB2/blob/b1c0abc/app/controllers/oai_controller.rb#L23
>
ie, ORR, and that is the only constraint applied.

http://americanarchive.org/catalog?f[access_types][]=online -> 13,611

**Comment by mccalluc** [comment]
@caseyedavis12 : Is there anything more to be done here? I believe you handled this in e24793045. Please close if so.
